<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_(28073485)(wells.wang1budweiserapac.com)</name>
   <tag></tag>
   <elementGuidId>0f817ade-9ed7-4b26-92f3-54433ad6300d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_easyui_combobox_i2_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_easyui_combobox_i2_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>02671b1c-43b9-4aa0-a4d1-ddf8f5f8af56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_easyui_combobox_i2_0</value>
      <webElementGuid>cfb38ef5-ded7-42c0-a9f8-f9df99ac267b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combobox-item combobox-item-selected combobox-item-hover</value>
      <webElementGuid>9676dbe6-0a1e-4181-99cf-115f53a5ef9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>汤环宇(28073485)(wells.wang1@budweiserapac.com)</value>
      <webElementGuid>397133d6-8747-4c13-bd1c-93717f7d7d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_easyui_combobox_i2_0&quot;)</value>
      <webElementGuid>ba5c55ca-337b-4313-9d3c-f533f68e5f8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/SignatureBoard/batchauthorize_page/iframe__BatchAuthListFrame</value>
      <webElementGuid>fb342089-1371-4ae7-9f11-aadd9f2b95ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='_easyui_combobox_i2_0']</value>
      <webElementGuid>db435bfc-dd96-4a31-a2d0-407353f2a502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '_easyui_combobox_i2_0', '&quot;', ')')])[1]/following::div[3]</value>
      <webElementGuid>5599794b-15a3-47f0-aaf8-4fc3b0e6d201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='显示1到2,共2记录'])[1]/following::div[13]</value>
      <webElementGuid>90539322-4a95-4c3d-8571-2ac9757483b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='汤环宇(28073485)(wells.wang1@budweiserapac.com)']/parent::*</value>
      <webElementGuid>8c11bdf7-51d3-4128-95ca-8edffb0b8d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>67ec5665-44be-44b1-a3f8-fc40aec0b9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '_easyui_combobox_i2_0' and (text() = '汤环宇(28073485)(wells.wang1@budweiserapac.com)' or . = '汤环宇(28073485)(wells.wang1@budweiserapac.com)')]</value>
      <webElementGuid>c6d43049-b4f8-4f3a-a8af-f0b13ef35176</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
