<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_(28070491)(wells.wang1budweiserapac.com)</name>
   <tag></tag>
   <elementGuidId>e9f617a9-f12c-4fdd-b175-74451c5df4fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_easyui_combobox_i1_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_easyui_combobox_i1_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>37a6f15f-231e-406c-8228-464cdd1123e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_easyui_combobox_i1_0</value>
      <webElementGuid>f8d8cdfb-f957-49b1-a059-0960dedc74c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combobox-item combobox-item-selected combobox-item-hover</value>
      <webElementGuid>15ff8c0c-eabf-4a04-beeb-fa66bfc5997f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>王海建(28070491)(wells.wang1@budweiserapac.com)</value>
      <webElementGuid>7a4d3fc1-1cfa-480a-8e60-7ef3afebe9e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_easyui_combobox_i1_0&quot;)</value>
      <webElementGuid>6a820bd0-1e52-4663-ae9c-be76b8b69e03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/SignatureBoard/batchauthorize_page/iframe__BatchAuthListFrame</value>
      <webElementGuid>2bf82e85-de10-43b3-9471-f4ffa606b5a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='_easyui_combobox_i1_0']</value>
      <webElementGuid>36328270-34c4-42f4-a868-39e541fa2925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '_easyui_combobox_i1_0', '&quot;', ')')])[1]/following::div[3]</value>
      <webElementGuid>09b5c9d6-d431-4cbe-aa70-f952e34e6494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='显示1到1,共1记录'])[1]/following::div[13]</value>
      <webElementGuid>a2a54db8-adb0-4c53-8309-37dde5adf1f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='王海建(28070491)(wells.wang1@budweiserapac.com)']/parent::*</value>
      <webElementGuid>5d884d58-e74c-40d5-9663-b037cf312385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>b9614a5e-e442-4168-af6b-304ffc0e5bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '_easyui_combobox_i1_0' and (text() = '王海建(28070491)(wells.wang1@budweiserapac.com)' or . = '王海建(28070491)(wells.wang1@budweiserapac.com)')]</value>
      <webElementGuid>e75cd9dc-cd88-4058-92bf-57a30947c988</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
