<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__ifm</name>
   <tag></tag>
   <elementGuidId>c5bb464e-a792-47a2-b77e-1a833bd620a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ifm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c1a93c9c-1ef4-40d2-b656-31bc69cd5e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifm</value>
      <webElementGuid>d970f564-a39d-47f1-8066-69558bba4a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7979ebd6-cb96-4224-a0f2-0b042bd12a2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>85cf6ed1-d4ee-4be7-a7d7-17ee13858b2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ifm</value>
      <webElementGuid>7067664b-6c4d-42aa-a224-87f8bdcf2202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DASContractSignUp/BWProcess/ConTractRelatMy/Page/ConTractMyTempletN.cshtml?mainTone=Index&amp;strUserUltCode=BPM/28070907&amp;CurrentLanguage=zh-CN&amp;rnd=0.7791662529475305</value>
      <webElementGuid>8a4f62bb-fd84-4f61-a422-4af846c873fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-header-fixed&quot;]/div[@class=&quot;page-container row-fluid&quot;]/div[@class=&quot;divContent&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;ifmBg&quot;]/div[@class=&quot;col-md-12&quot;]/iframe[@id=&quot;ifm&quot;]</value>
      <webElementGuid>2a3575f7-a1da-4e45-8d72-45f33138b04f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifm']</value>
      <webElementGuid>a2da5533-18c0-4812-aa5a-1f0103976329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>04ba6372-3b8d-4fca-8ce4-c7ee24b94df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ifm' and @name = 'ifm' and @src = '/DASContractSignUp/BWProcess/ConTractRelatMy/Page/ConTractMyTempletN.cshtml?mainTone=Index&amp;strUserUltCode=BPM/28070907&amp;CurrentLanguage=zh-CN&amp;rnd=0.7791662529475305']</value>
      <webElementGuid>66228fa0-8de7-4155-9652-ec915d134deb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
