<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkbox_all</name>
   <tag></tag>
   <elementGuidId>2739da73-1927-4c11-a3ca-64b36a44ec03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;checkbox&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6d55b917-8409-4f6f-b66d-be03e6528429</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c10bbd69-fc95-44ee-8ee2-6a46753dea0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ConTractCSMDiv&quot;)/div[@class=&quot;easyui-layout layout easyui-fluid&quot;]/div[@class=&quot;panel layout-panel layout-panel-center panel-htop&quot;]/div[@class=&quot;panel-body panel-body-noheader layout-body panel-noscroll&quot;]/div[@class=&quot;easyui-layout layout easyui-fluid&quot;]/div[@class=&quot;panel layout-panel layout-panel-center panel-htop&quot;]/div[@class=&quot;panel-body panel-body-noheader layout-body panel-noscroll&quot;]/div[@class=&quot;panel datagrid panel-htop easyui-fluid&quot;]/div[@class=&quot;datagrid-wrap panel-body panel-body-noheader panel-body-noborder&quot;]/div[@class=&quot;datagrid-view&quot;]/div[@class=&quot;datagrid-view1&quot;]/div[@class=&quot;datagrid-header&quot;]/div[@class=&quot;datagrid-header-inner&quot;]/table[@class=&quot;datagrid-htable&quot;]/tbody[1]/tr[@class=&quot;datagrid-header-row&quot;]/td[@class=&quot;datagrid-header-over&quot;]/div[@class=&quot;datagrid-header-check&quot;]/input[1]</value>
      <webElementGuid>f45965d0-930f-400c-82c7-4c9f6e5054bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/SignatureBoard/batchauthorize_page/iframe__BatchAuthListFrame</value>
      <webElementGuid>5650c5fc-b78b-4338-824a-61fe7e9be9a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>acba3f11-4225-434c-9a82-d7536db8dbc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ConTractCSMDiv']/div/div/div/div/div[2]/div/div/div/div/div/div/div/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>181131d1-6ce0-4a93-a685-d4d6fdf9d1c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>ae12e901-2465-4740-b8d4-3abcd68e6be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>9e2a1d21-28d4-49d7-b7e1-4971b6509502</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
