<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_username_row2</name>
   <tag></tag>
   <elementGuidId>6462d5c6-136e-490c-8f5f-9af2fce82095</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_easyui_textbox_input6']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_easyui_textbox_input6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b5609a5a-6ecf-4f64-bb42-dc042be99ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_easyui_textbox_input6</value>
      <webElementGuid>9f352790-f673-4ca5-8fdf-fa6bf1a35049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fa945aea-524a-4166-971e-5d0cb80e0511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-text validatebox-text validatebox-invalid tooltip-f</value>
      <webElementGuid>2e4eeee9-7967-43ae-a61e-401f308823fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a4cee38e-bd4e-4f3d-8ae0-f1bd9352a769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>请输入姓名、账号、邮箱</value>
      <webElementGuid>17821517-66ab-438c-a57e-4c9bcbd5b640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_easyui_textbox_input6&quot;)</value>
      <webElementGuid>84e05f0a-5b33-4b7b-940c-ea881375457b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/SignatureBoard/batchauthorize_page/iframe__BatchAuthListFrame</value>
      <webElementGuid>afb0c923-818c-4ee6-896b-eaaf1e5b90f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_easyui_textbox_input6']</value>
      <webElementGuid>f1a6692e-eff8-48eb-95dd-9debe91aaaf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='dataGrid_datagrid-row-r1-2-1']/td[3]/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>3bb02c6d-7612-468d-b2d4-8c236999e463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>708bffca-c57e-40bc-952a-d84bd34fbf7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_easyui_textbox_input6' and @type = 'text' and @placeholder = '请输入姓名、账号、邮箱']</value>
      <webElementGuid>f524ff79-ce75-4727-93d3-628452db0be6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
