<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ck-2</name>
   <tag></tag>
   <elementGuidId>9fd94321-1d34-472c-8509-8a6e39259aa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='ck'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dataGrid_datagrid-row-r1-1-1 > td:nth-of-type(2) > div.datagrid-cell-check > input[name=&quot;ck&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>61891be2-1044-4c37-a547-4bd989dafcba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>de0927d1-58d4-4f88-8d87-8901d1f64cf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ck</value>
      <webElementGuid>202d6329-f451-4d19-b097-bfc38dbe9f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataGrid_datagrid-row-r1-1-1&quot;)/td[2]/div[@class=&quot;datagrid-cell-check&quot;]/input[1]</value>
      <webElementGuid>d0177f64-9c86-45c4-aa6a-afd1c76d263a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/SignatureBoard/batchauthorize_page/iframe__BatchAuthListFrame</value>
      <webElementGuid>65a125e2-fca7-4595-972c-609f0262e9e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='ck'])[2]</value>
      <webElementGuid>c4de6892-fe47-47c3-9bb9-d51b19176e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='dataGrid_datagrid-row-r1-1-1']/td[2]/div/input</value>
      <webElementGuid>f21565b0-33a3-41c3-af2b-32b43f9803c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div/input</value>
      <webElementGuid>e72e205c-911b-4c28-a19a-80706fcfc7dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'ck']</value>
      <webElementGuid>4c578fbd-db5e-4f41-ad4a-8908d4a5c193</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
