<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_contractlink_row2</name>
   <tag></tag>
   <elementGuidId>085e79c1-c0d3-4ce3-b66c-feec23072da8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='sample_1']/tbody/tr[2]/td[3]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td:nth-of-type(3) > div.ultrawidehide > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>95b217d7-397f-42df-8556-ae26b08c7b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Handler/FormRedirect.ashx?cmdPath=OpenForm&amp;pendingcode=120416333b2383bfd4c46bb5ecaa14</value>
      <webElementGuid>ee293cf2-2794-4c5c-bb0c-696977258d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>a575c4ed-2615-4d14-b4ba-c4e45e082082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>autotest外部磋商1701681433-1000.00-2024-11-13-Commercial</value>
      <webElementGuid>c519cf22-301e-4a60-89de-6febb54ab31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sample_1&quot;)/tbody[@class=&quot;hidden_768&quot;]/tr[2]/td[3]/div[@class=&quot;ultrawidehide&quot;]/a[1]</value>
      <webElementGuid>dfbd66ce-308f-435e-ba25-29298feb72b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/AppliedTask/iframe_concat(id(, , AppliedFram, , ))_AppliedFram</value>
      <webElementGuid>c4010ccf-06f3-4428-929b-5c265a71137e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='sample_1']/tbody/tr[2]/td[3]/div/a</value>
      <webElementGuid>ea91da5f-f6bf-4865-81e4-c8b57b411295</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'autotest外部磋商1701681433-1000.00-2024-11-13-Commercial')]</value>
      <webElementGuid>ebbd6cb8-4969-4851-938f-5f3084c413dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='处理中'])[1]/following::a[2]</value>
      <webElementGuid>1d0b1867-b9c5-4e6f-a63d-78222853c5a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='杨云玖'])[1]/following::a[3]</value>
      <webElementGuid>398a76f1-8fba-4bcd-8636-72367f803d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='合同管理流程'])[2]/preceding::a[1]</value>
      <webElementGuid>618f6637-e695-425d-991c-d44e2ef9e9b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='autotest外部磋商1701681433-1000.00-2024-11-13-Commercial']/parent::*</value>
      <webElementGuid>98403a64-b249-4c00-a0ae-1c43d56a9203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Handler/FormRedirect.ashx?cmdPath=OpenForm&amp;pendingcode=120416333b2383bfd4c46bb5ecaa14')]</value>
      <webElementGuid>f8f7b177-7714-4b87-b875-869c6afc1dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/a</value>
      <webElementGuid>fcee444a-0b08-4789-8737-a4fd6434ded8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Handler/FormRedirect.ashx?cmdPath=OpenForm&amp;pendingcode=120416333b2383bfd4c46bb5ecaa14' and (text() = 'autotest外部磋商1701681433-1000.00-2024-11-13-Commercial' or . = 'autotest外部磋商1701681433-1000.00-2024-11-13-Commercial')]</value>
      <webElementGuid>deb1781a-98bf-47ce-a8da-a556c6840a8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
