<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_contractlink_row1</name>
   <tag></tag>
   <elementGuidId>dba556ea-2f79-49a9-b917-d5830e2385d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='sample_1']/tbody/tr/td[3]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ultrawidehide > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6852fe87-4faf-4ea4-aead-bf86fcf6e4f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>Handler/FormRedirect.ashx?cmdPath=OpenForm&amp;pendingcode=12041602536de9bdc76e8357eb25d1</value>
      <webElementGuid>11259014-921f-417a-a6e0-028b21841239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
      <webElementGuid>2674548a-7c40-419a-a064-c4762250d97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>autotest外部磋商1701681433-2500.00-2024-11-13-Commercial</value>
      <webElementGuid>d7373b87-e00a-4310-9e2b-f78ed7b79987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sample_1&quot;)/tbody[@class=&quot;hidden_768&quot;]/tr[1]/td[3]/div[@class=&quot;ultrawidehide&quot;]/a[1]</value>
      <webElementGuid>9d9b2e6b-2dbf-486c-9ef3-2ee6760497f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/AppliedTask/iframe_concat(id(, , AppliedFram, , ))_AppliedFram</value>
      <webElementGuid>f90a4c99-910d-41c0-8cd2-b91bbbf7294d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='sample_1']/tbody/tr/td[3]/div/a</value>
      <webElementGuid>8b31ba90-8c0c-4ada-9367-49d09cf4364f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'autotest外部磋商1701681433-2500.00-2024-11-13-Commercial')]</value>
      <webElementGuid>dfa58f8e-9b7c-4c4b-80b1-c618d404239c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='我的已申请'])[3]/following::a[2]</value>
      <webElementGuid>48eba7dc-1265-44ed-be48-2bb99ab51775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='流程名称'])[2]/following::a[2]</value>
      <webElementGuid>3b907dc1-7be0-4e9c-9993-fb2458976b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='合同管理流程'])[1]/preceding::a[1]</value>
      <webElementGuid>184626cf-5cf3-4ae3-bf3f-e092bb4ea58a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='autotest外部磋商1701681433-2500.00-2024-11-13-Commercial']/parent::*</value>
      <webElementGuid>3de2d3c7-da58-41ec-98f0-dd6f6dc86045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'Handler/FormRedirect.ashx?cmdPath=OpenForm&amp;pendingcode=12041602536de9bdc76e8357eb25d1')]</value>
      <webElementGuid>2eb65b1b-c893-4e60-a65d-45b1bfa18800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>f2ed564a-ef84-4d8c-a75e-7beb86fee25f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'Handler/FormRedirect.ashx?cmdPath=OpenForm&amp;pendingcode=12041602536de9bdc76e8357eb25d1' and (text() = 'autotest外部磋商1701681433-2500.00-2024-11-13-Commercial' or . = 'autotest外部磋商1701681433-2500.00-2024-11-13-Commercial')]</value>
      <webElementGuid>5e8d8487-9903-403f-b45a-6b09c3f8ab73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
