<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , AppliedFram, , ))_AppliedFram</name>
   <tag></tag>
   <elementGuidId>5f7e91a7-9c49-4853-a267-65215a96ce98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='AppliedFram']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AppliedFram</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>4c0c416d-a8ab-492e-b480-f6e3c61cd073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AppliedFram</value>
      <webElementGuid>2b3452bd-537b-460b-8a0f-fac29422d5cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AppliedFram</value>
      <webElementGuid>a0332868-2f52-492c-a679-ec382e5a8284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>b20e142e-834a-46b0-85b8-8f6a17da561b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/CTP/ProcessCenter/HaveAppliedPrc.aspx</value>
      <webElementGuid>b43044cd-0ac0-49f9-983f-20579d0f0e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AppliedFram&quot;)</value>
      <webElementGuid>f97de27d-415b-459c-8410-fb33b5384b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/AppliedTask/iframe__ifm</value>
      <webElementGuid>46ae0237-3d59-4df6-a859-198f07180e6c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='AppliedFram']</value>
      <webElementGuid>7ff906cf-9ed6-436d-904c-1427ce7484bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>2d2e2ae2-d2c7-40a0-a6bd-9ef8e439246c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'AppliedFram' and @name = 'AppliedFram' and @src = '/CTP/ProcessCenter/HaveAppliedPrc.aspx']</value>
      <webElementGuid>851aa3d6-059e-4af3-acf7-ed970bc96135</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
