<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_contractapplycontent_link_1</name>
   <tag></tag>
   <elementGuidId>5435875f-bb5e-413a-8f3a-8e0c75a1373b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='sample_1']/tbody/tr/td[4]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ultrawidehide > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>451c0bd2-cda7-4afd-80b2-e450f26a1005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>4626771d-7123-41bf-a514-1e6991026284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>autotest外部磋商1701832232-1000.00-2024/11/13-Commercial</value>
      <webElementGuid>83cbf930-b58b-4376-a7c8-d5a0582a1b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sample_1&quot;)/tbody[@class=&quot;hidden_768&quot;]/tr[1]/td[4]/div[@class=&quot;ultrawidehide&quot;]/a[1]</value>
      <webElementGuid>aa41d47a-d430-4d5b-8d00-ce1536105267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/NeedToDoTask/iframe_concat(id(, , TaskListFram, , ))_TaskListFram</value>
      <webElementGuid>32972c08-8621-42d0-ae42-1a0c5781b476</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='sample_1']/tbody/tr/td[4]/div/a</value>
      <webElementGuid>d3cebb40-8d6b-4b6e-8ade-508cae59e393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'autotest外部磋商1701832232-1000.00-2024/11/13-Commercial')]</value>
      <webElementGuid>6aa53021-e99a-4740-bf19-962a29aa9780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='我的待办'])[2]/following::a[2]</value>
      <webElementGuid>bbaf0ab7-3cb1-476b-a352-01b411610f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='流程名称'])[2]/following::a[2]</value>
      <webElementGuid>4acb9856-52b6-4218-9111-6014957feca7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='合同管理流程'])[1]/preceding::a[1]</value>
      <webElementGuid>03e86b7c-f330-4574-91b8-e79385e4bf95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='autotest外部磋商1701832232-1000.00-2024/11/13-Commercial']/parent::*</value>
      <webElementGuid>c7f6f85c-10bb-4025-ba21-5e40b6092edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:;')]</value>
      <webElementGuid>b8ad4709-c496-4482-8f41-789a76657962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>0b4b0965-1e2a-46c2-8735-829f39b81912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'autotest外部磋商1701832232-1000.00-2024/11/13-Commercial' or . = 'autotest外部磋商1701832232-1000.00-2024/11/13-Commercial')]</value>
      <webElementGuid>f0216e9c-13ef-4bbf-bf28-df5643bad836</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
