<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_onebatchcontractdg-1</name>
   <tag></tag>
   <elementGuidId>2fc71972-a82e-4671-875d-30d253190580</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.easyui-linkbutton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='合同定稿']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38f9c53f-b9ea-46d4-b712-23a2d399f497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>641f5bfa-088e-4aa6-8f8b-f5e07585bd9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>合同定稿</value>
      <webElementGuid>5dd5ce83-080e-4bbf-8c90-d2279b8dda4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AppoverContractDG('P-720a6f-5aa2-4d7c-adee-1cf532bcb4e4','2')</value>
      <webElementGuid>f7759e8f-8f99-4958-949d-a02ea3004937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>easyui-linkbutton</value>
      <webElementGuid>fb8325cf-c99d-4205-8b6e-cf51aa60cbad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>iconcls</name>
      <type>Main</type>
      <value>glyphicon glyphicon-refresh</value>
      <webElementGuid>7106e04c-b73e-4052-b8ba-60e4e66da3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;model&quot;)/tbody[@class=&quot;hidden_768&quot;]/tr[1]/td[8]/input[@class=&quot;easyui-linkbutton&quot;]</value>
      <webElementGuid>5195245d-b45f-41f8-82f8-359c229126b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/NeedToDoTask/iframe</value>
      <webElementGuid>195cad8c-cabe-409c-9fb7-67506c3d963f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='合同定稿']</value>
      <webElementGuid>dcf26e36-2b93-4703-acc3-6d514455ca47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='model']/tbody/tr/td[8]/input</value>
      <webElementGuid>ac176215-6168-446a-90bd-f3a72c3bd095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/input</value>
      <webElementGuid>5851b81b-ce0e-4714-b971-b184d8a3f06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>a96c5f7e-3d22-4463-8a6b-663bafe1904e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
