<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_vendorconsultdone-2</name>
   <tag></tag>
   <elementGuidId>fb243061-4217-4b0d-957a-365bbcc8842b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.easyui-linkbutton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='磋商完成处理'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e1020f6-6a3f-4595-9bc5-ab8bb50c13bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f04ad365-943e-439b-96c5-5b7e27285a4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>磋商完成处理</value>
      <webElementGuid>d9b9b3c8-3658-46d9-a8b8-6a6e8eb54677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AppoverContractQS('P-e68c9c-f29c-4196-97a5-522fb3f39f9d','2')</value>
      <webElementGuid>39659f8c-4957-4892-92bb-e860e7d8aff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>easyui-linkbutton</value>
      <webElementGuid>588b9a37-29ef-4890-bed1-9aea329c963c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>iconcls</name>
      <type>Main</type>
      <value>glyphicon glyphicon-refresh</value>
      <webElementGuid>8ea6e00c-f85a-46de-8e9a-632de0c68fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;model&quot;)/tbody[@class=&quot;hidden_768&quot;]/tr[1]/td[8]/input[@class=&quot;easyui-linkbutton&quot;]</value>
      <webElementGuid>b1f08e98-95ca-4284-9aff-6671d7069259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/NeedToDoTask/iframe</value>
      <webElementGuid>5c34f38b-e2fb-42e1-aea5-5b745dc2f133</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='磋商完成处理'])[2]</value>
      <webElementGuid>f18ad8c5-9167-4858-829c-65ec3a495532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//table[@id='model']/tbody/tr/td[8]/input)[2]</value>
      <webElementGuid>e2a4b73e-3df4-47e5-b9d8-5c0a253a2012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>(//td[8]/input)[2]</value>
      <webElementGuid>ee691689-4739-4942-b4b1-82669a9bbe1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>(//input[@type = 'button'])[2]</value>
      <webElementGuid>6713dd0b-5c7d-4866-8221-6fc06352e69c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
