<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_signapprovercheck</name>
   <tag></tag>
   <elementGuidId>4ba6b470-166b-44fe-8c73-c202ce92ace5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qssp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='qssp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a4258987-4a60-4ead-8985-36c73be6146a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qssp</value>
      <webElementGuid>7074bcc7-6582-4511-81a7-2b5b8bf7ef57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>newDataTable('签署审批人审核')</value>
      <webElementGuid>2fd3ff62-8348-45d3-9cc5-dfbb6118ed1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 签署审批人审核</value>
      <webElementGuid>76e056aa-bdc1-4c4d-9cb8-61f6be1cac1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qssp&quot;)</value>
      <webElementGuid>17dc1a20-a94e-4638-b830-aad3b1043c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/NeedToDoTask/iframe_concat(id(, , TaskListFram, , ))_TaskListFram</value>
      <webElementGuid>1dc967e7-7d66-4dce-a19b-f99e8f74008e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='qssp']</value>
      <webElementGuid>e7f1cf0d-8cf1-4435-9924-1fdb5e7bff6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/p[2]</value>
      <webElementGuid>b2060d86-789e-4d32-8369-45ac615924cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='正在获取数据，请稍后...'])[1]/following::p[2]</value>
      <webElementGuid>d83f9ae2-2669-474b-8ec2-4b9d45285629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='⇒'])[1]/following::p[2]</value>
      <webElementGuid>680e57eb-d420-48d4-a507-6b6d3cfdd403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'qssp', '&quot;', ')')])[1]/preceding::p[4]</value>
      <webElementGuid>53d9414a-bdd0-404e-9308-da5f6416456a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>1cc1df56-923a-48a5-ac13-66299c93badf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'qssp' and (text() = ' 签署审批人审核' or . = ' 签署审批人审核')]</value>
      <webElementGuid>62d36361-8884-4b1e-8c9c-043ce8777750</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
