<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_morebatchapprove</name>
   <tag></tag>
   <elementGuidId>08066e9f-a775-45f6-a6cc-a1de85f34df5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#belowBut > input.easyui-linkbutton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='多批次批量审批']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e115c67e-3b76-4f0f-b883-757f3832ea63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3fd1f613-d3f9-4ccd-8e96-8f99f1536db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>多批次批量审批</value>
      <webElementGuid>fff03240-7df5-47a6-bc83-5210d6c4ef92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>easyui-linkbutton</value>
      <webElementGuid>2183d4e4-6b65-45a5-b4a8-34c34f2370fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>iconcls</name>
      <type>Main</type>
      <value>glyphicon glyphicon-refresh</value>
      <webElementGuid>a14aeda3-6e1f-4190-a8cc-fb565e2b7728</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AppoverContractQSS()</value>
      <webElementGuid>2e3b83cf-b53c-4752-ab55-2a88da364d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;belowBut&quot;)/input[@class=&quot;easyui-linkbutton&quot;]</value>
      <webElementGuid>79256451-a218-48c7-a798-c2f0faa49f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/NeedToDoTask/iframe</value>
      <webElementGuid>c4a86a3e-9716-4d23-b4ca-033ce6f2613f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='多批次批量审批']</value>
      <webElementGuid>1d239722-bd71-46a2-b94a-6f7164819d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='belowBut']/input</value>
      <webElementGuid>31e40fa4-c859-4df7-9cd5-002fb83b679c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>de9771ad-6ee0-40eb-90a2-39bd447fb412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>be510ea7-6ecc-416f-969c-be2475872877</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
