<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_batchvendorconsultdone</name>
   <tag></tag>
   <elementGuidId>355324f3-f29a-4f82-9844-6a08563d7d96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='wbcswccl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wbcswccl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>3132b104-920e-409c-af1d-ffc4a4e65d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wbcswccl</value>
      <webElementGuid>17f47d48-413f-45f1-8291-31e0313f1375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>newDataTable('外部磋商完成处理')</value>
      <webElementGuid>87c384ba-ebd4-4141-a090-4d251128675a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 外部磋商完成处理</value>
      <webElementGuid>1eb56f56-a6ab-4c0d-9703-6d8f19eff298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wbcswccl&quot;)</value>
      <webElementGuid>e76371f7-f84b-40d2-8953-45a9f965a0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/NeedToDoTask/iframe_concat(id(, , TaskListFram, , ))_TaskListFram</value>
      <webElementGuid>6254b7cc-4d4e-4a76-821e-2fe3ebd8888b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='wbcswccl']</value>
      <webElementGuid>3cab0c71-f5fc-4f55-babf-11d9d5181567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/p[5]</value>
      <webElementGuid>bcf7e27b-3600-4aee-bfac-9d52ed7fc2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='正在获取数据，请稍后...'])[1]/following::p[5]</value>
      <webElementGuid>47efbede-3fbf-41d7-bf9f-2ab9f7b2fc0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='⇒'])[1]/following::p[5]</value>
      <webElementGuid>7d97b0cf-2eed-4711-a770-f8bada6d9c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'wbcswccl', '&quot;', ')')])[1]/preceding::p[1]</value>
      <webElementGuid>711dbfe7-1d81-4911-b0da-e608b65c6019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]</value>
      <webElementGuid>81b05202-845c-46d7-916d-fe277825e03c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'wbcswccl' and (text() = ' 外部磋商完成处理' or . = ' 外部磋商完成处理')]</value>
      <webElementGuid>36327a4b-9b44-4cb5-ba25-6a4b76197303</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
