<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_approvecontract-1</name>
   <tag></tag>
   <elementGuidId>404aa15f-0515-4fca-a26f-96f975c77876</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.easyui-linkbutton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='合同审批']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ae406b04-c09c-470a-aaf0-7fb5e4fffc39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>35a37e50-c860-4d6b-bb37-b5a6cfede407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>合同审批</value>
      <webElementGuid>7cfaf477-0e8a-4bbd-b2c6-17789441d6f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AppoverContractQS('P-daf676-1516-4571-9500-d3c9f9544532','2')</value>
      <webElementGuid>a42b205f-2fe6-4ba8-84a6-a747ff712768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>easyui-linkbutton</value>
      <webElementGuid>0453ccea-b78b-4847-afa0-1f70777676e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>iconcls</name>
      <type>Main</type>
      <value>glyphicon glyphicon-refresh</value>
      <webElementGuid>83d141e6-73ee-4e5b-b0d8-1a3c5f6967d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;model&quot;)/tbody[@class=&quot;hidden_768&quot;]/tr[1]/td[8]/input[@class=&quot;easyui-linkbutton&quot;]</value>
      <webElementGuid>fcea37e4-1f22-4cc3-aee6-20ec7ba11962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/NeedToDoTask/iframe</value>
      <webElementGuid>02cce5c5-4035-45bd-a085-92252874c10f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='合同审批']</value>
      <webElementGuid>bf8f1e49-3374-4b60-be61-db25d51713e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='model']/tbody/tr/td[8]/input</value>
      <webElementGuid>def2a8b4-b154-4ae3-9592-06ed225e949a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/input</value>
      <webElementGuid>feb14f37-bd34-4132-b6c0-5ae35d11ee70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>a6ec3744-e53b-42f6-8a3d-00c1e0721143</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
