<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_contractdraft-2</name>
   <tag></tag>
   <elementGuidId>73f657bf-c3e8-4037-9c28-dc61cc3f8668</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.easyui-linkbutton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@value='合同起草'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4dfe30a-68a9-43f9-8206-2b2c2bdd7ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dd787608-12cd-459b-800f-d46e5be0b025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>合同起草</value>
      <webElementGuid>976ffc28-6d38-4246-a66b-a3ee7fffb013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AppoverContractQS('P-d1a4f5-6133-47b6-818b-40f734f82227','2')</value>
      <webElementGuid>23974e78-574c-4f0f-95fa-bbc55183a66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>easyui-linkbutton</value>
      <webElementGuid>ccb3fc81-552f-4488-acdf-f3da35d7d1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>iconcls</name>
      <type>Main</type>
      <value>glyphicon glyphicon-refresh</value>
      <webElementGuid>f65df80b-dcb0-4145-a536-a3f4b3ca7aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;model&quot;)/tbody[@class=&quot;hidden_768&quot;]/tr[1]/td[8]/input[@class=&quot;easyui-linkbutton&quot;]</value>
      <webElementGuid>faa88a80-d277-4ae7-bd51-bc4f285e650c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/NeedToDoTask/iframe</value>
      <webElementGuid>4de081bf-d09d-4eb7-bbdf-f9aefa10aca5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@value='合同起草'])[2]</value>
      <webElementGuid>74f86ceb-0f72-4757-8adf-a975e8fb91dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//table[@id='model']/tbody/tr/td[8]/input)[2]</value>
      <webElementGuid>4348f0c1-f0b8-4a29-9f12-3cd379f26bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>(//td[8]/input)[2]</value>
      <webElementGuid>b926d9a2-67fe-4a94-b022-e608a2e3fcf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>(//input[@type = 'button'])[2]</value>
      <webElementGuid>b6e32c57-1200-481b-98bf-cca7c57203b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
