<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_contractdg</name>
   <tag></tag>
   <elementGuidId>4edeb66d-de49-4ef2-84fd-6c0adfbcfc75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#htdg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='htdg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>64a3bd23-2682-4d61-84bd-23e3a1065093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>htdg</value>
      <webElementGuid>8cababdf-3390-4c8e-b3d8-df6c0cd66105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>newDataTable('合同定稿')</value>
      <webElementGuid>93238a6c-a1b0-4c7c-9b6a-add2851e8eef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 合同定稿</value>
      <webElementGuid>3b2dae92-2703-497e-9442-927bbbd5d431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;htdg&quot;)</value>
      <webElementGuid>2d406626-862c-4091-bddf-33be6a9aef75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/NeedToDoTask/iframe_concat(id(, , TaskListFram, , ))_TaskListFram</value>
      <webElementGuid>abfc6379-d364-4ead-a11d-41eeb56b78b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='htdg']</value>
      <webElementGuid>8ced47dc-dcc8-4c8e-8593-b1e2490d94fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='menu']/p</value>
      <webElementGuid>ed5494f6-88d6-41f8-9816-b508c2a86cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='正在获取数据，请稍后...'])[1]/following::p[1]</value>
      <webElementGuid>000bb923-c197-4f44-8a4a-974491146443</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='⇒'])[1]/following::p[1]</value>
      <webElementGuid>a2d87e35-ffa5-4cb5-850f-4f14bc12b530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'htdg', '&quot;', ')')])[1]/preceding::p[5]</value>
      <webElementGuid>c9a6f951-a234-4034-8334-77c2f47b20d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>def0478b-4975-4f68-84c7-58cd4d5d3dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'htdg' and (text() = ' 合同定稿' or . = ' 合同定稿')]</value>
      <webElementGuid>44716a33-cc90-40fc-9e53-31e98b727d96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
