<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_vendorconsultdone-1</name>
   <tag></tag>
   <elementGuidId>2f82109b-688b-433a-a64c-d29f565c0746</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.easyui-linkbutton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='磋商完成处理']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>237acbce-da02-4a37-9132-a23b692ff3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ed1df72e-5a92-4071-a04e-0b1375b914dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>磋商完成处理</value>
      <webElementGuid>680b797a-72f5-4487-b873-5b14f5435d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AppoverContractQS('P-720a6f-5aa2-4d7c-adee-1cf532bcb4e4','2')</value>
      <webElementGuid>bb5cab19-e7ba-4120-a8f3-cfbd376c30c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>easyui-linkbutton</value>
      <webElementGuid>7797e8de-4ffd-480f-bcf6-39d27fe5d18d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>iconcls</name>
      <type>Main</type>
      <value>glyphicon glyphicon-refresh</value>
      <webElementGuid>586bbf5b-293d-4ea7-9113-11aa718aad08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;model&quot;)/tbody[@class=&quot;hidden_768&quot;]/tr[1]/td[8]/input[@class=&quot;easyui-linkbutton&quot;]</value>
      <webElementGuid>92ea32df-7832-4df0-9e4c-0bf66e74fec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/NeedToDoTask/iframe</value>
      <webElementGuid>8fb35698-9990-4e6a-a9d8-f0d9681cbb02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='磋商完成处理']</value>
      <webElementGuid>6aabd287-de4e-418d-834c-63963b27dfa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='model']/tbody/tr/td[8]/input</value>
      <webElementGuid>c9bc30ea-e330-4a8b-9d8e-e4220ba5c33f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/input</value>
      <webElementGuid>1bf45cac-b043-496a-9e52-7600cc3dfe4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button']</value>
      <webElementGuid>378934ec-521f-4cb6-9758-64827fc3d304</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
