<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__ifm</name>
   <tag></tag>
   <elementGuidId>39fe4435-6526-4ade-a60a-9e5b80fb3d04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ifm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>1d07be4b-fe01-4709-aea6-34737dda4965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifm</value>
      <webElementGuid>94aa8095-495c-441c-aa69-9554bf894a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d73b5157-1792-47a3-ae56-d1f231842f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>9275fc4b-7df7-4e7d-bece-4272405c6f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ifm</value>
      <webElementGuid>75bb0c87-51c7-4bf9-b137-6aa69340ee3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DASContract/Process/Page/ContractTaskList.cshtml?mainTone=Index&amp;strUserUltCode=BPM/28077170&amp;CurrentLanguage=zh-CN&amp;rnd=0.2179900284998022</value>
      <webElementGuid>d757e410-0aac-47c3-b24b-85288c72f0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-header-fixed&quot;]/div[@class=&quot;page-container row-fluid&quot;]/div[@class=&quot;divContent&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;ifmBg&quot;]/div[@class=&quot;col-md-12&quot;]/iframe[@id=&quot;ifm&quot;]</value>
      <webElementGuid>4edd5811-9962-4a45-b8ac-434ec42a9ad4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifm']</value>
      <webElementGuid>5ecccfb3-0513-4542-adda-fd5995b5a144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>65a06ab2-3c50-4979-9e4a-ea9531c1a7d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ifm' and @name = 'ifm' and @src = '/DASContract/Process/Page/ContractTaskList.cshtml?mainTone=Index&amp;strUserUltCode=BPM/28077170&amp;CurrentLanguage=zh-CN&amp;rnd=0.2179900284998022']</value>
      <webElementGuid>4c13a2d8-ed2a-4450-8a50-bf43763f2803</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
