<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , TaskListFram, , ))_TaskListFram</name>
   <tag></tag>
   <elementGuidId>6fef5766-7d71-4405-a5a2-a801df80b60a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TaskListFram</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='TaskListFram']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>38cf74c8-e325-4ab2-8d05-da57f562c096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TaskListFram</value>
      <webElementGuid>7dd46690-2167-4dca-b27e-1f8d3172bb2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TaskListFram</value>
      <webElementGuid>e91c5a2d-7d6a-4bfc-a9b1-5977154158b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>25c89d1e-8645-4611-8909-731f5eca2a58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/CTP/ProcessCenter/TaskList.aspx</value>
      <webElementGuid>2bd0667b-6c32-4875-87d2-f9c305b7d16d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TaskListFram&quot;)</value>
      <webElementGuid>a6a8d391-18f4-4eb1-9207-de8dc0551680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/NeedToDoTask/iframe__ifm</value>
      <webElementGuid>d2c4a3e6-eb8c-4a07-8a58-cd9f59de1660</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='TaskListFram']</value>
      <webElementGuid>252368ce-3e09-4324-86c6-a84d9e424947</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>886c6fb9-6864-4916-b24f-3587c47035ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'TaskListFram' and @name = 'TaskListFram' and @src = '/CTP/ProcessCenter/TaskList.aspx']</value>
      <webElementGuid>60978bca-f15a-4a02-9d94-5957677e9ef3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
