<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__chk-2</name>
   <tag></tag>
   <elementGuidId>6aaeaa38-ba8d-464b-828c-2f1d16cc2417</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.chk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//table[@id='model']/tbody/tr/td[2]/input)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9baed935-c912-48aa-8609-08f02b57eee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>174b02cc-34ee-46e2-bd9a-52ee040fc1f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>f55b8e97-a684-453a-9cd9-b54da3d5e7ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P-daf676-1516-4571-9500-d3c9f9544532</value>
      <webElementGuid>baf50c22-dd2f-4395-85fd-c94f00dcf396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;model&quot;)/tbody[@class=&quot;hidden_768&quot;]/tr[1]/td[@class=&quot;chkBox&quot;]/input[@class=&quot;chk&quot;]</value>
      <webElementGuid>d2bbb0f6-856b-466e-90dd-816480cf4058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/NeedToDoTask/iframe</value>
      <webElementGuid>15c35d05-19af-4526-84be-808d55380654</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='P-c82313-f368-477b-b00d-5536d801f847']</value>
      <webElementGuid>c1f5ca5e-b68f-4de8-b6df-9a3d312f3147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//table[@id='model']/tbody/tr/td[2]/input)[2]</value>
      <webElementGuid>35d0a878-29e5-48c7-8255-45321969d258</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
