<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>table_approvelist</name>
   <tag></tag>
   <elementGuidId>3b65b954-8ef5-42d3-b8d0-7b64d0240860</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tbContainer.container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;model&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0529c24c-a058-4012-9dd5-41a18a0e89a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tbContainer container</value>
      <webElementGuid>318bfe66-0556-4841-aa21-1d9b4c42def3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>达创科技表格数据申请人发起时间批量发起摘要批量发起数量待办数量操作申请人发起时间批量发起摘要批量发起数量待办数量操作达创科技表格数据1杨云玖【wells.wang1@budweiserapac.com】11/27/2023 2:26:33 PMautotest_add_批量测试222丰淑花【1@qq.com】6/8/2023 5:11:19 PM书签验证4-cxr;xsx5.31-prime4;xsx6.1-prime;xsx6.8-币种651申请人杨云玖【wells.wang1@budweiserapac.com】发起时间11/27/2023 2:26:33 PM批量发起摘要autotest_add_批量测试批量发起数量2待办数量2操作2申请人丰淑花【1@qq.com】发起时间6/8/2023 5:11:19 PM批量发起摘要书签验证4-cxr;xsx5.31-prime4;xsx6.1-prime;xsx6.8-币种批量发起数量6待办数量5操作⇐&lt;12345>⇒正在获取数据，请稍后...</value>
      <webElementGuid>87622a8d-422e-4d49-ac0b-678816fe7875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list&quot;)/div[@class=&quot;tbContainer container&quot;]</value>
      <webElementGuid>bc056892-a9bb-4b71-aed3-f9ba01d1aaba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/NeedToDoTask/iframe</value>
      <webElementGuid>300f6046-2a7a-47dc-a5e2-ad603df09abe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//*[@id=&quot;model&quot;]</value>
      <webElementGuid>063bfff9-8f9c-42d8-952b-71f548eea767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>/html/body/div/div[1]/div/div[2]/div/div[1]/table</value>
      <webElementGuid>767cc603-716b-4d0f-8433-73f480867019</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
