<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_autotest_add_</name>
   <tag></tag>
   <elementGuidId>a5ab886a-d019-4663-8e2f-5e7d43a5cbe3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(5)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='model']/tbody/tr/td[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0eee0666-57fe-44e6-9210-b3820c3e56b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>autotest_add_批量测试</value>
      <webElementGuid>15c91556-9fb2-48ef-8f4f-195f547fb6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;model&quot;)/tbody[@class=&quot;hidden_768&quot;]/tr[1]/td[5]</value>
      <webElementGuid>f2467298-bb03-422f-8b72-72d7aa2c17f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/NeedToDoTask/iframe</value>
      <webElementGuid>828d4abc-4b15-4f58-890c-ec722e2aa975</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='model']/tbody/tr/td[5]</value>
      <webElementGuid>3ffd3ef4-e8f8-4f9a-8bd2-867f81592e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='杨云玖【wells.wang1@budweiserapac.com】'])[1]/following::td[2]</value>
      <webElementGuid>c8075267-0234-4b33-89f1-ccebf68426f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='达创科技表格数据'])[2]/following::td[5]</value>
      <webElementGuid>b24e9ced-df34-4324-b4a1-2fa13e38a996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='丰淑花【1@qq.com】'])[1]/preceding::td[6]</value>
      <webElementGuid>d4ac3d3f-8bb2-4da5-b9a4-7e8001e9f105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='书签验证4-cxr;xsx5.31-prime4;xsx6.1-prime;xsx6.8-币种'])[1]/preceding::td[8]</value>
      <webElementGuid>6b51ab25-4a24-449d-842d-2430802039d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='autotest_add_批量测试']/parent::*</value>
      <webElementGuid>95ba6ed0-7732-4f75-b9be-f648bb5e755f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]</value>
      <webElementGuid>bf169b7b-bf52-4c88-90ec-013948e3ca2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'autotest_add_批量测试' or . = 'autotest_add_批量测试')]</value>
      <webElementGuid>0f632cfb-f9e3-424c-8e81-1b480d767bf2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
