<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__ifm_1</name>
   <tag></tag>
   <elementGuidId>5fc01b36-0b74-48bf-b0c4-afcce3de8757</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>62e6419a-34e8-4051-9e08-2678ebea7261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>67eaf158-11fa-4c21-9014-bf1e824529a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>f4097478-d106-45d3-8dfe-7840106d13c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>06a3170a-c920-431a-8d74-02962f7c72a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DASPortal/OrgCommonChoose/Page/OrgCommonChoose.aspx?chooseValCarID=3c77c011-7a6a-4839-95ec-c5c5e72ceb2a&amp;notChooseValCarID=c69a32c9-685d-492f-8bc8-201acb50237d&amp;mcwId=8b46b9cc-107e-4dfa-be68-ca5710861efa&amp;mcmwId=8de441ea-0061-4f97-99d2-73014b107307&amp;pageType=dpttreeuser&amp;chkTabsNum=0&amp;isCascadeUser=false&amp;isCascadeDpt=false&amp;isCascadeJob=false&amp;isPath=false&amp;isGrpName=false</value>
      <webElementGuid>f1ee8a8b-0a75-4de8-bc60-1c0ecff4fd17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;panel-fit&quot;]/body[@class=&quot;panel-noscroll modal-open&quot;]/div[@class=&quot;modal fade DachkjModel in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body form-horizontal&quot;]/iframe[1]</value>
      <webElementGuid>e0b6fa98-91c5-4c43-99fa-710f4f913976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/ContractTransfer_page/iframe__ifm</value>
      <webElementGuid>97b83bd6-d154-4786-946a-475a82580d55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>3d57ea2e-989b-48cd-8f8a-f69a74522d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/DASPortal/OrgCommonChoose/Page/OrgCommonChoose.aspx?chooseValCarID=3c77c011-7a6a-4839-95ec-c5c5e72ceb2a&amp;notChooseValCarID=c69a32c9-685d-492f-8bc8-201acb50237d&amp;mcwId=8b46b9cc-107e-4dfa-be68-ca5710861efa&amp;mcmwId=8de441ea-0061-4f97-99d2-73014b107307&amp;pageType=dpttreeuser&amp;chkTabsNum=0&amp;isCascadeUser=false&amp;isCascadeDpt=false&amp;isCascadeJob=false&amp;isPath=false&amp;isGrpName=false']</value>
      <webElementGuid>b35dfb8c-9df0-4a5e-9748-436055e0f4cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
