<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__ifm_1_1</name>
   <tag></tag>
   <elementGuidId>5c287ff3-e08d-439e-9f63-b07669aef6a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ifm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>62ed5893-1440-49bc-9a0d-c4247d08058e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifm</value>
      <webElementGuid>a25a4a35-d0bc-41e2-98b6-da0a68a823f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ifm</value>
      <webElementGuid>71f88428-7a31-48f4-bb9d-7885713af82b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Datadetail.cshtml?type=transfer&amp;model=contract&amp;cid=28070907&amp;dagcid=3d03b8c7-90cb-4590-9f89-752aa0e75efa</value>
      <webElementGuid>e5609992-18ea-4f88-af57-6690c33046c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>adec17c1-4c50-4e3d-80f4-812bb13cb33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f9d2ea73-c263-4bab-9259-34298d273251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ifm&quot;)</value>
      <webElementGuid>bccc23eb-cb20-400a-bd87-fb94e7b386dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/ContractTransfer_page/iframe__ifm_1</value>
      <webElementGuid>6ccb21ec-6f85-4acb-b309-e5c463d13658</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifm']</value>
      <webElementGuid>34e7a028-b0d3-4cf0-a641-714453563e0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>5aa8d8f1-a250-4b45-b73b-c8991fe3cdd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ifm' and @name = 'ifm' and @src = 'Datadetail.cshtml?type=transfer&amp;model=contract&amp;cid=28070907&amp;dagcid=3d03b8c7-90cb-4590-9f89-752aa0e75efa']</value>
      <webElementGuid>0129e4bc-56b0-4556-818b-dd44d8be2e38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
