<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_contracttransfer_user_search</name>
   <tag></tag>
   <elementGuidId>873497fb-a1c5-414a-993f-6f5d0f9beed4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control.selech</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a572841-318a-430a-94e1-407be8563ada</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ce4e0f1d-88c9-4f57-83b9-3279a62dff5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control selech</value>
      <webElementGuid>78ba4db0-51a1-4338-ac07-49d86aaad9c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>登录名,用户名称,邮箱,部门名称,职务名称</value>
      <webElementGuid>d839e42b-3965-4cbe-a7e3-dfa45fec6dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divGridBox&quot;)/div[@class=&quot;tbContainer container&quot;]/div[@class=&quot;tbBeforeBox row&quot;]/div[@class=&quot;input-group pull-right group searchBox input-group-sm&quot;]/input[@class=&quot;form-control selech&quot;]</value>
      <webElementGuid>8bb366ae-23f2-4c6b-ada4-292fcf9db272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/ContractTransfer_page/iframe__ifm_1_1</value>
      <webElementGuid>cf13882b-21ae-4b20-a035-b40e8711b372</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divGridBox']/div/div/div[2]/input</value>
      <webElementGuid>baa18b97-4131-4971-85e8-6ee951ab450e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>896a8bd2-e9a2-4476-98a0-4202d1028962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = '登录名,用户名称,邮箱,部门名称,职务名称']</value>
      <webElementGuid>392dc5cc-5ffa-40de-8135-c8471877f6c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
