<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_contracttransfer_user_chk</name>
   <tag></tag>
   <elementGuidId>39204cf6-43b7-4d70-b982-c600c76722e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.chk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tbGrid']/tbody/tr/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70ea492a-18ea-4cf5-9538-a08a6f583680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ccdfc3fb-eada-4cc4-bb56-6baadb779457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>b3eddafe-8792-4ac2-a8cf-ab642893136d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>23198599-5937-48d2-a1bb-ca72ff0a3a73</value>
      <webElementGuid>e768435a-860b-40dc-9ee6-36ff19ea3516</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbGrid&quot;)/tbody[@class=&quot;hidden_768&quot;]/tr[1]/td[@class=&quot;chkBox&quot;]/input[@class=&quot;chk&quot;]</value>
      <webElementGuid>9ab81241-8417-47d6-8ff6-7401466e2e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/ContractTransfer_page/iframe__ifm_1_1</value>
      <webElementGuid>7763328e-8ad7-4c48-a05d-cc56789ebad3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='23198599-5937-48d2-a1bb-ca72ff0a3a73']</value>
      <webElementGuid>fb779838-4d70-41f1-9d00-a65c93480495</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbGrid']/tbody/tr/td[2]/input</value>
      <webElementGuid>2ee3ea36-0655-45e6-bf43-2d3fe03d61a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>2242e925-48d1-4182-9fe0-f16af6d92ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>783c5c79-47d3-4f90-b605-75b87e437cf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
