<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_contract_autotest1</name>
   <tag></tag>
   <elementGuidId>a5fd2b56-c621-46a8-916f-a977edec7ec4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'autotest1条签署中')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.datagridhref</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f4064c0-543a-47dd-8f02-c6e84eace8d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>cd128720-784c-4a2f-89e0-d31fbc3b8180</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datagridhref</value>
      <webElementGuid>220739e8-b3eb-4e83-beca-538133e6f44a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>showContractView('856b1f83-4699-4eee-9f9c-b0c10100acbb','1','合同签署流程','签订')</value>
      <webElementGuid>264855a2-6564-4bb7-9f32-638c4b05ed78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>autotest1条签署中</value>
      <webElementGuid>c0a0eb8b-afb6-4ee4-aac2-359761478d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataGridTable_datagrid-row-r1-2-0&quot;)/td[8]/div[@class=&quot;datagrid-cell dataGridTable_datagrid-cell-c1-T_CONTRACT_NAME&quot;]/div[1]/a[@class=&quot;datagridhref&quot;]</value>
      <webElementGuid>904b59b8-76a7-4998-9c6a-0821198ee05e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/SignatureBoard/iframe__ifm</value>
      <webElementGuid>868d2aee-5e1a-44be-b1c0-3ad6d85e76bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;showContractView('856b1f83-4699-4eee-9f9c-b0c10100acbb','1','合同签署流程','签订')&quot;]</value>
      <webElementGuid>bc169f19-e810-4e59-a5e2-03e0b021dae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='dataGridTable_datagrid-row-r1-2-0']/td[8]/div/div/a</value>
      <webElementGuid>957c8cfc-c07e-4cf8-be92-93533ce9a2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'autotest1条签署中')]</value>
      <webElementGuid>6f08ca59-01bd-443b-82d1-f8a17814013c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CON-COM-20231121-001M'])[1]/following::a[1]</value>
      <webElementGuid>d6ce0475-5082-404c-8c66-6f73fc52d56e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAG-COM-20231121-001M'])[1]/following::a[1]</value>
      <webElementGuid>935343b8-fc76-4203-bb1e-ab18622fb15b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='独立合同'])[1]/preceding::a[1]</value>
      <webElementGuid>57305bf2-182a-44fd-b800-a8ed86e80777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CNY'])[1]/preceding::a[1]</value>
      <webElementGuid>d421a3ef-656c-4af3-ab66-124e8ad92d43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='autotest1条签署中']/parent::*</value>
      <webElementGuid>4cc7d273-4529-4289-9495-f5d15035a120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[4]</value>
      <webElementGuid>2e53164b-d00f-4a98-aa61-a45e0d6649ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/div/a</value>
      <webElementGuid>e2a080c2-a170-4e0d-869d-c211d88e7b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'autotest1条签署中' or . = 'autotest1条签署中')]</value>
      <webElementGuid>6bb82a60-70d8-4bfa-b842-34ba7f18ec0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
