<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_ceshi a a a</name>
   <tag></tag>
   <elementGuidId>d25b2725-494f-4bf0-ac07-76cf3dff1bd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='newView']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#newView</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e744412a-1903-4ac7-b250-b552171c9e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>newView</value>
      <webElementGuid>fc41af05-9ed9-4a8f-ac25-da1feff78ec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>newView</value>
      <webElementGuid>79c93ce5-84c1-4ba3-bd95-11f7bb2cd53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>7eea712f-45d6-4df2-9907-7614e4b4a709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f05826a1-710d-40d7-acf5-e27e01946277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DASContractSignUp/BWProcess/BWConTractDetailsN/Page/ContractDetail.cshtml?cid=856b1f83-4699-4eee-9f9c-b0c10100acbb&amp;&amp;version=1</value>
      <webElementGuid>a614ea98-73d7-41e6-8071-b9475e975bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ceshi a a a </value>
      <webElementGuid>4910a063-b4b8-4931-8b58-cae5e5acd1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;newView&quot;)</value>
      <webElementGuid>e78e018e-6f99-45a8-b8f3-d9a38901a1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/SignatureBoard/iframe__ifm</value>
      <webElementGuid>d480bb4f-4d88-4a71-bbbb-16de8b172d62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='newView']</value>
      <webElementGuid>b32d8c72-c743-4673-a999-0562f71f6103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='查看'])[1]/following::iframe[1]</value>
      <webElementGuid>d30d95c8-38e4-44ec-bf1d-1234a91edb72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'newView', '&quot;', ')')])[1]/following::iframe[1]</value>
      <webElementGuid>d5575081-f61c-4da4-b995-daf1538a3c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='关闭'])[1]/preceding::iframe[1]</value>
      <webElementGuid>411d487a-9106-4683-8132-96ccc156fd41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ceshi a a a']/parent::*</value>
      <webElementGuid>c1cba3ea-32dc-43a8-b614-5f4c42b7c993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>cbab61dd-1fe5-4182-98a6-48c9fed87e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'newView' and @name = 'newView' and @src = '/DASContractSignUp/BWProcess/BWConTractDetailsN/Page/ContractDetail.cshtml?cid=856b1f83-4699-4eee-9f9c-b0c10100acbb&amp;&amp;version=1' and (text() = 'ceshi a a a ' or . = 'ceshi a a a ')]</value>
      <webElementGuid>6dcb6a4c-3da6-444c-af75-841a56e8b929</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
