<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_contractname_search</name>
   <tag></tag>
   <elementGuidId>f0497f2f-fbdd-4816-b480-933ccf7825d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[2]/span/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_easyui_textbox_input41</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef474a5e-64e5-4feb-be6f-0fe7e00cd654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_easyui_textbox_input41</value>
      <webElementGuid>3f87d138-dbba-4e17-96d5-e98156d21df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78a6da88-a696-4668-bde5-c96d00e5797a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-text validatebox-text</value>
      <webElementGuid>605e01c0-2433-41c1-93f6-fa4203ef9fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b53eac5e-a164-48d5-bc57-e9bc07b591b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_easyui_textbox_input41&quot;)</value>
      <webElementGuid>e902d34f-6007-4e6c-92ca-c63789953f77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/SignatureBoard/iframe__ifm</value>
      <webElementGuid>d2898bea-cdca-4398-b3b1-c16e80afc0c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_easyui_textbox_input41']</value>
      <webElementGuid>ddddf464-7546-45ba-ab49-e2d1729074b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/span/input</value>
      <webElementGuid>d29baf2b-2964-458c-bd3d-3bb343d8b6a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_easyui_textbox_input41' and @type = 'text']</value>
      <webElementGuid>cb722caa-f707-49f0-84d8-ade05e67a9b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
