<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ordernext</name>
   <tag></tag>
   <elementGuidId>c220a4fe-5caa-4e41-bb55-05c6f1590c5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabs']/div/div[3]/ul/li[6]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(6) > a.tabs-inner > span.tabs-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>21fb2f83-cc9b-4e99-8fa6-f1dd4cc52b0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabs-title</value>
      <webElementGuid>4a9d6b61-6a8f-49b3-a4ae-39fc26e6c8fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>用印及签订</value>
      <webElementGuid>bfc5f4c0-f6eb-4100-bbf2-b73bd814728c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabs&quot;)/div[@class=&quot;tabs-header tabs-header-noborder&quot;]/div[@class=&quot;tabs-wrap&quot;]/ul[@class=&quot;tabs&quot;]/li[6]/a[@class=&quot;tabs-inner&quot;]/span[@class=&quot;tabs-title&quot;]</value>
      <webElementGuid>a4da86fa-4882-4a5b-b026-7e7e00562a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/SignatureBoard/iframe_ceshi a a a</value>
      <webElementGuid>2f9a3047-ab5b-4af8-87b2-ae8d845c09c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs']/div/div[3]/ul/li[6]/a/span</value>
      <webElementGuid>ad6ae419-c8e2-4a02-b8f5-b10da42384a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='审查记录'])[1]/following::span[2]</value>
      <webElementGuid>6ac609c9-cc5f-4dd1-b11e-1e195c616377</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='关联合同'])[1]/following::span[4]</value>
      <webElementGuid>c571b62a-2322-414c-b1cc-ea5aad2c7aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='履行明细'])[1]/preceding::span[2]</value>
      <webElementGuid>8c89f712-8bce-4fee-b9be-11bc6114b4c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='时间轴'])[1]/preceding::span[4]</value>
      <webElementGuid>98550d89-43fc-475d-8070-7d66e8ff931f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='用印及签订']/parent::*</value>
      <webElementGuid>15ad5929-821a-48e8-be6e-5f7478fb0a00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/span</value>
      <webElementGuid>9d2635b3-e99e-47e3-b881-74d42970c299</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '用印及签订' or . = '用印及签订')]</value>
      <webElementGuid>73fbd4bb-8e5f-4c6b-b3a7-e1aeaa98694b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
