<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_startdate</name>
   <tag></tag>
   <elementGuidId>a2cc7704-cf45-46ba-ab2d-b062a7910cab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.textbox-icon.combo-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='extendinfo']/div[2]/div/span/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4950744e-bd1a-42b3-a0b6-c6e08344af3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>b33ea609-17eb-4069-af2c-90720a78277c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-icon combo-arrow</value>
      <webElementGuid>e0f8b6b5-4972-4c68-9e86-61ae054bea7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>99185c04-a30b-4e9d-b3c8-bceb6f7d1f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>994837b7-189f-438e-9dde-8640333e61e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;extendinfo&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4&quot;]/span[@class=&quot;textbox easyui-fluid combo datebox&quot;]/span[@class=&quot;textbox-addon textbox-addon-right&quot;]/a[@class=&quot;textbox-icon combo-arrow&quot;]</value>
      <webElementGuid>6bbcb596-bdb5-4e08-9429-296cdb1b8a9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_infosupplement_page/iframe_DAG_ifm</value>
      <webElementGuid>b0059253-d8a0-4af7-9845-2ea3d44d6157</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='extendinfo']/div[2]/div/span/span/a</value>
      <webElementGuid>9bd8a247-ae28-4d5b-9956-f97c39b0ebe3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:;')]</value>
      <webElementGuid>d85b5943-4d3e-4235-82f2-8b736a5622b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>3d8f9c33-da67-404c-92a5-1ec380d1e670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;']</value>
      <webElementGuid>1fa55156-aab8-4115-9933-e1d056e6ae70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
