<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_DAG_ifm</name>
   <tag></tag>
   <elementGuidId>23556640-5ad5-4274-acc7-6f716dc1b578</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ifm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>72b6a676-4e9a-4a05-b4eb-3c0a84809dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifm</value>
      <webElementGuid>f7ac77ce-6f10-43f5-aa17-e646759f9fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ifm</value>
      <webElementGuid>bf199c09-94fd-4220-8ba5-500335cf5d2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Datadetail.cshtml?type=extend&amp;cid=46f9a92f-b49e-45ad-bae0-251e34d8f028</value>
      <webElementGuid>9efb0a98-8e3a-4f6b-9cd1-1bd8cb8a9d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>bf4d85bb-a043-4f25-a502-6e1b25681f7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a1c27e2c-861f-48bd-955e-f585ae6b0201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ifm&quot;)</value>
      <webElementGuid>0f3c5450-aa66-47f3-99c1-c9a48f463771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_infosupplement_page/iframe__ifm</value>
      <webElementGuid>ee6b88c5-6d72-4ff3-b156-9c9ab2435a4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifm']</value>
      <webElementGuid>f5b9585e-4bc7-4a50-a084-6745a8fc2c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c8d09443-3a5c-4ad0-a68f-debd9c8d67e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ifm' and @name = 'ifm' and @src = 'Datadetail.cshtml?type=extend&amp;cid=46f9a92f-b49e-45ad-bae0-251e34d8f028']</value>
      <webElementGuid>78cf8ad5-6087-43cf-8e93-daab0c0e7bf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
