<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_submit</name>
   <tag></tag>
   <elementGuidId>12e8e7b4-19de-4c02-9e92-cc91914c682e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='btnSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>048119b5-cc17-4c0e-a3ca-78afc5bc1772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSubmit</value>
      <webElementGuid>6829ba28-0783-44fa-8e24-2d35a8289815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-group-justified</value>
      <webElementGuid>ada3d978-2f0e-4724-bc67-0766bc19e3f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n-html</name>
      <type>Main</type>
      <value>提交</value>
      <webElementGuid>bec737cd-a272-434f-a452-3685719fcedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>提交</value>
      <webElementGuid>40b56848-fd68-4ec3-a9fa-376ec554d83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSubmit&quot;)</value>
      <webElementGuid>d26b56b6-4d53-4023-80e9-092ee166d7e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='btnSubmit']</value>
      <webElementGuid>169501cb-86f8-4081-8ed1-994cf78433d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div[3]/div[2]/div[3]/div[5]/span</value>
      <webElementGuid>269a823e-097c-4eaf-be1d-0c200e3e29df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='忘记密码'])[1]/following::span[1]</value>
      <webElementGuid>faa5a504-de8a-4b30-993b-f3a1c322519f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='记录密码'])[1]/following::span[1]</value>
      <webElementGuid>7a170382-375e-4999-8d65-c08d31fa78fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'btnSubmit', '&quot;', ')')])[1]/preceding::span[1]</value>
      <webElementGuid>69bed158-2901-4b4c-a0d9-fcff2e6e2081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='提交']/parent::*</value>
      <webElementGuid>3e896169-8c42-47de-8e57-21a704ce3d41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/span</value>
      <webElementGuid>0e65e443-4e8c-4824-9101-bc4494cefd77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'btnSubmit' and (text() = '提交' or . = '提交')]</value>
      <webElementGuid>ea425b0c-4107-482c-a1bc-b948f9d14f05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
