<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_password</name>
   <tag></tag>
   <elementGuidId>834c7770-6464-471f-a9b1-c28d762974bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c9cfcaf-b698-4c83-9381-d93937115557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtP</value>
      <webElementGuid>74264da3-dc2f-47f7-ba17-7c133b5aa1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>5488d5b8-8e58-4a0a-8ce8-8cb086965e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>53371a78-8680-4e96-9f9a-aebbc7ed66bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n-placeholder</name>
      <type>Main</type>
      <value>密码</value>
      <webElementGuid>6d98fb40-00e1-49d0-a8f5-6a3a2928fa00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>98bc9461-69e7-48c8-8c86-7c6de6b9984c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>isnull</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>034a3afa-fe9d-4ddd-bed9-79cf20336a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>7f9eb54c-f461-4421-a310-4c281bc064db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>密码</value>
      <webElementGuid>59df39cc-3e8d-4f4c-9bee-694160c11317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtP&quot;)</value>
      <webElementGuid>5c5eb1c7-d20f-4c52-86f5-634ffb466f42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtP']</value>
      <webElementGuid>56a5d1f0-5cf5-494f-98fd-8d5218cd2eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div[3]/div[2]/div[3]/div[2]/div/input</value>
      <webElementGuid>c1d987ba-c60b-4b3f-8cce-c9f0f5ec56dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>94ad2fd6-a646-4e4d-a485-d05d69b8e02b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtP' and @type = 'password' and @placeholder = '密码']</value>
      <webElementGuid>0f41b532-0de7-4e3b-98b9-c6a29a04b3ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
