<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_fileupload</name>
   <tag></tag>
   <elementGuidId>6bf4ddfa-2f67-4529-9a75-d09222a52352</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='upload']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#upload > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f79779f0-1f4c-47b6-836a-ef9f64e63500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n-text</name>
      <type>Main</type>
      <value>dag_upload</value>
      <webElementGuid>51841aa9-1e6a-4e8c-bd5b-fb62f5081443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>上传</value>
      <webElementGuid>64970de3-be31-4ddb-a4ed-2b862110aaf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;upload&quot;)/span[1]</value>
      <webElementGuid>d5dca949-abbd-430d-82f7-ef75c02ea4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/ContractChange_page/iframe__ifm_1</value>
      <webElementGuid>e37bd6f9-15fe-461c-ae4e-393bbcc23f57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='upload']/span</value>
      <webElementGuid>05dc6671-71a1-4191-9053-949842da6bd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='显示1到2,共2记录'])[1]/following::span[1]</value>
      <webElementGuid>65fb1cde-7c6a-4212-8383-77c77b4a2425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='共1页'])[1]/following::span[10]</value>
      <webElementGuid>4cf9b41e-2c0e-4ae1-b0b1-2113db7b7d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='关键词批导上传'])[1]/preceding::span[1]</value>
      <webElementGuid>5b3d1c0e-4159-4e9c-9edf-463142765c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='关键字：DAG'])[1]/preceding::span[2]</value>
      <webElementGuid>e291da5b-a062-4cee-9933-c47b36aaa0eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='上传']/parent::*</value>
      <webElementGuid>2890f29a-7583-42c4-9d01-751aeeeb8239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/button/span</value>
      <webElementGuid>04300a4c-db0c-41e9-8d75-3a82c1d720ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '上传' or . = '上传')]</value>
      <webElementGuid>f668ac8c-e5a4-44bc-bc00-0d21f74a19d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
