<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_contractprice</name>
   <tag></tag>
   <elementGuidId>7b1acf68-18c3-4e87-a29f-9e58ab565d85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_easyui_textbox_input154']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_easyui_textbox_input154</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e72e3bf4-8e1c-41b1-9845-ed2fd72c960d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_easyui_textbox_input154</value>
      <webElementGuid>0fb53d22-5136-4711-9679-b270b2306276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3f89606f-edc3-4d71-97f1-a54f159cce7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-text validatebox-text validatebox-invalid tooltip-f</value>
      <webElementGuid>08076173-83e9-4711-acd1-1a2d8cbf04cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9315b519-1ca8-4567-b4bd-e6b601d116d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_easyui_textbox_input154&quot;)</value>
      <webElementGuid>b4e83769-9ebb-48f4-b6a3-09fdfb0738e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/ContractChange_page/iframe__ifm_1</value>
      <webElementGuid>61224858-2335-4997-9bb1-2beded6213f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_easyui_textbox_input154']</value>
      <webElementGuid>15c2759f-b1b0-46cd-baee-dd87ebbf81a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContractGrid_datagrid-row-r1-2-0']/td[15]/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>e34051a8-9d53-4869-a4a8-3db5461a01f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[15]/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>311d0d15-28e1-41b3-8505-40d587ebcd33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_easyui_textbox_input154' and @type = 'text']</value>
      <webElementGuid>280d0638-ff0f-413b-b7cc-86ac2282ee23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
