<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Others</name>
   <tag></tag>
   <elementGuidId>71c13dba-2f84-458f-90c6-904ed326b69c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='AttachTree']/li[5]/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-tree-text.ui-tree-text-hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>31fab415-ef84-4984-a8a3-fb1ecc5df748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-tree-text ui-tree-text-hover</value>
      <webElementGuid>311e6aa3-0d86-4029-9977-7c95cdf5962b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Others</value>
      <webElementGuid>96787cb6-420e-44f8-ae60-f52f13e2995c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Others</value>
      <webElementGuid>be7dcf91-dc4d-49a7-b48c-cce32d366f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AttachTree&quot;)/li[5]/span[@class=&quot;ui-tree-text ui-tree-text-hover&quot;]</value>
      <webElementGuid>a156736d-131c-46d0-8a50-c92cd4dd52fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/ContractChange_page/iframe__ifm_1</value>
      <webElementGuid>7c0566b2-a8be-4603-b827-da49280095aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='AttachTree']/li[5]/span[3]</value>
      <webElementGuid>b1dd2ebc-8c2b-4928-85c2-f3996a91124d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contract'])[1]/following::span[3]</value>
      <webElementGuid>f0f96264-8d72-4e87-9eac-7c73d6f87396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RFQ'])[1]/following::span[6]</value>
      <webElementGuid>6b46cbe8-c206-4150-86d2-6d8a4217646c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CID'])[2]/preceding::span[1]</value>
      <webElementGuid>e8694bca-1bf7-4684-b70d-15a1c71f5e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T_SUP_CID'])[1]/preceding::span[3]</value>
      <webElementGuid>ed0bff87-a5d8-40f4-b9f7-63d47650a754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Others']/parent::*</value>
      <webElementGuid>c17c005c-a9dd-4e77-ba87-b2c59fd82f68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/span[3]</value>
      <webElementGuid>ba23c5d9-2bed-4531-9d8a-da13e6ba6f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Others' and (text() = 'Others' or . = 'Others')]</value>
      <webElementGuid>3fb8afbe-b88d-4c91-90e3-129cdbb7ec11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
