<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_authorizecontract</name>
   <tag></tag>
   <elementGuidId>8cb649a2-9c2e-4e01-ae44-a3da6059ffd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='dataGrid_datagrid-row-r1-2-0']/td[6]/div/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;授权合同&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>824ebec2-8933-4495-b6ed-043d075a7a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>455a21e9-4ab3-4470-bf02-238944ad5dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>授权合同</value>
      <webElementGuid>68cd08d2-5709-4dec-a3f2-52c2e843d9f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>AuthorizationClick('ac997b52-db14-4845-9c78-b0d7010a3be4','28073485','汤环宇')</value>
      <webElementGuid>330e6533-a60a-4c27-ada7-cc7b976d7c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>授权合同</value>
      <webElementGuid>df74f8f0-f0ab-47a2-9a78-b0d8fbd500e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataGrid_datagrid-row-r1-2-0&quot;)/td[6]/div[@class=&quot;datagrid-cell dataGrid_datagrid-cell-c1-operate&quot;]/a[1]</value>
      <webElementGuid>81722970-427b-4584-87ec-bc121b8d5717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/SignatureBoard/userauthorize_page/iframe__MultAuthorListFrame</value>
      <webElementGuid>a8670702-702c-4943-87ea-d16069688673</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;AuthorizationClick('ac997b52-db14-4845-9c78-b0d7010a3be4','28073485','汤环宇')&quot;]</value>
      <webElementGuid>74b4af84-15e9-46a0-8db2-62f62f977289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='dataGrid_datagrid-row-r1-2-0']/td[6]/div/a</value>
      <webElementGuid>f547a097-6c29-4cb5-be77-9b63b2fd0726</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'授权合同')]</value>
      <webElementGuid>9026f5fe-ebc7-4182-ab9a-72e8e47c1ceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='wells.wang1@budweiserapac.com'])[1]/following::a[1]</value>
      <webElementGuid>e936f3da-f41a-4c8e-a572-dc38275bede3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='汤环宇'])[1]/following::a[1]</value>
      <webElementGuid>c6e74f3a-904e-4a76-bd2d-df16e66c4fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='查看授权合同'])[1]/preceding::a[1]</value>
      <webElementGuid>6a242bfd-ff4b-4afb-9468-906eadff99f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='第'])[1]/preceding::a[4]</value>
      <webElementGuid>cec91108-411d-4993-bd8d-34482b3c9eba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='授权合同']/parent::*</value>
      <webElementGuid>55478753-5310-4fff-9b4b-4cebb39f1d06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:;')]</value>
      <webElementGuid>943f3e64-d9b4-4800-b225-3094cdc132d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>27edc2f4-1e1d-472f-b545-85a05dfb5542</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and @title = '授权合同' and (text() = '授权合同' or . = '授权合同')]</value>
      <webElementGuid>95400056-eaa5-47b7-aa68-80f4e10dba31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
