<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_viewauthorizedcontract</name>
   <tag></tag>
   <elementGuidId>c14fde4f-6d5b-4b14-a008-cb69d8230eb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;查看授权合同&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='dataGrid_datagrid-row-r1-2-0']/td[6]/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5f406450-6438-498e-89a8-65f35b8e6d08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>3ebcf595-107a-4124-b060-3a060fe0f600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>查看授权合同</value>
      <webElementGuid>98f75d14-ab9c-4c85-9676-49b1d9691a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ViewAuthorizationClick('c5eb607a-20f1-465b-b7f3-b0d800c04a31','28077170','汪晋怡')</value>
      <webElementGuid>fc523dbc-3ffa-48d2-ae0b-e7d291700496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>查看授权合同</value>
      <webElementGuid>26d4ecca-1a91-4727-bca8-67403c9108bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dataGrid_datagrid-row-r1-2-0&quot;)/td[6]/div[@class=&quot;datagrid-cell dataGrid_datagrid-cell-c1-operate&quot;]/a[2]</value>
      <webElementGuid>49072373-5ff8-4f90-8545-642bea6e7885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/SignatureBoard/userauthorize_page/iframe__MultAuthorListFrame</value>
      <webElementGuid>79d2adea-be92-4e26-b7fd-01d7a0350df1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;ViewAuthorizationClick('c5eb607a-20f1-465b-b7f3-b0d800c04a31','28077170','汪晋怡')&quot;]</value>
      <webElementGuid>79d020d4-e66d-462f-9b86-bb8d68e8093f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='dataGrid_datagrid-row-r1-2-0']/td[6]/div/a[2]</value>
      <webElementGuid>4ff47ee1-8796-4f62-be30-33bf213619b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'查看授权合同')]</value>
      <webElementGuid>37b684c0-4b2e-4b53-854c-821772c014b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='授权合同'])[1]/following::a[1]</value>
      <webElementGuid>567aa087-2562-4777-bfbf-92cabacb7217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='wells.wang1@budweiserapac.com'])[1]/following::a[2]</value>
      <webElementGuid>6f230d84-d851-4dfa-a05a-ee2a8f7e046f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='第'])[1]/preceding::a[3]</value>
      <webElementGuid>0aef791c-f05d-4306-b540-81015735e353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='共1页'])[1]/preceding::a[3]</value>
      <webElementGuid>234c14e3-4d51-4afd-b78e-b35ef9871671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='查看授权合同']/parent::*</value>
      <webElementGuid>0a862f95-70d0-40b6-a03a-9c2e2c0c4f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[2]</value>
      <webElementGuid>0b167db6-2edc-46aa-b795-eba60dfb7d37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>fced13b4-8c81-4359-bf8e-bd4e9fea5748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and @title = '查看授权合同' and (text() = '查看授权合同' or . = '查看授权合同')]</value>
      <webElementGuid>d3825c5f-f850-48a4-9e56-f18a648aa136</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
