<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_userauthorize</name>
   <tag></tag>
   <elementGuidId>5b187dff-e264-4f33-a778-805963e52570</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MyTempToolBar']/div/div/span[3]/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a5833861-1698-4441-a6da-ac2efad1e588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>l-btn-text</value>
      <webElementGuid>905d8d7a-a90b-4c3e-8343-bd576e8b27c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>用户授权</value>
      <webElementGuid>234b421a-335c-4fa3-908c-bd248aac6e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MyTempToolBar&quot;)/div[@class=&quot;tbBeforeBox row&quot;]/div[@class=&quot;btn-group pull-left toolBox&quot;]/span[@class=&quot;easyui-linkbutton l-btn l-btn-small&quot;]/span[@class=&quot;l-btn-left&quot;]/span[@class=&quot;l-btn-text&quot;]</value>
      <webElementGuid>532ebe19-9428-4ead-be95-6d3850e8b252</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/SignatureBoard/userauthorize_page/iframe__ifm</value>
      <webElementGuid>f9d8e14a-3289-4256-90bf-509bc4b035df</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MyTempToolBar']/div/div/span[3]/span/span</value>
      <webElementGuid>d188bd6a-b78b-48fd-a5a0-52c8d3740faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='批量授权'])[1]/following::span[3]</value>
      <webElementGuid>deff37a3-541b-4629-ba91-37a402426935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='导出'])[1]/following::span[6]</value>
      <webElementGuid>629f9a10-702f-4a19-b243-f8c3bfaf8133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='授权记录'])[1]/preceding::span[1]</value>
      <webElementGuid>6b6b9894-d575-478a-af2b-22dd5e2732da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='全部'])[1]/preceding::span[4]</value>
      <webElementGuid>05fc2f54-f7dd-4bc0-876a-ae6115e8f3c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='用户授权']/parent::*</value>
      <webElementGuid>20653a62-e404-455c-a185-8a7b4a9e2a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]/span/span</value>
      <webElementGuid>6a69aec5-904f-4419-a90d-8dd3fb217807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '用户授权' or . = '用户授权')]</value>
      <webElementGuid>a3770113-9d5a-4a46-84b4-eb680afa8e90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
