<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_--28073485_AuthorizationClick</name>
   <tag></tag>
   <elementGuidId>f091f1f3-e617-4d2a-afa3-8727918a0c78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='AuthorizationClick']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AuthorizationClick</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f6f8e3cf-7c2e-4189-9844-c5f8af47747f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AuthorizationClick</value>
      <webElementGuid>8f2219fc-acb7-47c0-a2a9-3a911a37e0c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AuthorizationClick</value>
      <webElementGuid>27f7c668-a936-4b6a-98fe-72afd454b698</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>68cd01a4-e72b-4f2e-b1ae-46ea07319ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c340294c-0b01-4683-9562-52cb67641da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DASContractSignUp/BWProcess/ConTractRelatMy/Page/AuthPage/MultAuthorList.cshtml?Ucid=0a78486d-3bc7-4e84-91b0-b0d7010345f9&amp;Ucode=28073485&amp;Uname=%u6C64%u73AF%u5B87</value>
      <webElementGuid>dbc32b44-fca3-49cf-a089-fa1177a2c259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AuthorizationClick&quot;)</value>
      <webElementGuid>c8fe0587-2204-4ac6-8e66-dcaed6e36942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/SignatureBoard/userauthorize_page/iframe__ifm</value>
      <webElementGuid>99da1fb2-8a97-4ac5-8c20-fefe7074370b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='AuthorizationClick']</value>
      <webElementGuid>0d2b9d48-95ea-4f63-bbf8-fc3cacc61c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='AuthorizationClick_dialog']/iframe</value>
      <webElementGuid>875526e8-1d32-472d-b698-d4bd381c7b1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div[2]/iframe</value>
      <webElementGuid>2038802f-9853-41ef-aa4c-000a31108b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'AuthorizationClick' and @name = 'AuthorizationClick' and @src = '/DASContractSignUp/BWProcess/ConTractRelatMy/Page/AuthPage/MultAuthorList.cshtml?Ucid=0a78486d-3bc7-4e84-91b0-b0d7010345f9&amp;Ucode=28073485&amp;Uname=%u6C64%u73AF%u5B87']</value>
      <webElementGuid>d15e3549-0782-4a49-9e48-9b7bd31af040</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
