<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__ViewAuthorizationClick</name>
   <tag></tag>
   <elementGuidId>83920b28-478c-4e4a-b0da-584eeb119053</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ViewAuthorizationClick</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ViewAuthorizationClick']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e1460a41-9489-4268-b82f-f81bf1ab4f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ViewAuthorizationClick</value>
      <webElementGuid>6ee4f056-aa3f-40de-9bc1-1ebdf270f5d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ViewAuthorizationClick</value>
      <webElementGuid>5d980688-ad1f-440c-9aca-da30cf5bed17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>94216e0e-4705-448b-bd0f-3902f19f50ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d4768518-d6d3-4e53-a2fa-6ed1dc81ebc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DASContractSignUp/BWProcess/ConTractRelatMy/Page/AuthPage/MultAuthorListView.cshtml?Ucid=c5eb607a-20f1-465b-b7f3-b0d800c04a31&amp;Ucode=28077170&amp;Uname=%u6C6A%u664B%u6021</value>
      <webElementGuid>3fb34f06-b857-4671-a176-0a0258eeae92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ViewAuthorizationClick&quot;)</value>
      <webElementGuid>f5357183-1256-40a7-b9ea-dbd40098be1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/SignatureBoard/userauthorize_page/iframe__ifm</value>
      <webElementGuid>cb44bd85-0df9-4514-aca8-af1f18ffa576</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ViewAuthorizationClick']</value>
      <webElementGuid>5dbbaea8-8fb5-4182-86f6-606ea9e50762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ViewAuthorizationClick_dialog']/iframe</value>
      <webElementGuid>0161d028-f7dc-497e-9b36-d3ef42e762eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div[2]/iframe</value>
      <webElementGuid>336ea086-9fac-4505-8796-5bfe9df64b0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ViewAuthorizationClick' and @name = 'ViewAuthorizationClick' and @src = '/DASContractSignUp/BWProcess/ConTractRelatMy/Page/AuthPage/MultAuthorListView.cshtml?Ucid=c5eb607a-20f1-465b-b7f3-b0d800c04a31&amp;Ucode=28077170&amp;Uname=%u6C6A%u664B%u6021']</value>
      <webElementGuid>fd7c2b20-53b0-42a8-ba7d-ec907ec987d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
