<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkalluser</name>
   <tag></tag>
   <elementGuidId>badd4fe5-8ed0-4e60-b321-35e2c4e46126</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;checkbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c36a59e0-611e-4a7f-9d0d-05069fe50c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>205397f2-6661-4506-ac50-8ab887016cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ConTractCSMDiv&quot;)/div[@class=&quot;easyui-layout layout easyui-fluid&quot;]/div[@class=&quot;panel layout-panel layout-panel-center panel-htop&quot;]/div[@class=&quot;panel-body panel-body-noheader layout-body panel-noscroll&quot;]/div[@class=&quot;easyui-layout layout easyui-fluid&quot;]/div[@class=&quot;panel layout-panel layout-panel-center panel-htop&quot;]/div[@class=&quot;panel-body panel-body-noheader layout-body panel-noscroll&quot;]/div[@class=&quot;panel datagrid panel-htop easyui-fluid&quot;]/div[@class=&quot;datagrid-wrap panel-body panel-body-noheader panel-body-noborder&quot;]/div[@class=&quot;datagrid-view&quot;]/div[@class=&quot;datagrid-view1&quot;]/div[@class=&quot;datagrid-header&quot;]/div[@class=&quot;datagrid-header-inner&quot;]/table[@class=&quot;datagrid-htable&quot;]/tbody[1]/tr[@class=&quot;datagrid-header-row&quot;]/td[@class=&quot;datagrid-header-over&quot;]/div[@class=&quot;datagrid-header-check&quot;]/input[1]</value>
      <webElementGuid>28ae7886-fc29-470e-94ac-f8a91504e2d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/SignatureBoard/userauthorize_page/iframe__MultAuthorListFrame</value>
      <webElementGuid>1da2d563-28fb-41f6-b78a-787f096bd60d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>09a9c2f8-b2fb-41f6-bb1a-65cca3ec13a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ConTractCSMDiv']/div/div/div/div/div[2]/div/div/div/div/div/div/div/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>4ba038fd-b4eb-45f2-b302-5b199f4fe969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>96efe262-9fb6-43ca-871f-5182ad82bcbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>3920dfab-a9a2-45dc-a012-52ffec0e736d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
