<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkall_needtocancel</name>
   <tag></tag>
   <elementGuidId>77a627b8-af0d-4111-83d0-586061cc8ace</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[type=&quot;checkbox&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cf317ff-dda9-4f97-bd26-d7938c5ca917</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6b6df296-ff13-47fb-85d6-3fab61c75b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ConTractCSMDiv&quot;)/div[@class=&quot;easyui-layout layout easyui-fluid&quot;]/div[@class=&quot;panel layout-panel layout-panel-center panel-htop&quot;]/div[@class=&quot;panel-body panel-body-noheader layout-body panel-noscroll&quot;]/div[@class=&quot;easyui-layout layout easyui-fluid&quot;]/div[@class=&quot;panel layout-panel layout-panel-center panel-htop&quot;]/div[@class=&quot;panel-body panel-body-noheader layout-body panel-noscroll&quot;]/div[@class=&quot;panel datagrid panel-htop easyui-fluid&quot;]/div[@class=&quot;datagrid-wrap panel-body panel-body-noheader panel-body-noborder&quot;]/div[@class=&quot;datagrid-view&quot;]/div[@class=&quot;datagrid-view1&quot;]/div[@class=&quot;datagrid-header&quot;]/div[@class=&quot;datagrid-header-inner&quot;]/table[@class=&quot;datagrid-htable&quot;]/tbody[1]/tr[@class=&quot;datagrid-header-row&quot;]/td[@class=&quot;datagrid-header-over&quot;]/div[@class=&quot;datagrid-header-check&quot;]/input[1]</value>
      <webElementGuid>63dec232-4b98-4cb8-b1a2-3651ffe889a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/SignatureBoard/userauthorize_page/iframe__ViewAuthorizationClick</value>
      <webElementGuid>0e3ff3a0-2ef1-4b4b-8e78-4b53ea85c02b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='checkbox']</value>
      <webElementGuid>403c9a39-cf64-461d-a409-fdca6965b748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ConTractCSMDiv']/div/div/div/div/div[2]/div/div/div/div/div/div/div/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>ba429bac-0e18-497d-b634-2985d9fe42c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/input</value>
      <webElementGuid>74c045ba-3575-40a2-9024-05768e7f1742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>01927194-8f43-49d6-96f4-ac7c89653045</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
