<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_draftstyle</name>
   <tag></tag>
   <elementGuidId>68eed532-46c8-4702-b48e-c4f6114017b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='SubjectFile_datagrid-row-r2-2-0']/td[6]/div/table/tbody/tr/td/span/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td > span.textbox.combo > span.textbox-addon.textbox-addon-right > a.textbox-icon.combo-arrow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>65f3b4b8-470f-49b2-9ef7-0d6272c60de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>055b7817-522b-4f6c-80a4-417b8a7afd67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-icon combo-arrow</value>
      <webElementGuid>0eee35cb-63f4-41d0-8226-4c6ff92aeebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>icon-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6e11588f-8cb7-4393-b8c1-dcef171b608b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a7e77df6-da7a-482e-93ac-42da4a7832f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubjectFile_datagrid-row-r2-2-0&quot;)/td[6]/div[@class=&quot;datagrid-cell SubjectFile_datagrid-cell-c2-T_DRAF_CODE datagrid-editable&quot;]/table[1]/tbody[1]/tr[1]/td[1]/span[@class=&quot;textbox combo&quot;]/span[@class=&quot;textbox-addon textbox-addon-right&quot;]/a[@class=&quot;textbox-icon combo-arrow&quot;]</value>
      <webElementGuid>83429a11-6e47-4430-b704-28b59feeb4b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='SubjectFile_datagrid-row-r2-2-0']/td[6]/div/table/tbody/tr/td/span/span/a</value>
      <webElementGuid>e958d16f-31e4-4e73-8031-b3a989d30786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[18]</value>
      <webElementGuid>6d4ba35b-dd52-43c6-964a-089d8a89d26e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span/span/a</value>
      <webElementGuid>c9e68b9b-e62e-4480-bb0f-7df40e4914c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;']</value>
      <webElementGuid>26e616ba-484c-4012-88b6-5f306fdd6ea3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
