<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alert_savesuccess</name>
   <tag></tag>
   <elementGuidId>63655d4f-a472-4173-82bc-a1574d4cd47a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[name=&quot;successalert&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@name='successalert']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>11590e4b-4fb7-41e5-b8f8-35727e46773c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-success show</value>
      <webElementGuid>53fbf25b-5b45-4062-a93d-0297b2b255e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>successalert</value>
      <webElementGuid>df12ccbf-0c2e-4b93-8374-7f7c7a138839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>本页面保存成功</value>
      <webElementGuid>013136be-e79f-435f-8e35-3d3d3bf72a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;panel-fit&quot;]/body[@class=&quot;panel-noscroll&quot;]/div[@class=&quot;alert alert-success show&quot;]</value>
      <webElementGuid>d1675d8d-e0a7-47bd-9f8d-ccea1fd5cd1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@name='successalert']</value>
      <webElementGuid>d9756069-375b-4837-abf9-c63c194c8a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='合同签署流程'])[2]/preceding::div[1]</value>
      <webElementGuid>393979ac-1d2b-4d25-b79b-d12c7c64490e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='对方经办人批量设置'])[1]/preceding::div[2]</value>
      <webElementGuid>90365a2c-75fe-4cac-91d5-12e50f7d325f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='本页面保存成功']/parent::*</value>
      <webElementGuid>4443fcf3-e651-4c11-9473-df5785d0f61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div</value>
      <webElementGuid>6ab99abf-eaf9-487e-a53e-99d8db59a22f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@name = 'successalert' and (text() = '本页面保存成功' or . = '本页面保存成功')]</value>
      <webElementGuid>cf8c7106-d8d6-402d-af02-e63d47a15bc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
