<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_selecttemplate</name>
   <tag></tag>
   <elementGuidId>70a46047-79a3-47fb-915c-79bda5d6ceff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.textbox-button.textbox-button-right.l-btn.l-btn-small.l-btn-focus > span.l-btn-left > span.l-btn-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='合同类型cid'])[1]/following::span[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e15a3d6d-5064-4d5e-b48d-5dbdd383aa07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>l-btn-text</value>
      <webElementGuid>196de1f5-ee50-427e-9261-32e039495589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>选择模板</value>
      <webElementGuid>da9f48b2-f342-4f72-84f7-4a4067e7a24d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubjectFile_datagrid-row-r2-2-0&quot;)/td[7]/div[@class=&quot;datagrid-cell SubjectFile_datagrid-cell-c2-T_FILE_NAME datagrid-editable&quot;]/table[1]/tbody[1]/tr[1]/td[1]/span[@class=&quot;textbox textbox-invalid&quot;]/a[@class=&quot;textbox-button textbox-button-right l-btn l-btn-small l-btn-focus&quot;]/span[@class=&quot;l-btn-left&quot;]/span[@class=&quot;l-btn-text&quot;]</value>
      <webElementGuid>964648da-debd-4eb7-a3f2-16e396c76ca5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='SubjectFile_datagrid-row-r2-2-0']/td[7]/div/table/tbody/tr/td/span/a/span/span</value>
      <webElementGuid>c27d312c-8fe0-4f72-8325-c5bb4cdd5797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='合同类型cid'])[1]/following::span[10]</value>
      <webElementGuid>5696c96b-107d-458c-b886-68f08f8222ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='合同类型名称'])[1]/following::span[12]</value>
      <webElementGuid>750919e1-7dcf-4d1b-8e3c-9ac89bdd1060</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='本模块应用到所有合同'])[4]/preceding::span[14]</value>
      <webElementGuid>a245d75a-748c-4901-8e04-eba2e8ff4061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='选择模板']/parent::*</value>
      <webElementGuid>01da5af7-140b-4384-b4b9-3ce359c6b99a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span/a/span/span</value>
      <webElementGuid>df120a58-2476-4292-9c63-c4b5c267ed5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '选择模板' or . = '选择模板')]</value>
      <webElementGuid>027e6a52-b485-476c-8f33-ae1063b4a80f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
