<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_applyall_3</name>
   <tag></tag>
   <elementGuidId>b777a5b7-eca8-484e-be73-4e0d8fee7e99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnMoThirdSend']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnMoThirdSend</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c51052bb-94d6-4a72-99ac-701c26cb3b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b41c3e1a-7c27-4abb-a958-7eb8c86a1250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnMoThirdSend</value>
      <webElementGuid>5aed599e-a4f7-4c2a-8f28-a53e15ba6600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default pull-right btn-sm btnBlueColor</value>
      <webElementGuid>69c273fe-9659-400c-b280-0adaac8c2d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n-text</name>
      <type>Main</type>
      <value>paperbase_page04</value>
      <webElementGuid>6a2544b7-c6f8-4bed-a053-f1bc47061af8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>本模块应用到所有合同</value>
      <webElementGuid>03bdf071-fbf4-4dd7-8f10-28f35caacead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnMoThirdSend&quot;)</value>
      <webElementGuid>24fe5a54-9b5b-4d42-acb2-d0db6a3e803b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnMoThirdSend']</value>
      <webElementGuid>ed5baa98-7424-4d7e-9a79-b689a92eb14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='选择模板'])[1]/following::button[1]</value>
      <webElementGuid>58638dca-6897-4952-83a4-0c2f8cc20842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='合同类型cid'])[1]/following::button[1]</value>
      <webElementGuid>ce420141-1b7b-4587-a8b2-b3d6f1ba9579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(仅Word/PDF格式文件，可用于后续电子签署)'])[1]/preceding::button[1]</value>
      <webElementGuid>13e39fd8-5263-4fc0-a00d-0d90791ae672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>3709770d-7543-4e6b-b2fc-86a1b7b550de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnMoThirdSend' and (text() = '本模块应用到所有合同' or . = '本模块应用到所有合同')]</value>
      <webElementGuid>244620d9-00a8-4263-937d-1b870ced992a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
