<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_batchcontract_delele</name>
   <tag></tag>
   <elementGuidId>4f0a48cb-74cc-4406-a3c4-3756bdb134da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.cfastclose</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/table/tbody/tr/td/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a620140a-5409-4fb3-941b-3c96aff58a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cfastclose</value>
      <webElementGuid>11147e5a-ae03-48b9-a875-253af0e2e982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>RemoveData('102b7519-2a42-4954-af0f-2187fef199c1')</value>
      <webElementGuid>4d7a446b-2bd7-4051-bf5b-6ef3596731a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftgrid_datagrid-row-r3-2-0&quot;)/td[1]/div[@class=&quot;cfastclose&quot;]</value>
      <webElementGuid>5cb0befb-50be-4a71-ae48-31e4ca135651</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick=&quot;RemoveData('102b7519-2a42-4954-af0f-2187fef199c1')&quot;]</value>
      <webElementGuid>2b1cb9e0-84b5-41ff-9ce7-41043e6d83ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='leftgrid_datagrid-row-r3-2-0']/td/div</value>
      <webElementGuid>7830de8c-88d3-4eb9-bcd0-51a5d5acbdd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/div</value>
      <webElementGuid>9c40bcff-9e08-4958-a6d2-0c5f04f8ddd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
