<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_applyall_2</name>
   <tag></tag>
   <elementGuidId>d710ea4d-a065-4208-9302-933bff19c40f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnMoSecondSend</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnMoSecondSend']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fed0d355-e504-48f6-a43d-7d2792669696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6ef0817b-22c6-4d7e-bac9-20cdd5913cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnMoSecondSend</value>
      <webElementGuid>b5ce5dfa-21cc-4f11-bf49-adcc796c7031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default pull-right btn-sm btnBlueColor</value>
      <webElementGuid>9da8e9d9-b143-44b8-9af6-d174a4e9ee5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n-text</name>
      <type>Main</type>
      <value>paperbase_page04</value>
      <webElementGuid>a362b1be-4a26-4192-b757-98241465903e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>本模块应用到所有合同</value>
      <webElementGuid>4044ae08-bde2-4f93-bf58-09c7cee9f861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnMoSecondSend&quot;)</value>
      <webElementGuid>4c167dd6-db74-4067-965e-d394330618fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnMoSecondSend']</value>
      <webElementGuid>9920a514-6939-4c21-90c8-06b93a3deed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='addForm']/div/div[2]/div[15]/div/button</value>
      <webElementGuid>93df4400-1326-465b-9706-ed89fe3bfd77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='价格清单备注'])[1]/following::button[1]</value>
      <webElementGuid>5eeec4e5-b8cf-4600-b554-bc926d983ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[15]/following::button[1]</value>
      <webElementGuid>0a89d3a4-ede3-4506-8080-e3c792b6f317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提交到'])[1]/preceding::button[1]</value>
      <webElementGuid>e4208c1d-91b0-4e01-9160-9ccdd67752ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='内部磋商'])[1]/preceding::button[1]</value>
      <webElementGuid>9c605ba0-8d87-4997-83a4-920eb130f6ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/button</value>
      <webElementGuid>fa2ba354-8a38-458c-a910-e8b30b865c74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnMoSecondSend' and (text() = '本模块应用到所有合同' or . = '本模块应用到所有合同')]</value>
      <webElementGuid>f99e7c62-2bc8-4e4a-a429-7d3513226bc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
