<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_applyall_1</name>
   <tag></tag>
   <elementGuidId>fd67ad5d-ebd3-4004-a718-9c75bc53ec39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnMoFirstSend</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnMoFirstSend']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>12ec7b74-de07-46a1-9bf1-c19664e15d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>21c47ac2-3da5-42c2-9122-dd069dad245a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnMoFirstSend</value>
      <webElementGuid>86f590b5-af5c-4d73-8dd3-b40a415deb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default pull-right btn-sm btnBlueColor</value>
      <webElementGuid>b5ca3361-7325-40d4-91aa-d592b93aa966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n-text</name>
      <type>Main</type>
      <value>paperbase_page04</value>
      <webElementGuid>40e2d254-1413-4742-b452-26874c64dc6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>本模块应用到所有合同</value>
      <webElementGuid>ae4a52e8-cb9a-42ef-a2f0-4efab6d242d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnMoFirstSend&quot;)</value>
      <webElementGuid>745cf297-0e35-4bbd-b222-ab2f22890aac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnMoFirstSend']</value>
      <webElementGuid>03ff1993-bd70-447c-a364-d85f50f69926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='addForm']/div/div[2]/div[9]/div/button</value>
      <webElementGuid>00ff1174-321e-4a07-b8d3-ad7f96ade746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::button[1]</value>
      <webElementGuid>751a8d62-909c-4149-9ee5-61feeeccb55a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='签署地'])[1]/following::button[1]</value>
      <webElementGuid>c4fc0600-f08c-4a2a-ac77-01403f8ec37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='是否为框架合同'])[1]/preceding::button[1]</value>
      <webElementGuid>b9f4de86-b487-4070-9134-5ae2e9da1cd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='是'])[1]/preceding::button[1]</value>
      <webElementGuid>5a0e3818-ac61-413d-bb8b-0ec24c21e12b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='本模块应用到所有合同']/parent::*</value>
      <webElementGuid>bee32fa1-d94e-40e4-bab0-0be84dcafe20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/button</value>
      <webElementGuid>4f8afd19-a6f6-499c-bc6b-445593ac8d60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnMoFirstSend' and (text() = '本模块应用到所有合同' or . = '本模块应用到所有合同')]</value>
      <webElementGuid>de0be8c9-423b-49c1-8cd7-828b7161e641</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
