<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_applyall_4</name>
   <tag></tag>
   <elementGuidId>848c94e5-4485-4c66-8808-2bff469d7808</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnMoFourSend']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnMoFourSend</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bc9a0f1e-d807-4a39-a6e0-8e8b313c49f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>90bf2e6c-cb6a-4f87-a61f-14210b8dcfad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnMoFourSend</value>
      <webElementGuid>c27293c8-eab8-45f3-b1fd-ce382f61318b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default pull-right btn-sm btnBlueColor</value>
      <webElementGuid>89750112-ddf2-4342-9206-6fcf102bbc3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n-text</name>
      <type>Main</type>
      <value>paperbase_page04</value>
      <webElementGuid>c5a5180e-ecbc-4e54-94ad-4637e1ab1458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>本模块应用到所有合同</value>
      <webElementGuid>876ed0bd-e656-4bd8-8075-40f5b540ab0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnMoFourSend&quot;)</value>
      <webElementGuid>b152e6b4-ce47-4af7-946e-954e683fbe11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnMoFourSend']</value>
      <webElementGuid>685929af-35bc-4c12-bc53-7c04c72ea85b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='没有获取到数据'])[1]/following::button[1]</value>
      <webElementGuid>1ed99c78-58fc-45ac-98eb-9b417faeaddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='合同类型cid'])[2]/following::button[1]</value>
      <webElementGuid>5869d51f-a348-4237-b427-1afd6fae5d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='签署审批人'])[1]/preceding::button[1]</value>
      <webElementGuid>021b4557-a023-4a28-a0b5-da080f900317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='选择'])[5]/preceding::button[1]</value>
      <webElementGuid>b1e398b2-11c1-4ac9-9599-42bc2b06a2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/button</value>
      <webElementGuid>eb14c496-671d-4f5c-acf1-2e72609106e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnMoFourSend' and (text() = '本模块应用到所有合同' or . = '本模块应用到所有合同')]</value>
      <webElementGuid>adfa963e-1a98-45f3-ad12-182e8429edfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
