<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_draftstyle_upload</name>
   <tag></tag>
   <elementGuidId>3209553f-2297-44c0-8ab0-0b27c081aae5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_easyui_combobox_i2_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_easyui_combobox_i2_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1ed6255b-a5a4-490d-9aaa-f3746c48f3f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_easyui_combobox_i2_1</value>
      <webElementGuid>5c28f5b3-61e4-4276-83e2-49fff1ad5d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combobox-item combobox-item-hover</value>
      <webElementGuid>8a877fa9-2cea-4e44-b1fd-da912e9ae99f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>自由上传合同文本</value>
      <webElementGuid>fe363a96-53b9-4d9f-a527-911813959cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_easyui_combobox_i2_1&quot;)</value>
      <webElementGuid>c46fc37e-4d33-44a0-bc66-20c50bef6381</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='_easyui_combobox_i2_1']</value>
      <webElementGuid>6b537943-730c-40f8-91e8-ca166edcfc27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='基于合同范本起草'])[1]/following::div[1]</value>
      <webElementGuid>f0dfdd85-967c-4bec-8d16-fe26e084b36e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '_easyui_combobox_i2_1', '&quot;', ')')])[1]/following::div[4]</value>
      <webElementGuid>1ca429c3-caa8-487b-9194-a088c33294f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='自由上传合同文本']/parent::*</value>
      <webElementGuid>7b999372-4aa1-4295-8075-f7a13f005cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[2]</value>
      <webElementGuid>bec9e642-f9ea-4141-bc3b-0581601a1dcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '_easyui_combobox_i2_1' and (text() = '自由上传合同文本' or . = '自由上传合同文本')]</value>
      <webElementGuid>5a9429da-e34f-4d6c-b490-59c451e5b593</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
