<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__ifmSubjectChooseModel</name>
   <tag></tag>
   <elementGuidId>434019c5-336b-45fb-be77-7edb9ff6ad4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifmSubjectChooseModel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ifmSubjectChooseModel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>fa74930a-a7f5-4c4d-bc9f-74578ff3ab94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifmSubjectChooseModel</value>
      <webElementGuid>489ce401-eaeb-437e-8a3b-c363faa3aff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ifmSubjectChooseModel</value>
      <webElementGuid>20185199-f884-42fd-b73c-04e3c145b7eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>3e53e82c-ed89-4244-8199-39a8d925da7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c2223caf-a6a0-4ed1-9f88-75797c164004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>ChoosePage/ChooseContractMCL.cshtml?companyid=&amp;contractType=&amp;exp40=China</value>
      <webElementGuid>657341f8-be7f-4151-bf91-70702e85e581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ifmSubjectChooseModel&quot;)</value>
      <webElementGuid>a2cefb7c-1e4a-417e-8171-cce3cd9cd106</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifmSubjectChooseModel']</value>
      <webElementGuid>dbaa1903-20dc-49fb-99fe-8a5edaaa6b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SubjectShowModel']/iframe</value>
      <webElementGuid>0bd2df1c-be00-4119-bcab-c42c88e18226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='选择合同范本'])[1]/following::iframe[1]</value>
      <webElementGuid>7a714361-99e6-40a2-9552-a81ea29d27a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='自由上传合同文本'])[1]/following::iframe[1]</value>
      <webElementGuid>87deb6fa-cb35-42c8-8194-6c1fc511165a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='关闭'])[2]/preceding::iframe[1]</value>
      <webElementGuid>e4bd509e-1f1a-49a2-847f-601bc1587a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='确认'])[1]/preceding::iframe[1]</value>
      <webElementGuid>fef8da9b-aef6-4dd6-b7bc-a05336c6fd37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>b3e7a9ba-0a8b-4f52-aafe-eebb27c1f812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ifmSubjectChooseModel' and @name = 'ifmSubjectChooseModel' and @src = 'ChoosePage/ChooseContractMCL.cshtml?companyid=&amp;contractType=&amp;exp40=China']</value>
      <webElementGuid>3938cc37-fcd1-4e99-86d3-774884ae5096</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
