<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_priceremark</name>
   <tag></tag>
   <elementGuidId>cbf009bc-ac51-411c-8480-5915fb276f5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_easyui_textbox_input86</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='_easyui_textbox_input86']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6ad7fe03-b2be-458c-bf9d-a55495a2b83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_easyui_textbox_input86</value>
      <webElementGuid>b28e274c-afb3-420c-880a-eddd92a2eca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-text validatebox-text</value>
      <webElementGuid>b68b0d94-0c00-481e-917e-a23d1601447d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a1ae824a-bfe6-4ff8-8049-7b0337f9d7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_easyui_textbox_input86&quot;)</value>
      <webElementGuid>ed3d2317-58e7-4512-810f-393c1cdc0cbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='_easyui_textbox_input86']</value>
      <webElementGuid>74e7895a-a11c-4689-98c0-aedfa18a8c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='priceremark']/div/span/textarea</value>
      <webElementGuid>94ef2ceb-05c4-4a13-9a31-42f31ddf15d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/span/textarea</value>
      <webElementGuid>1bf90932-47ed-41af-baa6-881aa37a36bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = '_easyui_textbox_input86']</value>
      <webElementGuid>355d481f-1077-4bde-b71e-1fc52509849a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
