<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tip_batchcontract_delete</name>
   <tag></tag>
   <elementGuidId>1bb4d0e1-48eb-4df6-ab8e-9ca5e9d5d870</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.messager-body.panel-body.panel-body-noborder.window-body > div:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='提示'])[1]/following::div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f0d45249-e68f-4c34-8b14-91830cac9fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>您将放弃本条目的批量发起，是否确认删除</value>
      <webElementGuid>24d04e84-58e2-4540-93be-283780079544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;panel-fit&quot;]/body[@class=&quot;panel-noscroll&quot;]/div[@class=&quot;panel window panel-htop messager-window&quot;]/div[@class=&quot;messager-body panel-body panel-body-noborder window-body&quot;]/div[2]</value>
      <webElementGuid>7a0224ba-c9ff-4d8a-abca-3da3add0429a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提示'])[1]/following::div[4]</value>
      <webElementGuid>3a028a29-0799-4681-b2db-a4ad77da0549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='自由上传合同文本'])[2]/following::div[7]</value>
      <webElementGuid>3ec779c0-94d8-45a9-9fb6-46ce9ac923c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='确定'])[1]/preceding::div[2]</value>
      <webElementGuid>739a019d-60dc-4794-b67a-a4dd6770be1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='取消'])[1]/preceding::div[2]</value>
      <webElementGuid>9637d048-f5a6-4ac5-8d7e-46bc74b81fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='您将放弃本条目的批量发起，是否确认删除']/parent::*</value>
      <webElementGuid>82201948-c5ed-4d9d-8ebd-08b55b6b95e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div[2]/div[2]</value>
      <webElementGuid>377db093-8202-486d-99fe-67ef923f93a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '您将放弃本条目的批量发起，是否确认删除' or . = '您将放弃本条目的批量发起，是否确认删除')]</value>
      <webElementGuid>fdcdb03c-0609-4cb6-b62d-65782bd5137e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
