<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tip_needlegalcheck</name>
   <tag></tag>
   <elementGuidId>4422fd72-6d36-48fb-8565-7c2b59abce1c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='提示'])[1]/following::div[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.messager-body.panel-body.panel-body-noborder.window-body > div:nth-of-type(2) > div:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>41ff49ab-f1f4-499d-be88-be61b59d3de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>合同编号[CON-COM-20231122-003M],请选择法务审核人进行审批</value>
      <webElementGuid>6949665d-243b-4e9a-9172-797509baee0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;panel-fit&quot;]/body[@class=&quot;panel-noscroll&quot;]/div[@class=&quot;panel window panel-htop messager-window&quot;]/div[@class=&quot;messager-body panel-body panel-body-noborder window-body&quot;]/div[2]/div[2]</value>
      <webElementGuid>3137791c-8325-4664-af8e-d4dcbcf60fb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提示'])[1]/following::div[6]</value>
      <webElementGuid>5d3c0b71-5f10-4a06-893c-dd38c3a9ccd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提交'])[2]/following::div[11]</value>
      <webElementGuid>9fb3bb07-cf1f-4a85-95e7-6d2da6c50c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='确定'])[1]/preceding::div[3]</value>
      <webElementGuid>778b6602-285a-4dc8-afe3-76fd5fb1a15b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='基于合同范本起草'])[3]/preceding::div[6]</value>
      <webElementGuid>2ecb3027-1d36-42ee-8ec3-2a794e1fe173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='合同编号[CON-COM-20231122-003M],请选择法务审核人进行审批']/parent::*</value>
      <webElementGuid>7bb1c0f7-cd41-4379-8955-772678d70133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div[2]/div[2]/div[2]</value>
      <webElementGuid>045572be-af8c-4960-9c33-e3312b200309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '合同编号[CON-COM-20231122-003M],请选择法务审核人进行审批' or . = '合同编号[CON-COM-20231122-003M],请选择法务审核人进行审批')]</value>
      <webElementGuid>57c9ea56-97e5-4856-a787-b1dccfa81a7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
