<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_vendorconsult_applythisallcontract</name>
   <tag></tag>
   <elementGuidId>bf852a70-cfbe-4b8e-87a2-f7bd37c219e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@onclick='quickFilling(0)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-2 > div.divItemBgToolbar > div.form-group.form-group-sm > span.btn.btn-default.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5700ad58-875a-4b8d-b791-8838b0c3908a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm</value>
      <webElementGuid>046df03c-bd9b-4e92-b07a-bd0735f252c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>quickFilling(0)</value>
      <webElementGuid>026006bc-46ef-4cd2-b0ed-fbdad693354b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>本模块应用到所有合同</value>
      <webElementGuid>6908e531-d806-4fb8-89b7-9365615533a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_dcd50019-fa9e-47e8-8bd2-7bedce928bb1&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-md-2&quot;]/div[@class=&quot;divItemBgToolbar&quot;]/div[@class=&quot;form-group form-group-sm&quot;]/span[@class=&quot;btn btn-default btn-sm&quot;]</value>
      <webElementGuid>e129e4cf-a448-481f-b2cb-00b5383190de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@onclick='quickFilling(0)']</value>
      <webElementGuid>e39124c3-710a-4d1c-84a9-0c4d2dbadb8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_dcd50019-fa9e-47e8-8bd2-7bedce928bb1']/div[8]/div[3]/div/div/span</value>
      <webElementGuid>808cae10-dfed-4df3-b4f8-1967f3953ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='签署审批人'])[1]/following::span[1]</value>
      <webElementGuid>5ddbc3a0-1359-40d0-ab6f-4ee71ee459d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提交'])[2]/following::span[1]</value>
      <webElementGuid>af21a90b-8881-47bf-a9df-4cf10ea26eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='审批意见'])[1]/preceding::span[1]</value>
      <webElementGuid>33c05eb5-8758-454d-acca-33623e4ee11a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO.0002'])[1]/preceding::span[1]</value>
      <webElementGuid>592e29ad-a821-4539-a7f3-15a18cfa7593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='本模块应用到所有合同']/parent::*</value>
      <webElementGuid>a7e79f50-725e-4890-a5e5-92c24d66b67b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span</value>
      <webElementGuid>dd65a1ff-90ec-4e82-ba84-e22756acc7cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '本模块应用到所有合同' or . = '本模块应用到所有合同')]</value>
      <webElementGuid>5c2a0d05-8382-45bd-a091-7263d71a4c94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
