<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_1</name>
   <tag></tag>
   <elementGuidId>5bfaed63-e296-4d1e-8ad0-d66d0624c363</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.modal-body.form-horizontal > iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a8690fc8-0062-4fea-b74a-ac9f503b1d1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>f925dc8e-bc02-4bb0-977a-309976215127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>f005f05f-ad45-40bb-a59c-ede9f0aefd85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>29c5a0dc-2532-4584-aedc-623f86cee9b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DASPortal/OrgCommonChoose/Page/OrgCommonChoose.aspx?chooseValCarID=3a4a66b6-8923-4b62-aef0-8dfb4bb109d7&amp;notChooseValCarID=b8c1cae6-59b4-413e-a7ba-a5293ae48116&amp;mcwId=e56640d7-9e98-48df-aacd-0d40a0b763e5&amp;mcmwId=1991fcca-02ac-4e52-9d76-db7cc881af50&amp;pageType=groupuser&amp;chkTabsNum=0&amp;isCascadeUser=false&amp;isCascadeDpt=false&amp;isCascadeJob=false&amp;isPath=false&amp;isGrpName=false&amp;groupCids=57d953c2-ec51-4cda-a661-b01b00c3580d</value>
      <webElementGuid>2e969be0-a259-4e2e-8a9f-c84361536347</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/div[@class=&quot;modal fade DachkjModel in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body form-horizontal&quot;]/iframe[1]</value>
      <webElementGuid>24531788-66b1-4261-9336-5c405df0ebec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>823e1c48-dc26-4cae-bf9b-6c0e1f3a8eed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/DASPortal/OrgCommonChoose/Page/OrgCommonChoose.aspx?chooseValCarID=3a4a66b6-8923-4b62-aef0-8dfb4bb109d7&amp;notChooseValCarID=b8c1cae6-59b4-413e-a7ba-a5293ae48116&amp;mcwId=e56640d7-9e98-48df-aacd-0d40a0b763e5&amp;mcmwId=1991fcca-02ac-4e52-9d76-db7cc881af50&amp;pageType=groupuser&amp;chkTabsNum=0&amp;isCascadeUser=false&amp;isCascadeDpt=false&amp;isCascadeJob=false&amp;isPath=false&amp;isGrpName=false&amp;groupCids=57d953c2-ec51-4cda-a661-b01b00c3580d']</value>
      <webElementGuid>87d9293a-b031-4bd3-8b36-d1a2873ffd66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
