<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_signapprover</name>
   <tag></tag>
   <elementGuidId>9ff92619-9a38-4dd3-95bf-97175a45e859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='spr_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#spr_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d7c81eb7-cbdf-4ab2-9dd6-487545ce4b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1071466c-7da5-448f-8cf4-3cbcdb3ccb92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>clickSpr('spr_0')</value>
      <webElementGuid>359ce708-8f90-4174-bb5e-0b444149679c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>e7a0fa8e-412c-41e6-9cda-36367de53088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>spr_0</value>
      <webElementGuid>8ec59d00-9e05-4ac4-891b-0ca38306855e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spr_0&quot;)</value>
      <webElementGuid>01a11a1f-b693-41db-83ef-c2ea2929a807</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='spr_0']</value>
      <webElementGuid>b814530d-7f4b-49c6-b308-3433e333b08e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_dcd50019-fa9e-47e8-8bd2-7bedce928bb1']/div[8]/div[2]/input</value>
      <webElementGuid>76c304ec-65b9-4b04-b45e-a8ca67c0f75e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/input</value>
      <webElementGuid>becdebf3-1c6a-47ac-9068-022d02cbc0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = 'spr_0']</value>
      <webElementGuid>b3cfa904-2bf7-49fd-91b7-0e978ad5f448</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
