<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vendorconsultapproveremark</name>
   <tag></tag>
   <elementGuidId>101d837f-4ab5-41f4-be81-497ebe97a7c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='spyj_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#spyj_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>41cc4120-7e6a-424a-a69b-7c892883fce0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3c11848e-c7fd-4635-9e46-a5df5af748da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>0729c582-9121-4d04-9b29-b4ac38b6fe98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>spyj_0</value>
      <webElementGuid>d76e1db3-82d6-4409-9657-49ff7c65be3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spyj_0&quot;)</value>
      <webElementGuid>7583d51e-efb8-4fc9-a1f5-0d771fd3e28e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='spyj_0']</value>
      <webElementGuid>910e76ad-09da-4205-8bd0-84020be855f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_dcd50019-fa9e-47e8-8bd2-7bedce928bb1']/div[10]/div/input</value>
      <webElementGuid>55fbf26b-e1ed-4898-ba2b-9d28f85f5168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>c6eddcae-4426-40cc-8d76-3feb53b033c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'spyj_0']</value>
      <webElementGuid>e821969c-5433-466a-993d-57e17df54681</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
