<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__chk</name>
   <tag></tag>
   <elementGuidId>e935c44e-87a8-4f3f-bd25-9ec0b465558a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='d4a69abd-18bc-435e-9199-e25662e2b350']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.chk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1780961e-3746-49e4-8c8f-ea0f2b263de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>cacd6b12-4b9f-421d-9ba5-fe7aa053f1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>65461763-b5b3-483e-b400-240728690e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>d4a69abd-18bc-435e-9199-e25662e2b350</value>
      <webElementGuid>05217107-bfeb-4dc9-a561-f862f5c0061c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbGrid&quot;)/tbody[@class=&quot;hidden_768&quot;]/tr[1]/td[@class=&quot;chkBox&quot;]/input[@class=&quot;chk&quot;]</value>
      <webElementGuid>f9df1433-f15c-4f7e-b70e-cec5205fd511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/NeedToDoTask/Batchvendorconsult_page/iframe_1</value>
      <webElementGuid>f9d9fa2e-d548-4a62-8485-1de576b1c7a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='d4a69abd-18bc-435e-9199-e25662e2b350']</value>
      <webElementGuid>8b645255-6a34-41c8-9469-e7bacdb5225d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbGrid']/tbody/tr/td[2]/input</value>
      <webElementGuid>ab73e168-e8d0-4956-a646-6d974e9722eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>989a106b-447c-4dcb-bf13-656e55296902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>9408d60c-1fdc-4352-bf20-337ae0f23bcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
