<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_returndraft</name>
   <tag></tag>
   <elementGuidId>730860f5-4aa1-47ea-a2fd-c4c2a2cfebe4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='spjg_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;spjg_0&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>40fc07a4-737c-45d6-b6ee-b38e3ac392f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f1eb55a7-ac3f-4c63-9f92-eac4e75895f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>spjg_0</value>
      <webElementGuid>26ad9c8d-8918-49a5-8c2b-dd0ea6fd3061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5f46f54c-e583-403d-b272-dd778e20993c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_dcd50019-fa9e-47e8-8bd2-7bedce928bb1&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-md-2&quot;]/input[1]</value>
      <webElementGuid>42fa39c4-b80c-4cb4-8a92-c6acfd72746f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='spjg_0']</value>
      <webElementGuid>68a72296-cae2-4d08-8519-85bfa4c6c6d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_dcd50019-fa9e-47e8-8bd2-7bedce928bb1']/div[8]/div/input</value>
      <webElementGuid>9be06de3-8cf0-4893-a1b5-24088beaa594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>14159d3c-8490-478e-a5de-20e583bb091b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'spjg_0']</value>
      <webElementGuid>b08b3234-232f-4812-832b-fac1df8e3de4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
