<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_contractcount</name>
   <tag></tag>
   <elementGuidId>f217653d-64bb-48e3-a5bd-ef6907d04ff8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='spanCount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#spanCount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3abc22eb-7d40-4f04-8e3c-1c2366952aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>spanCount</value>
      <webElementGuid>6270c3ce-6ad3-4cc2-8472-92c45c074c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>共计 2 合同条目,目前已展示 2 条！</value>
      <webElementGuid>c680e39f-a9a3-4af3-92fd-4485b2f604ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spanCount&quot;)</value>
      <webElementGuid>ce76309b-09cd-4e00-88cc-27c0fc56ca0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='spanCount']</value>
      <webElementGuid>983f5645-4bf3-4aad-a367-ceae8c35def6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divItemBg']/div/div[2]/span</value>
      <webElementGuid>7afc44c4-f9dc-40e3-b80c-8ad231cc1bf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提交'])[1]/following::span[1]</value>
      <webElementGuid>ffeddf31-312f-4845-8fda-fddab662f091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='批量提交【外部磋商】'])[1]/following::span[4]</value>
      <webElementGuid>1c9376f3-712a-4f08-a041-ea706ddce7cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO.0001'])[1]/preceding::span[1]</value>
      <webElementGuid>16e0d219-8848-49c0-8e5c-c6a435f0c279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='申请人'])[1]/preceding::span[4]</value>
      <webElementGuid>4dc225be-7d60-4976-b4f5-c9c7063ee8ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='共计 2 合同条目,目前已展示 2 条！']/parent::*</value>
      <webElementGuid>8ea1d619-4c0a-4515-aef0-8c4866491cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/span</value>
      <webElementGuid>cf5cd897-62c9-4bd1-87c8-048836159264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'spanCount' and (text() = '共计 2 合同条目,目前已展示 2 条！' or . = '共计 2 合同条目,目前已展示 2 条！')]</value>
      <webElementGuid>9664bbd3-2557-4ac4-844a-954ceb68ce78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
