<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_dgsubmit</name>
   <tag></tag>
   <elementGuidId>c28a2d88-264f-4054-9342-8d6dd631c33c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#spanSubmit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='spanSubmit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a2995d75-cdd6-47e4-a646-ac55b7af5a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm</value>
      <webElementGuid>75e89f80-9bb6-4b1a-b6d0-72d718f9c837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>spanSubmit</value>
      <webElementGuid>046a1f15-d4bf-4ba0-a919-da27e4c23bf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>Submit()</value>
      <webElementGuid>1daed86c-cfbb-48c3-829e-c0c65ae75050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>提交</value>
      <webElementGuid>7b28f555-cd45-4cec-ae24-7cedf92f359f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spanSubmit&quot;)</value>
      <webElementGuid>1581bc58-ef48-456a-a28c-91e98b957285</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='spanSubmit']</value>
      <webElementGuid>26faa33e-7986-4595-95cc-2ab0371f0a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divItemBg']/div/div/div[2]/span[3]</value>
      <webElementGuid>df8afed4-e681-4478-8888-4e58261e27e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='对方经办人批量设置'])[1]/following::span[1]</value>
      <webElementGuid>db18d1f3-1a81-4a8d-abe3-ecf684cd6af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='查询'])[1]/following::span[2]</value>
      <webElementGuid>3290178f-727f-4312-be86-348587cbc263</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO.0001'])[1]/preceding::span[2]</value>
      <webElementGuid>27b7caee-27bb-4ec1-a05a-eb9a53602c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='提交']/parent::*</value>
      <webElementGuid>f86514c7-8cb6-460e-af72-b49bae7ad36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]</value>
      <webElementGuid>6b3f97bb-5270-4e18-b1d1-549f358e6d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'spanSubmit' and (text() = '提交' or . = '提交')]</value>
      <webElementGuid>018b6125-9551-4ff6-a159-2942535fe2fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
