<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_sginprocessapplyallcontract</name>
   <tag></tag>
   <elementGuidId>fdfc31fb-5899-45d8-88fd-9e4c47b37bce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@onclick='quickFillYysx(0)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8b605d46-ee61-495d-876e-af720f5c6d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm</value>
      <webElementGuid>5111fee0-c253-4c19-94e7-96fa1713f4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>quickFillYysx(0)</value>
      <webElementGuid>0397d748-fe15-4f38-899a-cd0ac1d6915e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>本模块应用到所有合同</value>
      <webElementGuid>814daa19-feb4-4189-8a1d-a570afd06125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_0c73927c-577c-407f-b7c0-d782a4ef3f3c&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;divItemBgToolbar&quot;]/div[@class=&quot;form-group form-group-sm&quot;]/span[@class=&quot;btn btn-default btn-sm&quot;]</value>
      <webElementGuid>c50478ca-0022-48bb-8778-0fd807d7bca8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@onclick='quickFillYysx(0)']</value>
      <webElementGuid>b2f35fb7-e282-474b-92f7-9b0af7d26ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_0c73927c-577c-407f-b7c0-d782a4ef3f3c']/div[10]/div[4]/div/span</value>
      <webElementGuid>56d71bbb-c01f-4e68-885f-18c4eb657492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/following::span[1]</value>
      <webElementGuid>2999930e-9ff7-4acf-a8af-406b59e59db7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='用印页数'])[1]/following::span[2]</value>
      <webElementGuid>5ace8d0e-41e3-4c08-8d48-d8724d69ae98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='合同主体文件'])[1]/preceding::span[1]</value>
      <webElementGuid>2968569f-12ac-41ef-a7bd-f95edf81f0c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='基于合同范本起草'])[1]/preceding::span[1]</value>
      <webElementGuid>9e06e140-6571-4616-a1b9-8868240f923a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[4]/div/span</value>
      <webElementGuid>4fda0280-e7d6-45e5-9950-3afb540921c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '本模块应用到所有合同' or . = '本模块应用到所有合同')]</value>
      <webElementGuid>7d2e2d5e-ebe6-427c-bece-133c8e73991e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
