<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__finalDraftApprovalFrame</name>
   <tag></tag>
   <elementGuidId>19c6ea1f-b129-4460-b2a2-262f7d4565ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#finalDraftApprovalFrame</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='finalDraftApprovalFrame']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9731c622-9027-49d1-9e7b-70d5497f0599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>finalDraftApprovalFrame</value>
      <webElementGuid>a866b6a8-f2d2-43e1-b429-70575665492f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>finalDraftApprovalFrame</value>
      <webElementGuid>fc395630-d890-4c91-afb9-245cc8d9afde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>5d4a784d-c98e-43a6-8cb1-10409508eb8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Page/childPage/ConTractDraftApproval.cshtml</value>
      <webElementGuid>2d8153e2-5b0c-4b61-9e58-606475c80dba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;finalDraftApprovalFrame&quot;)</value>
      <webElementGuid>b2360dde-c65c-4861-be55-5f96d7ba1cb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='finalDraftApprovalFrame']</value>
      <webElementGuid>e4dbfca5-e1d2-46c6-b81d-e239bad91ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>0518f76a-a45f-406d-8292-247c18cdda13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'finalDraftApprovalFrame' and @name = 'finalDraftApprovalFrame' and @src = '../Page/childPage/ConTractDraftApproval.cshtml']</value>
      <webElementGuid>a872232d-b8dd-49a1-9597-21a55362698b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
