<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_sginprocess</name>
   <tag></tag>
   <elementGuidId>b4897ab5-71e7-435f-a6c0-3b9c9a4f4289</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='signingProcess_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#signingProcess_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2fd3fa9e-3bfe-4e63-af61-9991b156674c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>7cb19110-5729-45a7-8c3e-bad591917d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>signingProcess_0</value>
      <webElementGuid>1aa1e5a4-85b2-4d29-b80a-f7787225c8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signingProcess_0</value>
      <webElementGuid>22b55932-f26c-4e09-b652-0f7b0fdf8b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>电子合同签署流程纸质合同签署流程</value>
      <webElementGuid>609afc09-41df-4035-b737-774ff5a7c796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signingProcess_0&quot;)</value>
      <webElementGuid>2f4325fc-1ebf-49db-ada3-012e4861eb86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='signingProcess_0']</value>
      <webElementGuid>3b24cbd5-8078-4000-ad6a-a8f68584ed03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divCol_signingProcess_0']/select</value>
      <webElementGuid>6b7aab9e-6369-42e3-9764-7daa6e956432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='签署流程'])[1]/following::select[1]</value>
      <webElementGuid>4d6d8724-9204-4107-a644-1bb5519535e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='本模块应用到所有合同'])[1]/following::select[1]</value>
      <webElementGuid>5d3d2b60-82ce-4540-aa56-ba2c16e46182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::select[1]</value>
      <webElementGuid>8e67faf7-028a-4168-bc36-76d030624c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='印章类型'])[1]/preceding::select[1]</value>
      <webElementGuid>de2b2d4b-208f-4611-921c-ec1159ffdc78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>8347f973-5fd2-490f-a2f2-f099250ab2ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'signingProcess_0' and @id = 'signingProcess_0' and (text() = '电子合同签署流程纸质合同签署流程' or . = '电子合同签署流程纸质合同签署流程')]</value>
      <webElementGuid>67cdf7f8-8961-4e57-b199-7b4547597e36</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
