<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_applycontent_row1</name>
   <tag></tag>
   <elementGuidId>4d0f1f36-1e81-4f77-b79c-1430e97ca7eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='desc_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#desc_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>04f67a7f-b677-4bbb-a4b5-85924fd8831e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>desc_0</value>
      <webElementGuid>42ee2df5-251c-49be-b35e-e85b17e82b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>autotest外部磋商1701832232-1000.00-2023/11/30-Commercial</value>
      <webElementGuid>49802cbe-8b29-4e5f-a265-eb2f36fc3398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desc_0&quot;)</value>
      <webElementGuid>22960d71-b1c7-4291-902a-a93bb8808a1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='desc_0']</value>
      <webElementGuid>baf807df-2fdb-463f-85d5-d1227127c81c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divCol_desc_0']/p/span</value>
      <webElementGuid>2fc3e04f-f0d9-42bf-817f-86d2b2dd6394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='申请事项'])[1]/following::span[1]</value>
      <webElementGuid>b5b7e359-3859-43c6-a031-6d1d23d64f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CON-COM-20231122-002M'])[1]/following::span[1]</value>
      <webElementGuid>28b7bc89-8fb2-4489-a2c8-7ae9e2dd6e3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='单据号'])[1]/preceding::span[1]</value>
      <webElementGuid>2b7583c7-0f04-4c8d-bd4b-d9050afdef23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DZHTQS-20231130-008'])[1]/preceding::span[1]</value>
      <webElementGuid>d18188d8-cd89-4591-b96b-69a48366ea62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='autotest外部磋商1701832232-1000.00-2023/11/30-Commercial']/parent::*</value>
      <webElementGuid>8fe2b675-f5ba-4114-99a6-e223148846fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/p/span</value>
      <webElementGuid>fcf617a5-e795-4a36-afb7-690766426523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'desc_0' and (text() = 'autotest外部磋商1701832232-1000.00-2023/11/30-Commercial' or . = 'autotest外部磋商1701832232-1000.00-2023/11/30-Commercial')]</value>
      <webElementGuid>2d3fcf54-bad4-4ddc-a806-368f28607b68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
