<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_applycontent_row2</name>
   <tag></tag>
   <elementGuidId>ac10087b-38af-4083-a5c5-fcc4b2e59fc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='desc_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#desc_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bbfe0cf3-575f-4b8a-b460-2c80f96b8b24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>desc_1</value>
      <webElementGuid>111a7408-2216-49d7-9cd6-6222284ca145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>autotest外部磋商1701832232-2500.00-2023/11/30-Commercial</value>
      <webElementGuid>0f84258f-a604-4ff8-a74a-cf8e4f8dc375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;desc_1&quot;)</value>
      <webElementGuid>b85b274a-89ea-41e0-b36a-6fac76ce467f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='desc_1']</value>
      <webElementGuid>a2794330-f675-4c22-a7df-520acb2b1b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divCol_desc_1']/p/span</value>
      <webElementGuid>d2a393e1-dcce-4f37-9ba1-0023ffd3c5ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='申请事项'])[2]/following::span[1]</value>
      <webElementGuid>c13853ca-1053-4422-81be-2a50f6cbef48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CON-COM-20231122-001M'])[1]/following::span[1]</value>
      <webElementGuid>bed48c0c-3d20-4633-ab37-df508fc4f598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='单据号'])[2]/preceding::span[1]</value>
      <webElementGuid>44dcac96-df24-41e9-b5c2-4737979d842d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DZHTQS-20231130-007'])[1]/preceding::span[1]</value>
      <webElementGuid>ac0a2d66-f389-4c18-abe3-b64b242cb652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='autotest外部磋商1701832232-2500.00-2023/11/30-Commercial']/parent::*</value>
      <webElementGuid>e4dc68f4-8957-49c1-b914-b2cc5c153300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/p/span</value>
      <webElementGuid>3a04094c-c8eb-4f0b-a7f5-97302c6be575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'desc_1' and (text() = 'autotest外部磋商1701832232-2500.00-2023/11/30-Commercial' or . = 'autotest外部磋商1701832232-2500.00-2023/11/30-Commercial')]</value>
      <webElementGuid>9b1ccd7e-aaf3-457b-bad8-2616dbc96afb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
