<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_internalconsult_applyallcontract_row1</name>
   <tag></tag>
   <elementGuidId>08cffc15-4e6a-40c3-a3d0-91137cd21830</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@onclick='quickFilling(0)']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#divCol_cz_0 > div.divItemBgToolbar > div.form-group.form-group-sm > span.btn.btn-default.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4a70268a-380c-45e4-8d9e-33b8994e3da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm</value>
      <webElementGuid>e190428e-7506-48c2-8051-668da3e312a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>quickFilling(0)</value>
      <webElementGuid>8be3756c-d9bb-4308-8322-b1e9a480fcb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>本模块应用到所有合同</value>
      <webElementGuid>3166996c-ded7-48e5-a450-e4727bf8f6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divCol_cz_0&quot;)/div[@class=&quot;divItemBgToolbar&quot;]/div[@class=&quot;form-group form-group-sm&quot;]/span[@class=&quot;btn btn-default btn-sm&quot;]</value>
      <webElementGuid>9a5c99f7-1708-4aea-b720-26b699c1e122</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@onclick='quickFilling(0)']</value>
      <webElementGuid>60a0818c-2236-42b4-b33d-6c189425b9d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divCol_cz_0']/div/div/span</value>
      <webElementGuid>1b668f63-6a58-4387-bec5-6ca83fd6270a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='审批意见'])[1]/following::span[1]</value>
      <webElementGuid>1fa38c6a-7d19-43e6-a727-e7fe42a36641</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='退回至'])[1]/following::span[1]</value>
      <webElementGuid>24f7b792-1c95-4bef-8c72-b4f1ced83f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO.0002'])[1]/preceding::span[1]</value>
      <webElementGuid>59905ab9-1477-4315-8e89-7775aa913962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='申请人'])[2]/preceding::span[4]</value>
      <webElementGuid>8c368605-6e79-4d1a-8194-9ce492c79bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='本模块应用到所有合同']/parent::*</value>
      <webElementGuid>1e6752f4-69ef-4e0a-8b4b-c6d542664aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span</value>
      <webElementGuid>75ceca46-3edf-42b7-964f-0dcae0591e8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '本模块应用到所有合同' or . = '本模块应用到所有合同')]</value>
      <webElementGuid>029bf193-13e6-44e8-9156-4d995b72a3cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
