<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_batchcontractcount</name>
   <tag></tag>
   <elementGuidId>dde9e8b2-3575-4b73-9e23-1928a17c36a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='spanCount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#spanCount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2788d44b-309e-4e5d-8b58-b3f4195bf402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>spanCount</value>
      <webElementGuid>399a5e88-e5c9-47ee-b7e5-fdf55e72c865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>共计  2  条合同条目，目前已展示  2  条</value>
      <webElementGuid>88bc4158-e575-433b-a006-4ba906fc72bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spanCount&quot;)</value>
      <webElementGuid>f7ebcd07-92e2-4034-a52d-a5c51da98e1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='spanCount']</value>
      <webElementGuid>719faab8-f9d5-4b15-9eab-8c4701b37620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divItemBg']/div/div[2]/span</value>
      <webElementGuid>65364d8a-b04d-404d-8078-588606f4b12b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提交'])[1]/following::span[1]</value>
      <webElementGuid>cda544d6-d80e-4972-9811-eb238102654e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='刷新'])[1]/following::span[2]</value>
      <webElementGuid>c1e69606-612f-4ce7-9dc4-7b64d1ed5b01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO.0001'])[1]/preceding::span[1]</value>
      <webElementGuid>85a9078e-150f-42a0-a11c-a14f5be2561a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='申请人'])[1]/preceding::span[4]</value>
      <webElementGuid>8b57148e-bfc9-4247-867e-efb9f0ad4183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>3219866a-a3d8-4e88-b9ca-9cfdcadbb67e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'spanCount' and (text() = '共计  2  条合同条目，目前已展示  2  条' or . = '共计  2  条合同条目，目前已展示  2  条')]</value>
      <webElementGuid>3a876d6b-163f-472d-a400-68297e6f691a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
