<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_4 input tax, China</name>
   <tag></tag>
   <elementGuidId>57f4e258-d31d-4e73-8a02-150642af55f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_easyui_combobox_i23_8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_easyui_combobox_i23_8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>edd3ba68-6759-4f5f-a579-60196df82a6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_easyui_combobox_i23_8</value>
      <webElementGuid>2390aaba-f099-4956-88ce-43744029f7df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combobox-item combobox-item-hover</value>
      <webElementGuid>140e68f1-095f-480a-993b-2193e26ce80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>4% input tax, China</value>
      <webElementGuid>89df3eda-fa76-4484-a90b-af6debf8068c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_easyui_combobox_i23_8&quot;)</value>
      <webElementGuid>a8b59e4b-bd46-46e3-b04b-924171fbdd43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_modify_page/iframe__ifm_1</value>
      <webElementGuid>444f4ed5-1f2c-489c-83ec-a206622513f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='_easyui_combobox_i23_8']</value>
      <webElementGuid>f9ea175f-48e3-417b-9a64-0b9eed70d335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='六'])[7]/following::div[14]</value>
      <webElementGuid>da5781de-6e36-4f19-b673-c67615c06258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='五'])[7]/following::div[14]</value>
      <webElementGuid>37dea26a-2552-423c-ab7f-87365f04ce90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VAT Input 10%'])[1]/preceding::div[15]</value>
      <webElementGuid>ebfc8f31-9e7c-4281-a4f9-40343da8d42f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import VAT 10%'])[1]/preceding::div[16]</value>
      <webElementGuid>004917cf-00c6-42c7-98a3-3e6769d9de9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='4% input tax, China']/parent::*</value>
      <webElementGuid>087c29cb-3ab5-4c3b-ab18-109743096c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/div/div[9]</value>
      <webElementGuid>a3714523-1183-4772-aa02-a6a5c587cc2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '_easyui_combobox_i23_8' and (text() = '4% input tax, China' or . = '4% input tax, China')]</value>
      <webElementGuid>62eac2ed-1ebc-4e34-95c8-a86abade24b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
