<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__ifm</name>
   <tag></tag>
   <elementGuidId>463a96a7-c878-411c-97c4-f271ca5d277c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ifm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b7be7739-55f1-45c0-a20b-27c9ba84c49d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifm</value>
      <webElementGuid>2c473ee1-9384-4a08-a0ce-eb7b31c97549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>19e38545-ad1e-416b-8c31-e4bea3e950d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>5e2619e7-2c82-404a-842a-93da7fe6cddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ifm</value>
      <webElementGuid>3e689d34-0591-4301-a61e-1ab31bab3614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DASContractFast/BWProcess/BWContractDAG/Page/DatapoolN.cshtml?mainTone=Index&amp;strUserUltCode=BPM/28070907&amp;CurrentLanguage=zh-CN&amp;rnd=0.5784686231508511</value>
      <webElementGuid>ed8d43c4-8163-4cf2-af4c-9bbee61745d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-header-fixed&quot;]/div[@class=&quot;page-container row-fluid&quot;]/div[@class=&quot;divContent&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;ifmBg&quot;]/div[@class=&quot;col-md-12&quot;]/iframe[@id=&quot;ifm&quot;]</value>
      <webElementGuid>4298c411-6a8c-4cae-93ae-d0e33397b01b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifm']</value>
      <webElementGuid>baa6d3d6-1be3-46ff-94ab-9784aa4c6325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>9e724684-1dd3-4a79-80a2-424bfb37aed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ifm' and @name = 'ifm' and @src = '/DASContractFast/BWProcess/BWContractDAG/Page/DatapoolN.cshtml?mainTone=Index&amp;strUserUltCode=BPM/28070907&amp;CurrentLanguage=zh-CN&amp;rnd=0.5784686231508511']</value>
      <webElementGuid>e3437874-c8b1-4189-8136-975fcc367ff8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
