<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkdate_nextinput</name>
   <tag></tag>
   <elementGuidId>0560ec2e-7d43-4b44-98c9-36ae96f22dd6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_easyui_textbox_input79</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_easyui_textbox_input79']/following-sibling::input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>854e6a3f-19a9-405c-a3d8-093ee816681a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_easyui_textbox_input79</value>
      <webElementGuid>c26c3c25-6614-44d0-bd4e-364154494196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dbe9c22c-d8ea-47f7-8f3c-b145ff670c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-text validatebox-text validatebox-readonly</value>
      <webElementGuid>fe98a899-68ea-4ba7-a1d2-898f944af7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>61d800f1-b3cb-4b1d-9e6a-df3d4843ed48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_easyui_textbox_input79&quot;)</value>
      <webElementGuid>5f00da62-976d-4a27-bda4-b9e57c86a795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_modify_page/iframe__ifm_1</value>
      <webElementGuid>43b292ab-68b9-4a8b-8461-5a6cbf2a30cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_easyui_textbox_input79']/following-sibling::input</value>
      <webElementGuid>dce57636-4706-4383-bf2a-282d9878a00c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='daginfo']/div[21]/div/span/input/following-sibling::input</value>
      <webElementGuid>4666284f-5e97-4358-99fb-24d2a1b58c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div/span/input/following-sibling::input</value>
      <webElementGuid>d2c9582e-ecf6-4aa5-b04c-5008412f76c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_easyui_textbox_input79' and @type = 'text']/following-sibling::input</value>
      <webElementGuid>b1922710-bc3d-444b-aef1-79e4c0ef78c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
