<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_deleteallchecked</name>
   <tag></tag>
   <elementGuidId>3e3eb154-075f-4f51-a60a-7bf841f5e6b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnDeleteAll</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnDeleteAll']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4713922c-86d5-4798-93b2-37d9118b6e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5ee1a865-6bd3-4ea9-9f5a-630eabb3eb8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDeleteAll</value>
      <webElementGuid>c0830605-060c-4c3f-8d25-f68c27f77d24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btnSearch btn-default pull-right btn-sm btnBlueColor</value>
      <webElementGuid>7f3ccec9-0f4c-41b7-bb06-a49c55f66933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>clearAll()</value>
      <webElementGuid>275f2076-c7b8-44fa-96cb-0b4a6a97b1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>全部删除</value>
      <webElementGuid>58853827-c634-4ef0-a0de-3d2a8587ba72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnDeleteAll&quot;)</value>
      <webElementGuid>527899c4-5f3a-4f90-bf5c-fa177f1932f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/iframe__ifm</value>
      <webElementGuid>bcf785d2-2ca9-467b-bcfe-1897c470efad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnDeleteAll']</value>
      <webElementGuid>9a87078c-d87e-42bb-88f5-96c5233062d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MCLSearchToolBar']/button</value>
      <webElementGuid>cc3f5630-e673-4929-a3ba-26d79ada6339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[2]'])[1]/following::button[1]</value>
      <webElementGuid>2f8c1703-0f03-496c-8bc5-bee19e4a7e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='批量发起合同'])[1]/preceding::button[1]</value>
      <webElementGuid>3bc42cc6-bbc1-48ee-8084-6f1739244f6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='序号'])[1]/preceding::button[3]</value>
      <webElementGuid>45eee78a-ee73-4839-9437-4235e9ec9880</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='全部删除']/parent::*</value>
      <webElementGuid>e5dd4bfd-c1e0-4d9e-b68c-70f981e55343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button</value>
      <webElementGuid>16e601ab-44e0-4a01-b609-8ef80fe06d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnDeleteAll' and (text() = '全部删除' or . = '全部删除')]</value>
      <webElementGuid>4890f833-7c94-494d-a587-82178c1adce7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
