<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_deletecontract_row1</name>
   <tag></tag>
   <elementGuidId>beef2c11-8910-4af4-9c04-34625ba83dac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ff283cdf-a714-4b11-a762-bc56a1446fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>close</value>
      <webElementGuid>84f3526a-1733-449f-bcc7-40d4157e525f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>DeleteData('1511bbe6-2593-42ce-ae4b-f00ebbc89fcf')</value>
      <webElementGuid>f27c1143-101f-4b01-b023-1fab547e1d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectedDt_datagrid-row-r6-2-0&quot;)/td[1]/div[@class=&quot;close&quot;]</value>
      <webElementGuid>19819052-469d-4c3a-b498-9bd9427788af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/iframe__ifm</value>
      <webElementGuid>8825f1d6-ed4c-4172-b31b-722c7f24f322</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick=&quot;DeleteData('1511bbe6-2593-42ce-ae4b-f00ebbc89fcf')&quot;]</value>
      <webElementGuid>c805dd4b-87bb-4c23-9f47-5be13c144484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='selectedDt_datagrid-row-r6-2-0']/td/div[2]</value>
      <webElementGuid>f9926a9d-24e0-4a21-b668-81dcb48889d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div[2]</value>
      <webElementGuid>043ee5b4-e489-49bf-96d7-db5318f4d57f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
