<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_batchcontract</name>
   <tag></tag>
   <elementGuidId>bb9a0653-4363-47c9-8bc1-915186cd2197</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnBatch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnBatch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>108fa8c2-1367-44ab-9105-cec55747f474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2069eae7-d0ef-4912-a615-291bfde4216c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnBatch</value>
      <webElementGuid>68c329e4-4992-417b-82c1-08d899d40f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btnSearch btn-default pull-right btn-sm btnBlueColor</value>
      <webElementGuid>5de08f36-8a74-4639-98fa-e342a009d17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>BatchContract()</value>
      <webElementGuid>71211eae-4c8a-4d22-b116-8d8b0895e956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>批量发起合同</value>
      <webElementGuid>d647cf4a-de11-45f6-b49c-195917507b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnBatch&quot;)</value>
      <webElementGuid>3bb24bce-02dd-4329-bf72-42a556e54adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/iframe__ifm</value>
      <webElementGuid>9df82d78-f36d-4273-9ea1-cb54821b1bda</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnBatch']</value>
      <webElementGuid>0caf5eec-22a2-4374-a4e9-01e94976d654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MCLSearchToolBar']/button[2]</value>
      <webElementGuid>76a5baa3-4e8f-48c0-bf59-7bd8fc630317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='全部删除'])[1]/following::button[1]</value>
      <webElementGuid>2584211e-1bd4-4ff2-bad3-828aff9be8b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[2]'])[1]/following::button[2]</value>
      <webElementGuid>0fff5da2-029c-4a4f-94db-32e68393af29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='序号'])[1]/preceding::button[2]</value>
      <webElementGuid>e8a0f3c6-656f-4930-9605-58d2ef4be6c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAG_ID'])[1]/preceding::button[2]</value>
      <webElementGuid>05792f66-50b6-482a-b18f-82198e946300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='批量发起合同']/parent::*</value>
      <webElementGuid>6cc1d6c8-dee8-4630-b61a-371e5d0aa17e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/button[2]</value>
      <webElementGuid>a90eafe5-7091-4db0-9f95-dcef1ccb025c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnBatch' and (text() = '批量发起合同' or . = '批量发起合同')]</value>
      <webElementGuid>83750e18-4c30-4620-9dc5-09620868b22b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
