<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_advancedsearch_close</name>
   <tag></tag>
   <elementGuidId>bc3402db-bf6f-4c4b-bdc9-ab9003654307</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.easyui-panel.panel-body.panel-body-noheader > button.btn.btn-default.pull-right.btn-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='complexQuery']/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c12da69d-8781-40d8-ae34-2c0ab053529b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default pull-right btn-sm</value>
      <webElementGuid>f2c12973-4622-4de3-b063-cbfbd05c8580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>关闭</value>
      <webElementGuid>81eab68f-37de-4f97-8a45-f91dedd79e3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;complexQuery&quot;)/div[@class=&quot;panel panel-htop easyui-fluid&quot;]/div[@class=&quot;easyui-panel panel-body panel-body-noheader&quot;]/button[@class=&quot;btn btn-default pull-right btn-sm&quot;]</value>
      <webElementGuid>45c3a9e7-d40a-4e80-84d6-966b5e688b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/iframe__ifm</value>
      <webElementGuid>c4a45211-089c-49bd-b092-f2ed37e02097</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='complexQuery']/div/div/button</value>
      <webElementGuid>f3b02c92-1324-4af3-885d-fa2406f18f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='公司代码'])[1]/following::button[1]</value>
      <webElementGuid>175f1d58-d504-4ef1-aa16-714b8fe44d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='签署实体'])[1]/following::button[1]</value>
      <webElementGuid>018e6e8a-4110-4029-aae6-9aff7e3afb39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='检索'])[1]/preceding::button[1]</value>
      <webElementGuid>2a893ee5-fca6-4753-9e34-85412b1cc2c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='已选数据'])[1]/preceding::button[2]</value>
      <webElementGuid>70e887c3-ab10-4610-a677-5e69551c6b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='关闭']/parent::*</value>
      <webElementGuid>d9dbeb92-ad49-4388-8eed-b21adc34b49a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/button</value>
      <webElementGuid>b048ae39-72d5-4945-b836-22c443cd33cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '关闭' or . = '关闭')]</value>
      <webElementGuid>88fc8ad3-7bf8-4036-844e-9e52a21d5897</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
