<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_datasource</name>
   <tag></tag>
   <elementGuidId>d9b83b56-6582-4e5e-9bb1-ba3323d9ac36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='DAGGrid_datagrid-row-r1-2-0']/td[24]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DAGGrid_datagrid-row-r1-2-0 > td:nth-of-type(24) > div.datagrid-cell.DAGGrid_datagrid-cell-c1-T_DAG_DATA_SOURCE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5780493b-8f7a-4790-978c-eb626ecba2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datagrid-cell DAGGrid_datagrid-cell-c1-T_DAG_DATA_SOURCE</value>
      <webElementGuid>1a6b2030-1353-42da-9ef2-b281b66b2ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>手动录入</value>
      <webElementGuid>199cf6d9-9e5c-4937-b15c-b64bd4849731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DAGGrid_datagrid-row-r1-2-0&quot;)/td[24]/div[@class=&quot;datagrid-cell DAGGrid_datagrid-cell-c1-T_DAG_DATA_SOURCE&quot;]</value>
      <webElementGuid>e5f97d01-1b77-460d-92f2-49d2d1869c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/iframe__ifm</value>
      <webElementGuid>5a52834b-ebcb-4583-aeeb-44af2f31455d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='DAGGrid_datagrid-row-r1-2-0']/td[24]/div</value>
      <webElementGuid>09ba6cc2-3064-4051-a8e2-011db2a40cb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INPUT'])[1]/following::div[1]</value>
      <webElementGuid>10d3b6e6-5d69-44ec-980b-9ae35f379062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='实物类'])[1]/following::div[4]</value>
      <webElementGuid>ca7c29db-32b2-4124-89f0-010907013d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DRAFT'])[1]/preceding::div[1]</value>
      <webElementGuid>f9ff7fe1-d5ad-45d3-bdc8-1ee62a711a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='草稿'])[1]/preceding::div[2]</value>
      <webElementGuid>6862b1d2-891b-4032-8648-0977377cd2a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='手动录入']/parent::*</value>
      <webElementGuid>9ded0307-2962-40c0-aeb3-e09986f73d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[24]/div</value>
      <webElementGuid>538588d9-66df-4c75-a2a7-147d044a1432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '手动录入' or . = '手动录入')]</value>
      <webElementGuid>8cd437f7-8d68-4f14-98db-6b174bc227fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
