<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_tip_nodata</name>
   <tag></tag>
   <elementGuidId>3ddc030f-90e7-4cd9-9c06-e4c2f1b718ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.datagrid-empty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='List']/div/div/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fffbdb0c-fa12-4bd4-b6a5-06f8a62c49a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datagrid-empty</value>
      <webElementGuid>5be80ceb-b535-4a20-9990-f462649363e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>暂无数据</value>
      <webElementGuid>24857387-2d8b-42b1-b670-812a41957559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;List&quot;)/div[@class=&quot;panel datagrid panel-htop easyui-fluid&quot;]/div[@class=&quot;datagrid-wrap panel-body panel-body-noheader&quot;]/div[@class=&quot;datagrid-view&quot;]/div[@class=&quot;datagrid-empty&quot;]</value>
      <webElementGuid>31234d93-8b10-482d-88f6-3d823538af2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/iframe__ifm</value>
      <webElementGuid>11f1d32b-67c0-4ac0-8860-d8e0479c5a04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='List']/div/div/div/div[3]</value>
      <webElementGuid>d13d28b4-82b0-4713-8a45-c2e74caf0878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='是否共享金额'])[1]/following::div[34]</value>
      <webElementGuid>072ea689-2c6a-4058-9b5b-59a74c9bd12a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提示'])[1]/following::div[35]</value>
      <webElementGuid>5b65bd0a-ca94-4f27-a97a-9a3a16a5fc09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='第'])[1]/preceding::div[3]</value>
      <webElementGuid>3a74ce72-169e-4bc7-b207-a310c814ea0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='共0页'])[1]/preceding::div[3]</value>
      <webElementGuid>394653c6-8991-42e9-af64-3a4b0b93be9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='暂无数据']/parent::*</value>
      <webElementGuid>37c0fdbc-a4d2-4e2e-81dc-f0305da44fca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[3]</value>
      <webElementGuid>ae5e04df-04de-48a9-80f0-c05129dd07c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '暂无数据' or . = '暂无数据')]</value>
      <webElementGuid>9fb5a3f2-a532-48dc-80ff-adad1c0a9344</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
