<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ck-4</name>
   <tag></tag>
   <elementGuidId>35780d1e-af69-487c-b89e-65a2d2ce1c8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ck&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='ck'])[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24f5d9ac-8f67-48d4-9016-abbeddb92759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bfc747ab-a759-4c3d-ba79-5615c78b5c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ck</value>
      <webElementGuid>6e7215ba-22ce-42b5-8a18-a24f812496fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DAG-COM-20231117-002M_datagrid-row-r3-2-0&quot;)/td[1]/div[@class=&quot;datagrid-cell-check&quot;]/input[1]</value>
      <webElementGuid>d530bbc0-063e-431e-a86c-ad4e60baa607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/iframe__ifm</value>
      <webElementGuid>658a4f0a-84a7-4e1f-9847-6ce0d4392f89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='ck'])[4]</value>
      <webElementGuid>43fa6524-7b65-4356-a1a2-c5959081d66d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='DAG-COM-20231117-002M_datagrid-row-r3-2-1']/td/div/input)[4]</value>
      <webElementGuid>971f8026-f2f8-4b45-a668-042b2973a01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>(//td/div/div/div/div/div/div/div[2]/div[2]/table/tbody/tr/td/div/input)[4]</value>
      <webElementGuid>67cc8c0c-a5f9-4b8b-add2-92fc9ee97d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>(//input[@type = 'checkbox' and @name = 'ck'])[4]</value>
      <webElementGuid>ec9a350a-4758-4ec4-8dbc-676bd0079b3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
