<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DAG_search</name>
   <tag></tag>
   <elementGuidId>20c3f5a4-b4f9-4eae-8b51-38e5f7b57100</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.selech</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ff7d706-036d-4bac-91c5-8fd9d9445be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30695d37-a03d-49aa-a86c-9a12aa9b652a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control selech</value>
      <webElementGuid>b593c170-fc33-47dc-b324-7a0da98b2524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DAG_ID,DAG描述,DAG负责人,供应商名称,供应商主数据编号,源DAG号</value>
      <webElementGuid>3f1b9aec-8ba0-4b4d-b186-f4d6282908f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>DAG_ID,DAG描述,DAG负责人,供应商名称,供应商主数据编号,源DAG号</value>
      <webElementGuid>777f013c-cdcb-42e9-beab-66c6c0735425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchBox&quot;)/div[@class=&quot;input-group pull-right group searchBox input-group-sm&quot;]/input[@class=&quot;form-control selech&quot;]</value>
      <webElementGuid>a29e5863-aba4-4353-8ba1-44fe10c0d2fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/iframe__ifm</value>
      <webElementGuid>9ad9ee9b-a07a-41ca-95cd-fff3d17e73b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>31f1ffcd-98c5-48ef-8743-fd6b66bebe72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchBox']/div[2]/input</value>
      <webElementGuid>a328cec0-cef4-492a-b233-2ec938160f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>95cb1a07-86dd-41ea-81f8-40692b49e578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'DAG_ID,DAG描述,DAG负责人,供应商名称,供应商主数据编号,源DAG号' and @title = 'DAG_ID,DAG描述,DAG负责人,供应商名称,供应商主数据编号,源DAG号']</value>
      <webElementGuid>b0224c89-661e-49e8-9e5f-00a27b3ce9c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
