<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__cb</name>
   <tag></tag>
   <elementGuidId>f05261e4-a344-4531-a2af-c198155bd32b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cb']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cb&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10c5b0aa-424b-4f23-881e-80920a403605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>33644be7-e759-4fc4-8156-7795452607be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cb</value>
      <webElementGuid>813b4cde-f9d6-4978-b031-d472575915ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DAGGrid_datagrid-row-r2-2-0&quot;)/td[1]/div[@class=&quot;datagrid-cell-check&quot;]/input[1]</value>
      <webElementGuid>69494d06-4ae1-47fa-b595-09c2a1efa3eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/iframe__ifm</value>
      <webElementGuid>325f7fc5-add2-456b-8236-e195111bb8b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cb']</value>
      <webElementGuid>9268cbe1-ff39-4b9d-9e1c-dd308b74ad52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='DAGGrid_datagrid-row-r2-2-0']/td/div/input</value>
      <webElementGuid>ee27b06a-29a8-4c45-85d6-ab3383a4db58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/div/input</value>
      <webElementGuid>4d0359e6-19d8-4ffe-a312-4e7e820e3c10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'cb']</value>
      <webElementGuid>46fba430-6b9e-4a4e-94b6-16ea40d7cbe3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
