<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ck-5</name>
   <tag></tag>
   <elementGuidId>c9e2a369-2341-4e92-b489-f7634277e6d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ck&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='ck'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>daa48d73-ea48-45e1-b7b8-a7ca29a4264f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fa5d8090-5e87-4736-902e-99b4ebe29e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ck</value>
      <webElementGuid>eb149c56-a675-4b2b-b861-38a8cd3c09b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DAG-COM-20231117-002M_datagrid-row-r3-2-0&quot;)/td[1]/div[@class=&quot;datagrid-cell-check&quot;]/input[1]</value>
      <webElementGuid>299dd2a2-e3b5-4ec6-b05a-50a99ae6e44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/iframe__ifm</value>
      <webElementGuid>01931b1e-1bd2-49ab-9c8a-ed5a04212266</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='ck'])[5]</value>
      <webElementGuid>e0d7bcde-ee6e-4e96-ac34-1b9385983186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='DAG-COM-20231117-002M_datagrid-row-r3-2-1']/td/div/input)[5]</value>
      <webElementGuid>0d510eba-ea05-4383-b3e1-4be84683c694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>(//td/div/div/div/div/div/div/div[2]/div[2]/table/tbody/tr/td/div/input)[5]</value>
      <webElementGuid>dd4d1ec7-45c1-4333-89b2-3a43858f2955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>(//input[@type = 'checkbox' and @name = 'ck'])[5]</value>
      <webElementGuid>a573923c-ad74-450e-a012-f6fc68f1c3d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
