<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_checkeddata_0</name>
   <tag></tag>
   <elementGuidId>a3a478ae-2a18-4c76-b692-d9b7ab2dc07a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#spanCount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='spanCount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3b7df2a8-4780-4e0d-b74d-17dbd6542c7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>spanCount</value>
      <webElementGuid>291e99bf-6657-4d78-9ac2-f62ed3ae1465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>[0]</value>
      <webElementGuid>2a27ea67-5921-4410-855f-3b0e3caa409f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DAG&quot;)/div[@class=&quot;panel layout-panel layout-panel-west panel-htop layout-split-west&quot;]/div[@class=&quot;panel-header&quot;]/div[@class=&quot;panel-title&quot;]/span[@id=&quot;spanCount&quot;]</value>
      <webElementGuid>c88865b9-ad27-479a-b782-108d8b830d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/iframe__ifm</value>
      <webElementGuid>bd7024e8-374b-4b0b-9220-791cc972c005</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='spanCount']</value>
      <webElementGuid>c7eb619c-8b2a-480b-8d60-16e2633c3ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DAG']/div[2]/div/div/span</value>
      <webElementGuid>f5d1f958-13b9-4f83-9efb-ecbc0c272829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='高级检索'])[1]/following::span[2]</value>
      <webElementGuid>e354d235-cead-47c5-b2d2-cc8bd4178858</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='全部删除'])[1]/preceding::span[1]</value>
      <webElementGuid>c6f4f3c7-8f12-4ece-af3f-edd44bfcaba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='批量发起合同'])[1]/preceding::span[1]</value>
      <webElementGuid>24253ffe-b0cb-44a6-ba13-72f0e27e6f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='[0]']/parent::*</value>
      <webElementGuid>355dbbf1-fc4d-4f12-b459-464a99f0c466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span</value>
      <webElementGuid>897ed458-ef9c-41a5-a526-f8c3c02cc645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'spanCount' and (text() = '[0]' or . = '[0]')]</value>
      <webElementGuid>60b35bd4-10b8-4f0e-87bf-84f44de4fbcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
