<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_datagrid-row-expand</name>
   <tag></tag>
   <elementGuidId>51c1886c-0355-404c-ba41-0c5c2c3b152d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.datagrid-row-expander.datagrid-row-expand</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='DAGGrid_datagrid-row-r2-1-0']/td[2]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dc91a8a4-563d-4cc2-9628-bfc30785d04b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datagrid-row-expander datagrid-row-expand</value>
      <webElementGuid>9a164d44-c509-4ce3-bf58-02c53115c69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DAGGrid_datagrid-row-r2-1-0&quot;)/td[2]/div[@class=&quot;datagrid-cell undefined&quot;]/span[@class=&quot;datagrid-row-expander datagrid-row-expand&quot;]</value>
      <webElementGuid>aba4be29-0295-416b-855d-d95dcd0a3665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/iframe__ifm</value>
      <webElementGuid>390b2997-3022-4ea2-8879-62c5ec551399</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='DAGGrid_datagrid-row-r2-1-0']/td[2]/div/span</value>
      <webElementGuid>546f11a5-60fe-43b4-9e7d-3c6dcf595daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr/td[2]/div/span</value>
      <webElementGuid>1185215d-6fb3-4845-b9cd-280562ed21c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
