<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tip_contracttransfer_nopermission</name>
   <tag></tag>
   <elementGuidId>c48e210e-7b73-4f68-8485-d27a1fedaf19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.messager-body.panel-body.panel-body-noborder.window-body > div:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='提示'])[2]/following::div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c808f45d-32ca-43b3-bc49-70036c1cb9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DAG-CAP-20221026-001M,您没有操作权限</value>
      <webElementGuid>96a62a53-dc3f-41c3-9e6f-b81b6bd12a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;panel-fit&quot;]/body[@class=&quot;panel-noscroll&quot;]/div[@class=&quot;panel window panel-htop messager-window&quot;]/div[@class=&quot;messager-body panel-body panel-body-noborder window-body&quot;]/div[2]</value>
      <webElementGuid>f1c7d21e-4e30-4045-8e7d-7ef144d8c40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/iframe__ifm</value>
      <webElementGuid>36043958-ebe5-4e38-8596-c72e8c447e8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提示'])[2]/following::div[4]</value>
      <webElementGuid>b918289d-ee5b-48d7-9724-06c09724ee1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='显示1到1,共1记录'])[2]/following::div[39]</value>
      <webElementGuid>80bc1d46-4300-4d59-ab2d-808887ba9d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='确定'])[1]/preceding::div[2]</value>
      <webElementGuid>0a6b83c1-f71d-4f93-acb4-fe31bbdd4b07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DAG-CAP-20221026-001M,您没有操作权限']/parent::*</value>
      <webElementGuid>1417020e-69ec-4bac-9b66-b986eb7e3e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div[2]/div[2]</value>
      <webElementGuid>61ff796a-aef6-4604-bde6-321edd43b6ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'DAG-CAP-20221026-001M,您没有操作权限' or . = 'DAG-CAP-20221026-001M,您没有操作权限')]</value>
      <webElementGuid>086e6a33-3b00-48f2-8110-61aa8b17c6f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
