<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_submitorreject</name>
   <tag></tag>
   <elementGuidId>769d214e-6c97-42b3-a0d7-481101b970fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnSend']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnSend</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0491684b-f454-4b68-89a4-ed04226348b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6a84e596-1934-4d81-be53-89cd538442d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSend</value>
      <webElementGuid>5f489354-5c60-4286-a033-453913b4c3f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default pull-left btn-sm btnBlueColor</value>
      <webElementGuid>2f7441a4-67c8-42da-906e-c2a390c08979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n-text</name>
      <type>Main</type>
      <value>paprobasicmsg_submit1</value>
      <webElementGuid>f364cbc0-57f9-4061-a3ab-8474a9018a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>提交or退回</value>
      <webElementGuid>f5d2ebae-f243-4362-9a4f-74d3866cae9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSend&quot;)</value>
      <webElementGuid>1b681a7a-04b4-4c81-b6b9-84ee26130947</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnSend']</value>
      <webElementGuid>d3ab5459-bbc2-42ff-9072-e0734c8ab022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='单据号:OA-DZHTQS-20231130-008'])[1]/following::button[1]</value>
      <webElementGuid>e87a4b47-f36a-4939-b1ff-c1230edd813c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='合同签署流程'])[2]/following::button[1]</value>
      <webElementGuid>1e2b9dba-1a50-46ee-8152-cb3caf6bba87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='关闭'])[1]/preceding::button[1]</value>
      <webElementGuid>c34c2f64-153a-42a2-88c1-c861fdcdfa35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='起草'])[1]/preceding::button[2]</value>
      <webElementGuid>a32e4387-64c5-4a0f-99dc-c50fa83f70b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='提交or退回']/parent::*</value>
      <webElementGuid>c95470ef-60a2-4ebd-a363-d0a3f3082c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>0783ee8c-351c-4ab0-b9b4-e3acc322b863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnSend' and (text() = '提交or退回' or . = '提交or退回')]</value>
      <webElementGuid>0fd25aa8-60d5-495f-b7e6-ee30be72dd02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
