<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_batchcontract_submit</name>
   <tag></tag>
   <elementGuidId>4acc9ca8-a982-4ae4-98d6-80355babc475</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnFastSend</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnFastSend']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1eb15d15-48ce-4e8d-8274-2b878e43b94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5eea7e20-eb45-407e-a237-0c38b01893f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnFastSend</value>
      <webElementGuid>648eb424-b96a-451b-a54a-3103501c8caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default pull-left btn-sm btnBlueColor</value>
      <webElementGuid>19ca1579-5ea7-48f3-b62a-eaae5910e4c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n-text</name>
      <type>Main</type>
      <value>dag_submit</value>
      <webElementGuid>701ea4bb-b782-4fde-bd01-49c2c7c7eda6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>提交</value>
      <webElementGuid>0d37b587-c469-48ef-b31a-9053daedf9de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnFastSend&quot;)</value>
      <webElementGuid>c93ed3ae-77f5-4d24-b4fc-6e9a760c8ef8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnFastSend']</value>
      <webElementGuid>fb8da1f8-1ad2-4f06-ab4e-5c9e72253dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myTimeLine']/button[3]</value>
      <webElementGuid>ff4e67e3-c3b7-4fea-be96-34a190b4a4b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='保存'])[1]/following::button[1]</value>
      <webElementGuid>841a6909-1e49-4d62-a4b2-61398a9876d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='对方经办人批量设置'])[1]/following::button[2]</value>
      <webElementGuid>0edaf972-cf6d-4782-88ff-3bc8878bf83d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='关闭'])[1]/preceding::button[1]</value>
      <webElementGuid>3ae15e10-bb7b-413b-b405-93f7e7977130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='合同表格'])[1]/preceding::button[2]</value>
      <webElementGuid>445c40b8-8a4f-47ca-88ad-264cb908dbf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='提交']/parent::*</value>
      <webElementGuid>3d19f94c-2c7d-44ae-abe0-6dfab9e2d723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>352ce746-d3d0-4033-b118-be9acf726d56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnFastSend' and (text() = '提交' or . = '提交')]</value>
      <webElementGuid>2be67c68-f3ed-457d-9dda-7bfa3026e0b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
