<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_approver_select</name>
   <tag></tag>
   <elementGuidId>d8963194-e654-472d-b452-eff2c510f8b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.textbox-button.textbox-button-right.l-btn.l-btn-small.l-btn-focus > span.l-btn-left > span.l-btn-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zxlddiv']/div/span/a/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a718f5c3-8b3a-48fb-b5b2-a2b3905b8797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>l-btn-text</value>
      <webElementGuid>fed24083-f732-4f4d-9c54-afccaf12d945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>选择</value>
      <webElementGuid>50060e28-06b4-46e3-8691-b0265441bca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zxlddiv&quot;)/div[@class=&quot;col-md-4&quot;]/span[@class=&quot;textbox easyui-fluid&quot;]/a[@class=&quot;textbox-button textbox-button-right l-btn l-btn-small l-btn-focus&quot;]/span[@class=&quot;l-btn-left&quot;]/span[@class=&quot;l-btn-text&quot;]</value>
      <webElementGuid>dbbfb258-554a-4ad5-bd06-fd8603b47973</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zxlddiv']/div/span/a/span/span</value>
      <webElementGuid>13d93579-63b0-4d6b-9133-d76fbe853a63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='签署审批人'])[1]/following::span[3]</value>
      <webElementGuid>99cde198-6005-40ca-975f-fc9303f11d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='批量发起摘要'])[1]/following::span[3]</value>
      <webElementGuid>5e721793-ee63-4460-9f17-085613188405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[18]/preceding::span[1]</value>
      <webElementGuid>f9c8d934-5499-41fa-9b5d-5b33335fd466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='批量发起摘要'])[2]/preceding::span[2]</value>
      <webElementGuid>837c28b6-6270-474f-ad43-f81b21c7de71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div[2]/div/div/span/a/span/span</value>
      <webElementGuid>8ebe4f27-59a0-41d8-826a-b560bd1e47ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '选择' or . = '选择')]</value>
      <webElementGuid>d8646159-5862-4cce-af5f-fa670087df5c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
