<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>0bd5a7c6-6bb1-4377-8918-6ce562895478</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div/div[2]/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>12bbc87c-37a2-4bc4-92b0-df475aed0d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>8ef99001-8240-4082-a7e5-a9f66314f121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>fdd4af50-04ab-44a4-b5ad-4bbbf07e9878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>223dced1-4c93-4b9c-9e1c-6564f5833389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DASPortal/OrgCommonChoose/Page/OrgCommonChoose.aspx?chooseValCarID=b3674c28-ba35-469e-86c1-d3b5d257962b&amp;notChooseValCarID=8c0139bc-df71-4c14-99d8-c423904d5cf8&amp;mcwId=7a60d0c6-5efd-48ab-a8e2-18ade95ba304&amp;mcmwId=e3cf62de-af83-4fa3-b131-f14de16cfd10&amp;pageType=groupuser&amp;chkTabsNum=0&amp;isCascadeUser=false&amp;isCascadeDpt=false&amp;isCascadeJob=false&amp;isPath=false&amp;isGrpName=false&amp;groupCids=57d953c2-ec51-4cda-a661-b01b00c3580d</value>
      <webElementGuid>d385035b-02ad-4b21-bf84-03d2846ff028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;panel-fit&quot;]/body[@class=&quot;panel-noscroll modal-open&quot;]/div[@class=&quot;modal fade DachkjModel in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body form-horizontal&quot;]/iframe[1]</value>
      <webElementGuid>8c60d6f0-7597-4ba7-be73-99306299ad76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/iframe</value>
      <webElementGuid>03a174ac-3a9b-49bb-bd23-4db8d2e14523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/DASPortal/OrgCommonChoose/Page/OrgCommonChoose.aspx?chooseValCarID=b3674c28-ba35-469e-86c1-d3b5d257962b&amp;notChooseValCarID=8c0139bc-df71-4c14-99d8-c423904d5cf8&amp;mcwId=7a60d0c6-5efd-48ab-a8e2-18ade95ba304&amp;mcmwId=e3cf62de-af83-4fa3-b131-f14de16cfd10&amp;pageType=groupuser&amp;chkTabsNum=0&amp;isCascadeUser=false&amp;isCascadeDpt=false&amp;isCascadeJob=false&amp;isPath=false&amp;isGrpName=false&amp;groupCids=57d953c2-ec51-4cda-a661-b01b00c3580d']</value>
      <webElementGuid>517b26f2-d15e-44ce-b2f2-95fefd93adf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
