<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__chk</name>
   <tag></tag>
   <elementGuidId>ec78bff7-f148-452d-ab49-15655133f4c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.chk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='d4a69abd-18bc-435e-9199-e25662e2b350']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dee508e9-ebe7-4483-a3f3-f80d024feaed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>34fec9fe-1fe5-43ab-b49e-6a9687304bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>1f780160-842b-4da4-9b0e-0c38b739d7f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>d4a69abd-18bc-435e-9199-e25662e2b350</value>
      <webElementGuid>5300c9d8-b7f2-4e54-9dfa-45efb100bd9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbGrid&quot;)/tbody[@class=&quot;hidden_768&quot;]/tr[1]/td[@class=&quot;chkBox&quot;]/input[@class=&quot;chk&quot;]</value>
      <webElementGuid>5bd722f6-f360-4ed8-a7a6-e1058b65414a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/ContractBatchSignProcess_Page/Submit_page/iframe</value>
      <webElementGuid>37e7d5a0-68a5-4984-b7b5-2790e8d56f08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='d4a69abd-18bc-435e-9199-e25662e2b350']</value>
      <webElementGuid>60cb0040-00e5-4cdc-a47b-d118bb2e185e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbGrid']/tbody/tr/td[2]/input</value>
      <webElementGuid>7f6c68cc-0e25-4043-af50-36ac18cc0285</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>011c32e8-2e3e-48ba-a31f-eaa5c9c7a8f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>b83e6258-7e5f-4f60-9604-6a31469cd0b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
