<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_batchsummary</name>
   <tag></tag>
   <elementGuidId>9dd2bc55-ae4e-4dad-a1b5-b062ef706d9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_easyui_textbox_input2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='_easyui_textbox_input2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>bc6f4040-0f57-4cd6-ae59-1138e3de371d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_easyui_textbox_input2</value>
      <webElementGuid>631161f8-0e0f-469b-b683-1edd45b3e045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-text validatebox-text</value>
      <webElementGuid>5c98cd77-3f92-4fad-a59d-a3afb506c1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>99224099-7e3a-4445-90eb-88f3b85b358b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_easyui_textbox_input2&quot;)</value>
      <webElementGuid>33ede341-2515-4f24-a3d4-fc3060c823cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='_easyui_textbox_input2']</value>
      <webElementGuid>362a2a52-b658-49b1-b630-5d148de66f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FastAppSummary']/div[2]/div/span/textarea</value>
      <webElementGuid>f8b04e44-d33b-422c-80b3-d3e03e2fa0ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/textarea</value>
      <webElementGuid>3ef9b9a7-597d-4d38-8668-df134de609cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = '_easyui_textbox_input2']</value>
      <webElementGuid>32907bdf-f830-4616-92e4-92a924cbabd1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
