<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tip_plzcheck</name>
   <tag></tag>
   <elementGuidId>5e47d34b-7796-452a-9bf3-86aef2dd0042</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.messager-body.panel-body.panel-body-noborder.window-body > div:nth-of-type(2) > label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='提示'])[1]/following::label[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>afcc030d-4ff8-40d0-8c09-4a972957fb76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>后台校验合同文本关键字，校验结果请到“我的任务”>>“批量处理日志”>>“盖章关键字检查记录”菜单中查看</value>
      <webElementGuid>2bf5e0b7-faec-4467-800b-8e08ea17b462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;panel-fit&quot;]/body[@class=&quot;panel-noscroll&quot;]/div[@class=&quot;panel window panel-htop messager-window&quot;]/div[@class=&quot;messager-body panel-body panel-body-noborder window-body&quot;]/div[2]/label[1]</value>
      <webElementGuid>fc3a832b-7227-4f97-81ef-28604e3693d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提示'])[1]/following::label[1]</value>
      <webElementGuid>cd7e927e-07b0-4a77-b33c-24334ff73801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提交'])[2]/following::label[1]</value>
      <webElementGuid>93b3142e-fdc4-43f8-9354-08765489826a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='确定'])[1]/preceding::label[1]</value>
      <webElementGuid>0150ac61-ea46-41ea-ae37-cb8037473eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='后台校验合同文本关键字，校验结果请到“我的任务”>>“批量处理日志”>>“盖章关键字检查记录”菜单中查看']/parent::*</value>
      <webElementGuid>cb475b32-54b1-4c93-9154-42e732636d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div[2]/div[2]/label</value>
      <webElementGuid>103421ba-ed73-4003-88c4-f60f055d82c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '后台校验合同文本关键字，校验结果请到“我的任务”>>“批量处理日志”>>“盖章关键字检查记录”菜单中查看' or . = '后台校验合同文本关键字，校验结果请到“我的任务”>>“批量处理日志”>>“盖章关键字检查记录”菜单中查看')]</value>
      <webElementGuid>28ec787f-3581-4abf-a26e-a0131f06b6a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
