<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__ifm_1_1</name>
   <tag></tag>
   <elementGuidId>d5a7d150-0ddd-485d-a107-a91e6928f5c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>61966e84-a50a-480b-94b3-d9b944bb24d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>325ccb3b-2286-44b9-9599-3d6b152d91a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>b7a36ba1-7c24-4f07-a0f6-75d4aeba8316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>border</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5c9d45f1-218d-4f11-93a6-98c02185bdc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DASPortal/OrgCommonChoose/Page/OrgCommonChoose.aspx?chooseValCarID=303a5493-5333-469a-811e-3e8274a381ce&amp;notChooseValCarID=4d1cc742-de6c-415a-abab-4890f5d0d6de&amp;mcwId=3e259554-02f4-4e37-9144-16a975626701&amp;mcmwId=c53cf55d-2d40-4a84-9842-637fbe83152e&amp;pageType=dpttreeuser&amp;chkTabsNum=0&amp;isCascadeUser=false&amp;isCascadeDpt=false&amp;isCascadeJob=false&amp;isPath=false&amp;isGrpName=false</value>
      <webElementGuid>8286f3b6-da17-4a82-b448-1cd29eb9024a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;panel-fit&quot;]/body[@class=&quot;panel-noscroll modal-open&quot;]/div[@class=&quot;modal fade DachkjModel in&quot;]/div[@class=&quot;modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body form-horizontal&quot;]/iframe[1]</value>
      <webElementGuid>2fa086aa-6104-4075-b2a9-5c5c3a4c5b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAGtransfer_page/iframe__ifm_1</value>
      <webElementGuid>c3287189-0738-43fb-8faa-f5f8b489d182</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>53cc1ba6-6c16-4fa9-a4ce-d505cf9c645f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = '/DASPortal/OrgCommonChoose/Page/OrgCommonChoose.aspx?chooseValCarID=303a5493-5333-469a-811e-3e8274a381ce&amp;notChooseValCarID=4d1cc742-de6c-415a-abab-4890f5d0d6de&amp;mcwId=3e259554-02f4-4e37-9144-16a975626701&amp;mcmwId=c53cf55d-2d40-4a84-9842-637fbe83152e&amp;pageType=dpttreeuser&amp;chkTabsNum=0&amp;isCascadeUser=false&amp;isCascadeDpt=false&amp;isCascadeJob=false&amp;isPath=false&amp;isGrpName=false']</value>
      <webElementGuid>99b9b2ae-1dba-4db9-96f7-04380978a692</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
