<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__ifm_1</name>
   <tag></tag>
   <elementGuidId>67d1c2dc-d259-4eaa-8bec-ecfc0da651ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ifm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>fa495966-a7af-432c-aa99-15d71ccde89e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifm</value>
      <webElementGuid>53fd1000-daab-4450-9fc3-7de85556f6b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ifm</value>
      <webElementGuid>248209de-6288-4f02-85b0-8808e4d8306e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Datadetail.cshtml?type=transfer&amp;model=dag&amp;cid=28070907&amp;dagcid=3d03b8c7-90cb-4590-9f89-752aa0e75efa</value>
      <webElementGuid>4b69c563-52e9-4718-a2f4-cf65bc1f4618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>12af6216-51a1-4b53-9331-3b133804497f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7a790063-8b69-499c-88e9-6799f6d9c0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ifm&quot;)</value>
      <webElementGuid>32128fa9-0fd3-46db-ab24-c8c652ec13b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAGtransfer_page/iframe__ifm</value>
      <webElementGuid>72e4648f-339a-4c39-9423-92089d14c45b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifm']</value>
      <webElementGuid>b0639af7-b60f-4f01-b25b-8945b69540ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>068dcef8-2772-42fc-8cd6-64e46b21f26a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ifm' and @name = 'ifm' and @src = 'Datadetail.cshtml?type=transfer&amp;model=dag&amp;cid=28070907&amp;dagcid=3d03b8c7-90cb-4590-9f89-752aa0e75efa']</value>
      <webElementGuid>f31d5d42-8ab6-4600-9d60-bf2a27307d87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
