<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_numinfo_contractstartdate</name>
   <tag></tag>
   <elementGuidId>a496a227-10c4-4aad-a6fc-eb9fa9ba7404</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[contains(text(),'今天')])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>75a3c898-49ad-446d-9244-221b1e2f83ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datebox-button-a</value>
      <webElementGuid>1afd1f8f-8d8a-4214-9d07-919eff1e4e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>38480513-ab65-468f-bf5d-2d20fe868ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datebox-button-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>51b78119-9ab2-4746-ae86-9eec34748b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>今天</value>
      <webElementGuid>b4038ea4-b8b7-4df4-81e7-3678349c4c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;panel-fit&quot;]/body[@class=&quot;panel-noscroll&quot;]/div[@class=&quot;panel combo-p panel-htop&quot;]/div[@class=&quot;combo-panel panel-body panel-body-noheader&quot;]/div[@class=&quot;datebox-button&quot;]/table[1]/tbody[1]/tr[1]/td[1]/a[@class=&quot;datebox-button-a&quot;]</value>
      <webElementGuid>eae0c503-90d7-4209-8124-9223c4859a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>49004ee0-76a9-414e-ac0e-8b37b4bd766b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'今天')])[2]</value>
      <webElementGuid>798f3afa-5887-45d1-bd9d-8c9512b51b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='六'])[6]/following::a[1]</value>
      <webElementGuid>8ca2659a-6f4e-4acf-8944-e90e1550208d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='五'])[6]/following::a[1]</value>
      <webElementGuid>8acd10b0-5933-4fbf-a256-cb21357fc32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='关闭'])[2]/preceding::a[1]</value>
      <webElementGuid>45f6dbb3-5221-4b31-ad9b-851f22281a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='十一月 2023'])[7]/preceding::a[2]</value>
      <webElementGuid>a4554061-c162-4e10-9eb0-b1b73be6871e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[38]</value>
      <webElementGuid>531246ff-158a-4883-a3ca-8738467d22e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div/div[2]/table/tbody/tr/td/a</value>
      <webElementGuid>abe86378-f7d2-44f5-b8a2-e57fc6b8b301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = '今天' or . = '今天')]</value>
      <webElementGuid>82ad1a6f-d83d-4f7a-a82d-6c00cda7d290</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
