<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_numinfo_add</name>
   <tag></tag>
   <elementGuidId>f3eeb521-06ca-4ef9-986c-b2dfcda7225d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#create > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='create']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>362f2772-6bcc-47af-aac1-e3cf0d9e8441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n-text</name>
      <type>Main</type>
      <value>dag_create</value>
      <webElementGuid>306aef12-1dcd-4954-93bc-e38964c330a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>新增</value>
      <webElementGuid>360f7bae-dbd6-4a99-9d1b-28b07b522aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;create&quot;)/span[1]</value>
      <webElementGuid>3d83fd67-ed8f-4c47-8b7a-63af665385a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>2b87d3fa-1840-4633-97ee-470e978eb41a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='create']/span</value>
      <webElementGuid>e135f302-e954-492f-883c-3fcc8693145b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='审核日期'])[1]/following::span[3]</value>
      <webElementGuid>6e9fa851-b07d-41cc-a5e5-e5d0fbd024e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='开始日期'])[1]/following::span[5]</value>
      <webElementGuid>e238d773-9dba-4934-a729-d1818155ff70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='删除'])[1]/preceding::span[1]</value>
      <webElementGuid>a60b2286-0404-44f7-9868-27503bd22d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CID'])[1]/preceding::span[2]</value>
      <webElementGuid>858bd8d1-7b72-4f2c-a624-13cee3b39fb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='新增']/parent::*</value>
      <webElementGuid>eefda8de-291d-4086-8354-0663f36a70aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>0fce9e4e-81d9-4cb7-8920-d08a2b7f311e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '新增' or . = '新增')]</value>
      <webElementGuid>6f529786-cc15-4601-a626-565c3a9a8ad2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
