<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_zhaobiaofile_upload</name>
   <tag></tag>
   <elementGuidId>f4315124-1a87-4d33-8417-3619baceda3d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#upload > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='upload']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c46908a6-d6e8-4c44-b578-377fddc34c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n-text</name>
      <type>Main</type>
      <value>dag_upload</value>
      <webElementGuid>8e045f56-8a4b-4651-a9ad-3fe76bfb6363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>上传</value>
      <webElementGuid>6b30dfa2-cc18-471b-bcc8-08ea4af89e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;upload&quot;)/span[1]</value>
      <webElementGuid>b063764d-f341-4ad9-8415-e3470cb7173e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>77dc20f2-bb07-472a-a661-ddd2fe2c65bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='upload']/span</value>
      <webElementGuid>a06d5232-725e-41c6-a2ec-03deef03106d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='显示0到0,共0记录'])[1]/following::span[1]</value>
      <webElementGuid>3273d42a-ec26-48c8-9e4e-4061fd65cde5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='共0页'])[1]/following::span[10]</value>
      <webElementGuid>e6ed0ff9-2457-4505-8913-b6c88d1d9612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='关键词批导上传'])[1]/preceding::span[1]</value>
      <webElementGuid>3923c987-49e2-4cbe-b932-e90cab61847a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='※无法删除之前已提交的附件'])[1]/preceding::span[2]</value>
      <webElementGuid>58d22f46-3f22-41c1-a18d-b32bdad0ec7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='上传']/parent::*</value>
      <webElementGuid>8adab6bb-0f60-4896-bb7d-2da6f4e7a3c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/button/span</value>
      <webElementGuid>edf35f7f-cdda-46ad-a723-3a4f5f1a2dbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '上传' or . = '上传')]</value>
      <webElementGuid>f892a2d2-6a67-47b7-a239-802e20165836</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
