<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>country_Korea</name>
   <tag></tag>
   <elementGuidId>429a20c2-5ce0-4996-aa37-78d8c19ab8ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='T_COUNTRY_CODE_easyui_combobox_i1_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#T_COUNTRY_CODE_easyui_combobox_i1_1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9aadb769-4b24-47fa-bcba-45a947c1a9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>T_COUNTRY_CODE_easyui_combobox_i1_1</value>
      <webElementGuid>dcec202d-557b-4347-948a-3e01d3fc1558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combobox-item combobox-item-hover</value>
      <webElementGuid>ae388c91-fb2d-47a9-b999-310f10809775</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Korea</value>
      <webElementGuid>004c95e9-1267-41a0-ae38-3cf29f214517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;T_COUNTRY_CODE_easyui_combobox_i1_1&quot;)</value>
      <webElementGuid>14d1d44e-929b-4437-9ad6-5203d1a19533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>6437d868-028b-4305-a34a-e023e4bf2f50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='T_COUNTRY_CODE_easyui_combobox_i1_1']</value>
      <webElementGuid>fde6c7dc-4511-46e2-a5a2-644fc819c8db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='China'])[1]/following::div[1]</value>
      <webElementGuid>25ab4c24-1599-4d97-9c2f-1da097b2e200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='※无法删除之前已提交的附件'])[1]/following::div[15]</value>
      <webElementGuid>88ec8f58-4a37-4fa6-be8b-e5b800e93431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India'])[1]/preceding::div[1]</value>
      <webElementGuid>7bb4bc60-4314-40bd-9a02-f062b8521c02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vietnam'])[1]/preceding::div[2]</value>
      <webElementGuid>dc03faa8-6728-4a70-9b59-ec2975a8efc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Korea']/parent::*</value>
      <webElementGuid>eed31978-9ec5-4694-9fb8-e8f38dd57ae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]</value>
      <webElementGuid>a5486536-2311-4d38-af98-aa63a0d62bd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'T_COUNTRY_CODE_easyui_combobox_i1_1' and (text() = 'Korea' or . = 'Korea')]</value>
      <webElementGuid>6933a264-599b-49a9-a729-f61ebafc9afd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
