<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>country_China</name>
   <tag></tag>
   <elementGuidId>92b943a1-dc51-43ed-a2df-8bc4956705a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#T_COUNTRY_CODE_easyui_combobox_i1_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='T_COUNTRY_CODE_easyui_combobox_i1_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b6cc2c3c-e67d-4028-afcf-c90538489d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>T_COUNTRY_CODE_easyui_combobox_i1_0</value>
      <webElementGuid>d44b47e7-17b5-4310-842e-8b7d2649318a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combobox-item combobox-item-hover</value>
      <webElementGuid>cdd7b9a3-a700-430c-9c94-ee6757a778d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>China</value>
      <webElementGuid>255f75a1-1527-485a-91cd-2311db433162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;T_COUNTRY_CODE_easyui_combobox_i1_0&quot;)</value>
      <webElementGuid>27606c31-51c1-4466-bc02-f53cc4e3aacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>2061f00e-bb2e-464f-b41a-36f9d1054902</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='T_COUNTRY_CODE_easyui_combobox_i1_0']</value>
      <webElementGuid>47a17ae3-53b3-43e8-917d-d1efce68f186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='※无法删除之前已提交的附件'])[1]/following::div[14]</value>
      <webElementGuid>93077a4a-1d17-433e-b3a5-6f2faf87176b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='关键词批导上传'])[1]/following::div[15]</value>
      <webElementGuid>384501fb-2780-4313-aa8c-be37a31ea54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Korea'])[1]/preceding::div[1]</value>
      <webElementGuid>84f2238e-d8bc-4b8e-ad4a-0d240d61bb8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India'])[1]/preceding::div[2]</value>
      <webElementGuid>2845cde6-12fa-4684-8405-eb5ad5ce8691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='China']/parent::*</value>
      <webElementGuid>1629d72f-922e-45e2-b27a-b3ad35ce2a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div</value>
      <webElementGuid>f2697505-434e-459b-b84d-7ce0ad7cd11a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'T_COUNTRY_CODE_easyui_combobox_i1_0' and (text() = 'China' or . = 'China')]</value>
      <webElementGuid>6f88889e-7482-4ad1-8318-caf1638778fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
