<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Commercial</name>
   <tag></tag>
   <elementGuidId>c3a3ab03-4eea-4d60-bfb2-2dd18e2a58da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#T_CATEGORY_CODE_easyui_combobox_i2_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='T_CATEGORY_CODE_easyui_combobox_i2_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f905cd46-ef38-404d-83fb-2bf571247009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>T_CATEGORY_CODE_easyui_combobox_i2_1</value>
      <webElementGuid>82e5209e-cda5-46f5-8cac-cb637f080aa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combobox-item combobox-item-hover</value>
      <webElementGuid>1b00d5ff-5483-45f4-9296-0ba60a87d458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Commercial</value>
      <webElementGuid>aa3ae1f0-43bf-4e1f-ba0e-0d88235524f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;T_CATEGORY_CODE_easyui_combobox_i2_1&quot;)</value>
      <webElementGuid>eb6a76b9-6170-4f37-913c-c459f93bdbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>6e523292-f703-4f09-9465-dd55e2a10b2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='T_CATEGORY_CODE_easyui_combobox_i2_1']</value>
      <webElementGuid>9995fd7e-2d4e-4168-a134-2445e4368f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NCI'])[1]/following::div[1]</value>
      <webElementGuid>607aec9a-a577-4e90-8b9d-f3a7878e82a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GPO'])[1]/following::div[4]</value>
      <webElementGuid>ad6189e9-5cb1-4011-987e-5f36cf874adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CAPEX'])[1]/preceding::div[1]</value>
      <webElementGuid>f2bb04b5-b43c-4935-91d9-babdcbcf27a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MRO'])[1]/preceding::div[2]</value>
      <webElementGuid>c8517502-8688-4df4-805c-0d9c1e246e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Commercial']/parent::*</value>
      <webElementGuid>ed104870-ca2c-4615-b347-a9ccab9ac88c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]</value>
      <webElementGuid>69bcd72b-e48b-42c1-a005-492e52d21423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'T_CATEGORY_CODE_easyui_combobox_i2_1' and (text() = 'Commercial' or . = 'Commercial')]</value>
      <webElementGuid>00709b0a-e658-4e74-be00-4b31fabfd7bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
