<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SpotBuy_other</name>
   <tag></tag>
   <elementGuidId>f29daac5-1ee7-4bde-93a0-1ded7e65dfd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EXP6_easyui_combobox_i19_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='EXP6_easyui_combobox_i19_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d3306431-6351-423c-85d5-722eba2c17e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EXP6_easyui_combobox_i19_3</value>
      <webElementGuid>cfae3c9a-23b9-438d-8372-95a3257c7a24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combobox-item combobox-item-hover</value>
      <webElementGuid>948265fb-f9bc-4c86-ad4e-dc4ca196d22b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SpotBuy其他</value>
      <webElementGuid>0455be21-9705-4280-a803-9bdc6c2ea206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EXP6_easyui_combobox_i19_3&quot;)</value>
      <webElementGuid>bfa9dd69-e54f-4f67-81f9-64fd769a25c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>e7abcfa2-6654-44ca-8508-75a4a44b4cf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='EXP6_easyui_combobox_i19_3']</value>
      <webElementGuid>803e8058-8cba-4fa9-b35c-093c4819d03f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SpotBuy调拨'])[1]/following::div[1]</value>
      <webElementGuid>c3e432a7-eea7-44cc-b1de-d9393a97edd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='年框'])[1]/following::div[2]</value>
      <webElementGuid>0735edae-96d0-4b05-baec-d8fb83575711</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAF'])[1]/preceding::div[1]</value>
      <webElementGuid>ffd4cb4c-cf52-492d-8b82-2c85191c27e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='十一月 2023'])[1]/preceding::div[8]</value>
      <webElementGuid>91463eac-45b5-4466-9583-5d7d7e16af98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SpotBuy其他']/parent::*</value>
      <webElementGuid>7cb70994-ef03-4bc5-8091-bb0ce1473b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/div[4]</value>
      <webElementGuid>943a357b-adc1-4be6-b259-1ecbc79c9fc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'EXP6_easyui_combobox_i19_3' and (text() = 'SpotBuy其他' or . = 'SpotBuy其他')]</value>
      <webElementGuid>bd96f41a-1614-467e-9e93-e300ebd33ade</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
