<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_baseline_EOM</name>
   <tag></tag>
   <elementGuidId>583bd8a3-65d2-43f2-bddd-3a31eded0acf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#T_PT_BASELINE_CODE_easyui_combobox_i11_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='T_PT_BASELINE_CODE_easyui_combobox_i11_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>47be726a-5d2e-48e5-a779-e188fe34b81d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>T_PT_BASELINE_CODE_easyui_combobox_i11_1</value>
      <webElementGuid>77df316e-87f2-4640-9817-6aeb57b3f921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combobox-item combobox-item-hover</value>
      <webElementGuid>ba3329a1-7dac-4e17-bff7-e04fe771be63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EOM</value>
      <webElementGuid>ed6cf1b0-7d19-4122-91ae-9358bb9d59c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;T_PT_BASELINE_CODE_easyui_combobox_i11_1&quot;)</value>
      <webElementGuid>9166ab9a-7b1a-45fc-a1f6-fc2d5738b7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>222fb6af-6b29-4d89-ac61-cff5d350dd86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='T_PT_BASELINE_CODE_easyui_combobox_i11_1']</value>
      <webElementGuid>78e8c369-f6fc-4506-ab38-8e5e4be15884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NET'])[1]/following::div[1]</value>
      <webElementGuid>2b531310-0bb7-4e37-b945-5cd1b6bb16bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exceptional'])[1]/following::div[5]</value>
      <webElementGuid>6c60fd8e-9fe1-4af6-9866-5a4b6be95bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CNY'])[1]/preceding::div[1]</value>
      <webElementGuid>1330c04b-ce0b-4953-aee2-686bbeab65a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KRW'])[1]/preceding::div[2]</value>
      <webElementGuid>eece2f4c-f94e-4d9e-94f9-759d0b7350f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='EOM']/parent::*</value>
      <webElementGuid>a019b891-326f-4059-a546-ab6a93ccb365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div[2]</value>
      <webElementGuid>bbaa25db-8f82-4d43-be0d-417142b70ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'T_PT_BASELINE_CODE_easyui_combobox_i11_1' and (text() = 'EOM' or . = 'EOM')]</value>
      <webElementGuid>50ed898b-6d82-48ba-84ec-b157bc01dc87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
