<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_low_big_yes</name>
   <tag></tag>
   <elementGuidId>c5f4a43c-7f93-4d9c-ab28-5ec60ece293d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#T_LOWES_BID_CODE_easyui_combobox_i5_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='T_LOWES_BID_CODE_easyui_combobox_i5_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>43e48c18-ee71-4781-a9cb-d0567abf20a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>T_LOWES_BID_CODE_easyui_combobox_i5_1</value>
      <webElementGuid>f490cd32-8df9-40c1-a032-1631a09d74da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combobox-item combobox-item-hover</value>
      <webElementGuid>08396eeb-e917-43fe-9cd5-4d0bcfcd29d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>否</value>
      <webElementGuid>f8105426-abe2-4b89-a308-1cb0601256da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;T_LOWES_BID_CODE_easyui_combobox_i5_1&quot;)</value>
      <webElementGuid>269fcac9-fd22-42a6-a9a2-44e489e47049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>279486ca-5ef2-4483-899e-ebac2d00f89f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='T_LOWES_BID_CODE_easyui_combobox_i5_1']</value>
      <webElementGuid>772a005b-ff98-4d0e-88ae-d3e9f6a4546d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='是'])[2]/following::div[1]</value>
      <webElementGuid>fd8a8f25-784e-4369-82bd-bb54e75ae11e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HKD'])[1]/following::div[4]</value>
      <webElementGuid>36e9a559-589b-482b-8235-46c0797ce692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='电子竞标最低价，谈判最低价'])[1]/preceding::div[1]</value>
      <webElementGuid>5e7fcb3c-0829-4b7b-ab33-b048d03e6458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='电子竞标非最低价，谈判最低价'])[1]/preceding::div[2]</value>
      <webElementGuid>0fd15959-1b52-49d5-943b-c0e7a9c446a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/div[2]</value>
      <webElementGuid>8c207bdd-9e26-4f46-ac24-e274d5a26f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'T_LOWES_BID_CODE_easyui_combobox_i5_1' and (text() = '否' or . = '否')]</value>
      <webElementGuid>3e531839-f9ec-4a4f-b51b-63b155c21f37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
