<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sales</name>
   <tag></tag>
   <elementGuidId>2fb7222f-ee8e-409c-a94c-be65433299ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#T_SUB_CATEGORY_CODE_easyui_combobox_i20_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='T_SUB_CATEGORY_CODE_easyui_combobox_i20_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b1cb3b4b-36b7-4996-8825-edb919d6f39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>T_SUB_CATEGORY_CODE_easyui_combobox_i20_1</value>
      <webElementGuid>e17d1900-15e2-4768-99af-f401a8251ee4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combobox-item combobox-item-hover</value>
      <webElementGuid>967294ee-7a74-4876-a696-66c983837ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sales</value>
      <webElementGuid>c1cf89df-54b2-4093-9f0b-b4413109c29d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;T_SUB_CATEGORY_CODE_easyui_combobox_i20_1&quot;)</value>
      <webElementGuid>d86984c1-be85-4961-acbd-e10745935388</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>24aad2fa-00b4-42b8-b3e4-d8c44bfe7c68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='T_SUB_CATEGORY_CODE_easyui_combobox_i20_1']</value>
      <webElementGuid>bf92fdb1-ed74-4f89-9201-06a53b76510f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketing'])[1]/following::div[1]</value>
      <webElementGuid>2b343eab-67c2-493e-afe7-cb6edc979cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agro'])[1]/following::div[4]</value>
      <webElementGuid>f8832d44-82ca-4c03-ab13-4d8ab06f0ebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comm Capex'])[1]/preceding::div[1]</value>
      <webElementGuid>df998a38-344c-4ffa-ab23-6bc47e13008b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='是'])[1]/preceding::div[2]</value>
      <webElementGuid>54ee835b-c770-4b61-96cf-946f259e93fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sales']/parent::*</value>
      <webElementGuid>a9c0dde3-0797-4464-8e82-c8109eb65712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div[2]</value>
      <webElementGuid>e0995a97-7015-461a-96e5-06120722d76b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'T_SUB_CATEGORY_CODE_easyui_combobox_i20_1' and (text() = 'Sales' or . = 'Sales')]</value>
      <webElementGuid>ec7c73a0-043f-4719-a013-c22317878f5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
