<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_NA</name>
   <tag></tag>
   <elementGuidId>808daf2a-e402-48c9-983d-c25405f5c842</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#T_IPRICE_TYPE_CODE_easyui_combobox_i14_3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='谈判非最低价'])[1]/following::div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bfc02c1f-bf0c-4671-b8f3-3ebe6723ee48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>T_IPRICE_TYPE_CODE_easyui_combobox_i14_3</value>
      <webElementGuid>e41febc9-3dfa-4285-9447-ac81edc405c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combobox-item combobox-item-hover</value>
      <webElementGuid>5824045b-2467-4ee5-b7aa-92061f8ab86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>N/A</value>
      <webElementGuid>5991cfa1-816c-4482-80ea-d29b779e8e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;T_IPRICE_TYPE_CODE_easyui_combobox_i14_3&quot;)</value>
      <webElementGuid>31196483-23ee-47f1-a87f-88b8a16aab14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>2c9def3e-3bce-440c-bab8-08c9dec7277a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='T_IPRICE_TYPE_CODE_easyui_combobox_i14_3']</value>
      <webElementGuid>9d745413-2cc8-4f76-8cca-14f2af4b3765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='谈判非最低价'])[1]/following::div[1]</value>
      <webElementGuid>4cba3412-e0c5-4c1d-a1f3-05241e2eee55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='电子竞标非最低价，谈判最低价'])[1]/following::div[2]</value>
      <webElementGuid>3be17b7a-3aef-4890-9a20-3babac44cfee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='无电子竞标，谈判最低价'])[1]/preceding::div[1]</value>
      <webElementGuid>ceffa769-0607-45f0-82d5-b9aa24ecfd2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='是'])[3]/preceding::div[2]</value>
      <webElementGuid>044c0ccb-ee63-43a7-b50f-3d3ea5070ee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='N/A']/parent::*</value>
      <webElementGuid>02226825-61ff-4748-8d36-7d51f61e3182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[14]/div/div[4]</value>
      <webElementGuid>29663b00-65d9-4038-8f41-8b0de5ecffe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'T_IPRICE_TYPE_CODE_easyui_combobox_i14_3' and (text() = 'N/A' or . = 'N/A')]</value>
      <webElementGuid>d73f6b61-bad6-4db3-8a07-3c2aedae76b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
