<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_RPSS</name>
   <tag></tag>
   <elementGuidId>f18ecec5-fac4-4881-9f58-8eb4a122510f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#T_PATTERN_CODE_easyui_combobox_i9_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='T_PATTERN_CODE_easyui_combobox_i9_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7b3ba94c-d2dd-400d-95f5-995ee9b17f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>T_PATTERN_CODE_easyui_combobox_i9_2</value>
      <webElementGuid>a0ba2fa3-87c9-4f19-8684-48d834e529ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combobox-item combobox-item-hover</value>
      <webElementGuid>ef23d9a5-b8d6-46c5-8f11-1066d176d101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RPSS</value>
      <webElementGuid>6adce87f-1249-40d9-baf7-6071b3ff6d77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;T_PATTERN_CODE_easyui_combobox_i9_2&quot;)</value>
      <webElementGuid>08053995-e76d-4e0f-8e2c-5484d58831fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>d8422bc1-e29d-451d-866a-942d01f6a77a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='T_PATTERN_CODE_easyui_combobox_i9_2']</value>
      <webElementGuid>b22b1d0f-2f38-44c9-9404-b4bffdc671ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RPO'])[1]/following::div[1]</value>
      <webElementGuid>115b1456-0685-4cfb-940b-ed58027d19e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non-Compliant'])[1]/following::div[2]</value>
      <webElementGuid>6ed17878-125a-457c-85ec-81d50d4637cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GPO Led'])[1]/preceding::div[1]</value>
      <webElementGuid>d239be2e-bb09-45c3-8085-bc6421921193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GPO'])[1]/preceding::div[2]</value>
      <webElementGuid>f10179fb-8279-47dd-9c63-b7c23bad8dcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='RPSS']/parent::*</value>
      <webElementGuid>8ccd4319-52c1-445e-8ae0-97c6a3eb9a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[3]</value>
      <webElementGuid>316c825c-6dbd-4795-93d2-f239109842f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'T_PATTERN_CODE_easyui_combobox_i9_2' and (text() = 'RPSS' or . = 'RPSS')]</value>
      <webElementGuid>fcb25644-6393-49ca-ae9d-19573d449ba1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
