<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_needvendor_no</name>
   <tag></tag>
   <elementGuidId>2f6591ac-df5d-44aa-939f-6f7fafd1973e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#T_SINGLE_SOURCE_CODE_easyui_combobox_i7_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='T_SINGLE_SOURCE_CODE_easyui_combobox_i7_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7d86f1e7-d75d-4b79-9054-7ff14673fed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>T_SINGLE_SOURCE_CODE_easyui_combobox_i7_1</value>
      <webElementGuid>fa2d6085-a55b-4ae1-8978-158f881b5ee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combobox-item combobox-item-hover</value>
      <webElementGuid>3bb4af15-964f-460e-81e5-79d7e43e5d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>否</value>
      <webElementGuid>c14a9482-75e8-4eba-8bb9-8092dbb032de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;T_SINGLE_SOURCE_CODE_easyui_combobox_i7_1&quot;)</value>
      <webElementGuid>9bdca70b-dc0f-412d-a491-7caf7ced877d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>37c44b24-4600-4fc6-a1f6-a1c5115e9152</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='T_SINGLE_SOURCE_CODE_easyui_combobox_i7_1']</value>
      <webElementGuid>7194ceff-cdc7-427b-9bbf-f1e1484497d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='是'])[4]/following::div[1]</value>
      <webElementGuid>9626c7a0-d9f1-4684-aded-8f55c9d155c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::div[4]</value>
      <webElementGuid>c19718c7-5956-4e20-a19c-a27e7db3325b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='年框'])[1]/preceding::div[2]</value>
      <webElementGuid>1838047c-b42b-4fdd-9b93-7087863fb629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SpotBuy调拨'])[1]/preceding::div[3]</value>
      <webElementGuid>954e5ecc-6d99-4ac4-891a-5ff8df595fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div[2]</value>
      <webElementGuid>bbeb300c-72d8-47de-8859-8312a850a8eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'T_SINGLE_SOURCE_CODE_easyui_combobox_i7_1' and (text() = '否' or . = '否')]</value>
      <webElementGuid>939d917d-94bc-406c-b28b-d525a4f2132f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
