<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_oneoff_contract_yes</name>
   <tag></tag>
   <elementGuidId>0bd657e4-589b-444d-be65-584e00d72bef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#T_ONEOFF_CONTRACT_CODE_easyui_combobox_i4_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='T_ONEOFF_CONTRACT_CODE_easyui_combobox_i4_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f87911e3-4e39-4d72-93c0-0f167bef9931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>T_ONEOFF_CONTRACT_CODE_easyui_combobox_i4_0</value>
      <webElementGuid>6be1c51b-f432-42ef-a998-ef067671f217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combobox-item combobox-item-hover</value>
      <webElementGuid>1a088775-3d30-4b42-a9f3-f9e4986c6955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>是</value>
      <webElementGuid>b992ed6d-2ee1-49f2-99e2-3867cbd33272</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;T_ONEOFF_CONTRACT_CODE_easyui_combobox_i4_0&quot;)</value>
      <webElementGuid>4eef71ed-fe44-4e6c-b097-233320efa3ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>876274dd-8c19-4c62-9969-a64e4f38c3b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='T_ONEOFF_CONTRACT_CODE_easyui_combobox_i4_0']</value>
      <webElementGuid>34cd5f49-85b3-4ef9-bdaa-f62cfd7c7cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comm Capex'])[1]/following::div[3]</value>
      <webElementGuid>bab0f91b-ab64-47c4-88ad-757e5fa47835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sales'])[1]/following::div[4]</value>
      <webElementGuid>509eabad-39e5-431d-b895-3f0419791473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='否'])[1]/preceding::div[1]</value>
      <webElementGuid>4173db77-2143-4e97-8a9a-f19894ac6568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='实物类'])[1]/preceding::div[2]</value>
      <webElementGuid>f89381e1-f45e-45cb-bf56-4a975a44f06f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='是']/parent::*</value>
      <webElementGuid>751e9080-9d45-41cc-abb3-91c5c9831ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div</value>
      <webElementGuid>792e645b-c149-4032-b567-c930da4e745f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'T_ONEOFF_CONTRACT_CODE_easyui_combobox_i4_0' and (text() = '是' or . = '是')]</value>
      <webElementGuid>ca1be123-ff6f-4ba0-9353-6a29c4d81796</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
