<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__calendar-nav calendar-nextyear calenda_b62f14</name>
   <tag></tag>
   <elementGuidId>0c58da10-51f3-4978-b2fc-1e743666cf24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.calendar-nav.calendar-nextyear.calendar-nav-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[27]/div/div/div/div/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3a3215df-385c-4953-801f-a9df468be5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calendar-nav calendar-nextyear calendar-nav-hover</value>
      <webElementGuid>8b3c026e-b958-4725-8d63-b7122d6afff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;panel-fit&quot;]/body[@class=&quot;panel-noscroll&quot;]/div[@class=&quot;panel combo-p panel-htop&quot;]/div[@class=&quot;combo-panel panel-body panel-body-noheader&quot;]/div[@class=&quot;datebox-calendar-inner panel-noscroll&quot;]/div[@class=&quot;calendar calendar-noborder easyui-fluid&quot;]/div[@class=&quot;calendar-header&quot;]/div[@class=&quot;calendar-nav calendar-nextyear calendar-nav-hover&quot;]</value>
      <webElementGuid>898584a1-8365-4022-92e7-6730d90de87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>01e5b0e3-d1cf-48f6-b5c2-13f0f38cecd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div/div/div/div/div[4]</value>
      <webElementGuid>1e0cf734-c78e-441f-abff-3ba2b70b4a0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
