<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_jingbiao_no</name>
   <tag></tag>
   <elementGuidId>9fa651c9-ad30-4395-a2ed-f515bd217879</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#T_IF_ELECTRONIC_BIDDING_CODE_easyui_combobox_i6_1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='T_IF_ELECTRONIC_BIDDING_CODE_easyui_combobox_i6_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>05c5e3ca-1bb9-4a56-a486-c8147fbf8d65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>T_IF_ELECTRONIC_BIDDING_CODE_easyui_combobox_i6_1</value>
      <webElementGuid>4dee138a-40ea-4df4-82d1-557ba70f99da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combobox-item combobox-item-hover</value>
      <webElementGuid>cb81139d-1702-4bd2-a84f-e32d71bd2d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>否</value>
      <webElementGuid>06275cf2-e068-4f23-88ff-b105bae3bf1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;T_IF_ELECTRONIC_BIDDING_CODE_easyui_combobox_i6_1&quot;)</value>
      <webElementGuid>175f016a-29c9-4f8b-b13b-a5d08384c498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>4de52fbf-2f71-4da4-adf9-daa67796bc84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='T_IF_ELECTRONIC_BIDDING_CODE_easyui_combobox_i6_1']</value>
      <webElementGuid>5f12830e-b3e0-469b-97e5-82560394de54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='是'])[3]/following::div[1]</value>
      <webElementGuid>a7ad7781-a854-4fcd-9ea1-6e919deb33a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='无电子竞标，谈判最低价'])[1]/following::div[4]</value>
      <webElementGuid>c5f5186d-b371-4c7e-a878-65ff229feede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dutch'])[1]/preceding::div[1]</value>
      <webElementGuid>dfe9cb1c-12dc-4ef0-9f5d-69f067110a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Japanese'])[1]/preceding::div[2]</value>
      <webElementGuid>c07ac874-4a11-4e52-a74b-c6a328e4574d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/div/div[2]</value>
      <webElementGuid>e68064b9-cc75-4dcb-8c66-ba6376fcfc93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'T_IF_ELECTRONIC_BIDDING_CODE_easyui_combobox_i6_1' and (text() = '否' or . = '否')]</value>
      <webElementGuid>c0169fde-508e-4c78-9d3d-63ee721bfcc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
