<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_contract_duli</name>
   <tag></tag>
   <elementGuidId>e56cdc73-76bb-40b3-a1e7-969a309ca15e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_easyui_combobox_i22_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_easyui_combobox_i22_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>24086a87-18e1-4992-b5a4-a9c068c3f005</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_easyui_combobox_i22_0</value>
      <webElementGuid>0d7983cc-43e2-4737-bfc7-acd797d19c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combobox-item combobox-item-hover</value>
      <webElementGuid>d2b9f00e-2ad5-4735-8d19-968cbb8fab2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>独立合同</value>
      <webElementGuid>659b72c2-29e0-4d03-9d5d-d90a19654696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_easyui_combobox_i22_0&quot;)</value>
      <webElementGuid>a0813e85-514a-47fc-b09d-8010edd90281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>730db8c3-de7c-4d53-82ef-f687dfd15797</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='_easyui_combobox_i22_0']</value>
      <webElementGuid>d30c69fb-1faa-42f8-8cd6-9493bb5fc531</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', '_easyui_combobox_i22_0', '&quot;', ')')])[1]/following::div[3]</value>
      <webElementGuid>13d09863-c8d8-4d5f-b4a4-b548eee700c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='六'])[5]/following::div[8]</value>
      <webElementGuid>4ab48089-cf8a-444e-b654-317eb7fc05cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='主合同'])[1]/preceding::div[1]</value>
      <webElementGuid>48af1015-6982-4f70-9de4-d4a2dd1d597a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='十一月 2023'])[6]/preceding::div[6]</value>
      <webElementGuid>765d2669-ecd0-42e6-ab8a-a2f72a8a389d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='独立合同']/parent::*</value>
      <webElementGuid>5ed2e0de-45c2-4058-b48f-7b02690b822e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/div/div</value>
      <webElementGuid>44ee095a-5923-4707-a8f6-6e4dcf9e0f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '_easyui_combobox_i22_0' and (text() = '独立合同' or . = '独立合同')]</value>
      <webElementGuid>41fa4c5e-9946-484d-bf21-288cae78863b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
