<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_curreny_CNY</name>
   <tag></tag>
   <elementGuidId>0c0d52df-c4af-4b0b-b720-61ad500055c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#T_CURRENCY_CODE_easyui_combobox_i12_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='T_CURRENCY_CODE_easyui_combobox_i12_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0d925723-5ed0-41c0-ae9a-c70d6bcac02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>T_CURRENCY_CODE_easyui_combobox_i12_0</value>
      <webElementGuid>dd02077c-5d07-4359-9f9e-da72ee7f8a3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combobox-item combobox-item-hover</value>
      <webElementGuid>da6e2e44-03f1-430f-829a-384d4ebc26e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CNY</value>
      <webElementGuid>29063d58-4ca5-45a6-bd0a-af5aa8743181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;T_CURRENCY_CODE_easyui_combobox_i12_0&quot;)</value>
      <webElementGuid>2a1eacaf-5e18-43aa-aea1-dd67e6184ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>ac17432e-7cb7-489f-8ced-23c5daf27f56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='T_CURRENCY_CODE_easyui_combobox_i12_0']</value>
      <webElementGuid>44429c2b-4337-44ee-b500-935f8e99736c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EOM'])[1]/following::div[3]</value>
      <webElementGuid>b502c967-73bc-4660-92a8-595b407b70ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NET'])[1]/following::div[4]</value>
      <webElementGuid>703170f7-00dc-4085-89b2-217d63fd2137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KRW'])[1]/preceding::div[1]</value>
      <webElementGuid>dd7256a9-00cc-4d94-b415-db2578966152</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VND'])[1]/preceding::div[2]</value>
      <webElementGuid>ab8043f7-ffc7-479a-990f-9094ff97decd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CNY']/parent::*</value>
      <webElementGuid>fb215a98-d7a1-4a0c-855d-01bef655e127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[12]/div/div</value>
      <webElementGuid>9a031ad5-0224-4db8-adfa-e4b4ff0560ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'T_CURRENCY_CODE_easyui_combobox_i12_0' and (text() = 'CNY' or . = 'CNY')]</value>
      <webElementGuid>492288db-3362-43c0-b3cb-1ba6e5623d99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
