<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_classification_material</name>
   <tag></tag>
   <elementGuidId>d34b0e89-5c33-4f3c-b4cb-84fd9005c36d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#T_CLASSIFICATION_CODE_easyui_combobox_i8_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='T_CLASSIFICATION_CODE_easyui_combobox_i8_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>50198a14-4826-422b-abbc-1b36d1a998c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>T_CLASSIFICATION_CODE_easyui_combobox_i8_0</value>
      <webElementGuid>3d06e5ef-0601-4e11-8c40-297677471d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>combobox-item combobox-item-hover</value>
      <webElementGuid>ce00e5a8-f286-4f2f-8d2e-3f20420c5600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>实物类</value>
      <webElementGuid>f6469392-5dcd-4d97-a54d-56638871e641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;T_CLASSIFICATION_CODE_easyui_combobox_i8_0&quot;)</value>
      <webElementGuid>8b6a62d5-e805-4e1f-bc2e-c9df89c3e234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>dd3d0759-a2ff-44e1-9946-8a09084c1d9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='T_CLASSIFICATION_CODE_easyui_combobox_i8_0']</value>
      <webElementGuid>6a77575f-e91e-493d-b39d-1dc2d229d37a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='否'])[1]/following::div[3]</value>
      <webElementGuid>6420fd9d-11bb-4444-a2c2-d9ba42ce4890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='是'])[1]/following::div[4]</value>
      <webElementGuid>c783ea63-c6c3-4daa-9adc-0bc57feedb9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='服务类'])[1]/preceding::div[1]</value>
      <webElementGuid>d38c965f-b140-4022-97ea-fdfeec2502d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exceptional'])[1]/preceding::div[2]</value>
      <webElementGuid>0ce57f91-25fb-4437-993f-7254d09779ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='实物类']/parent::*</value>
      <webElementGuid>98cd85f4-e77c-45e0-aebf-8611a10e5e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div</value>
      <webElementGuid>e9cd838a-2837-4fe4-954c-aba58b6ecebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'T_CLASSIFICATION_CODE_easyui_combobox_i8_0' and (text() = '实物类' or . = '实物类')]</value>
      <webElementGuid>31d3958d-6b28-4423-83a5-c589c85fecec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
