<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__ifm_1_1</name>
   <tag></tag>
   <elementGuidId>d87572a3-de2a-4405-930b-21133522b912</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ifm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>8b8443f9-19e2-43cd-a904-864062124294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifm</value>
      <webElementGuid>023d6713-5e1e-4e9f-9e84-9357c320c408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ifm</value>
      <webElementGuid>1171f543-0664-43ec-b9b6-d435384e4db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>Datadetail.cshtml?op=create&amp;type=dag&amp;cid=undefined</value>
      <webElementGuid>909def59-a095-4193-84b0-38f99fde1ee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>4155f2b8-c332-4109-ad6b-ec379b22da77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>51fc28aa-216b-4e0f-9da7-8388b45f80ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ifm&quot;)</value>
      <webElementGuid>98c304ff-cebd-4269-9a68-0445761a518e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>00b478b4-b2b5-4557-a273-e57ea7e71e46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifm']</value>
      <webElementGuid>395df990-7fa1-4bda-8141-c4c0f275f65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>db8fd47a-4a94-4fd5-935a-e55204ffc74e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ifm' and @name = 'ifm' and @src = 'Datadetail.cshtml?op=create&amp;type=dag&amp;cid=undefined']</value>
      <webElementGuid>26ffe336-aba6-4c27-9da1-a05e5a483fbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
