<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__corp</name>
   <tag></tag>
   <elementGuidId>e29ea7d2-992f-42bd-a1ba-d189ec7d42ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#corp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='corp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c16fb5af-d92d-4b6b-803a-2bd02fc8c2e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>corp</value>
      <webElementGuid>360980af-d115-4aec-ac23-761ec293a6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>corp</value>
      <webElementGuid>e121772a-f279-4841-8912-ccc7be10422f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../../../BWForm/ConTractDAGDataManage/Page/childPage/ContractDagSignEntity.cshtml?IsVIC=1&amp;VICName=undefined</value>
      <webElementGuid>acdcd325-efd1-4193-a117-25bfd498b393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>c424c5dc-1af9-42ec-afb4-e3878f7edab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6a606861-ac10-454f-adf9-98c043c452a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;corp&quot;)</value>
      <webElementGuid>4508a40d-890b-460f-bbb2-8d39d66aefab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>e9c33ae5-b338-4dcc-ae42-5a1bc248ae4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='corp']</value>
      <webElementGuid>1ac92ff4-60b2-4433-aa06-25db97e93f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>83c98306-fab8-40c6-a59f-f38726aa26d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'corp' and @name = 'corp' and @src = '../../../BWForm/ConTractDAGDataManage/Page/childPage/ContractDagSignEntity.cshtml?IsVIC=1&amp;VICName=undefined']</value>
      <webElementGuid>bc7b20bc-5819-425f-b3a7-0c19979ac8e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
