<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PR ID</name>
   <tag></tag>
   <elementGuidId>e2a26b16-2735-4c31-aa85-e2008992c20a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_easyui_textbox_input9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_easyui_textbox_input9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>291440be-9638-40c1-b883-ea171dcf33a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_easyui_textbox_input9</value>
      <webElementGuid>beac77bc-4cdc-47ae-afe7-e1ad0e41beb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f02ab9b1-4a0e-4238-94e8-86fbeac29a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-text validatebox-text</value>
      <webElementGuid>db6ee94b-9a60-459b-a22b-dd1da03905cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0facd23b-bc01-49d5-b0b0-adef7edd9241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_easyui_textbox_input9&quot;)</value>
      <webElementGuid>f75eb342-ee5b-4fb0-9f6b-10731807f003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>4166711c-5387-461e-b84f-bc040efa23ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_easyui_textbox_input9']</value>
      <webElementGuid>c38fdc2f-a98f-47c2-8067-37e060e00128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='daginfo']/div[20]/div/span/input</value>
      <webElementGuid>a7d5664b-f9d7-467f-96b5-eefd84b5284c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/span/input</value>
      <webElementGuid>97f91f8a-b5a0-448b-97e8-6a7b878d83fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_easyui_textbox_input9' and @type = 'text']</value>
      <webElementGuid>a6619026-8dce-4a99-89c3-9537bcf2862a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
