<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_vendor</name>
   <tag></tag>
   <elementGuidId>faca985a-eab1-4dd8-984f-d8b96e93fb58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_easyui_textbox_input174</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='ContractGrid_datagrid-row-r1-2-0']/td[24]/div/table/tbody/tr/td/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d54b5399-e682-45d2-87e6-dda6bbac8285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_easyui_textbox_input174</value>
      <webElementGuid>0fff3925-7ed2-499a-b030-ece38693c33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a6edcdb2-6a7b-4c06-bf5a-26b3980480bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-text validatebox-text validatebox-readonly validatebox-invalid</value>
      <webElementGuid>e673ba69-96e8-424d-9beb-400f3823a88e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>40a95e7e-3b7e-4a6c-8bb1-99b83b12d8d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_easyui_textbox_input174&quot;)</value>
      <webElementGuid>adbc1f99-0793-4701-9fad-e7382eaef926</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>be412aa3-6441-4122-a05f-100ee9dcdd84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_easyui_textbox_input174']</value>
      <webElementGuid>2e7c2f9c-87a2-482d-ba1d-daeae2754b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContractGrid_datagrid-row-r1-2-0']/td[24]/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>63364d1d-5345-438e-b9f8-fb1241dee7ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[24]/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>f1dade88-e37a-4bc7-8909-8cbe430f2065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_easyui_textbox_input174' and @type = 'text']</value>
      <webElementGuid>a9af04de-f868-4522-af9d-51753364d296</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
