<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_paymentcondition</name>
   <tag></tag>
   <elementGuidId>c629e2ba-f451-478f-bfd2-4c67aa985c26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_easyui_textbox_input175</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='ContractGrid_datagrid-row-r1-2-0']/td[25]/div/table/tbody/tr/td/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53b4f773-a89f-4272-861d-9db8ca123b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_easyui_textbox_input175</value>
      <webElementGuid>5a18e783-2d5e-4424-819e-c0198b1992c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a4fb471b-97bd-4d6f-8c92-56fefdcff924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-text validatebox-text validatebox-invalid tooltip-f</value>
      <webElementGuid>7b84fc61-5a3b-43d2-b8bc-68d594531a0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>89e399c1-4a91-466d-af9e-12e986d36cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_easyui_textbox_input175&quot;)</value>
      <webElementGuid>3b18d9b7-482f-48db-b27b-7bb0a40b5378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>d54bfdf7-3f64-452c-ba2a-2ac0cc2002a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_easyui_textbox_input133']</value>
      <webElementGuid>68811ac8-1fad-4628-95d4-952ce373223d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContractGrid_datagrid-row-r1-2-0']/td[25]/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>5f7aa901-9ef9-40cb-9fd3-8cce8d5ffcc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[25]/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>076b8c59-5650-4153-bc91-715825d3da11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_easyui_textbox_input133' and @type = 'text']</value>
      <webElementGuid>32925d50-2c99-4d60-a705-09cc10b89528</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
