<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ck</name>
   <tag></tag>
   <elementGuidId>09cb9003-130b-4c5d-b704-b45a01d13198</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ck&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='ck']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59d7ed23-d264-4891-bf30-a021e7ddc61c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>23f7290a-d846-445d-9967-59117b8426ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ck</value>
      <webElementGuid>d6d8bf28-e497-491b-8210-9322cd5d5060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;entitydataGrid_datagrid-row-r1-2-0&quot;)/td[1]/div[@class=&quot;datagrid-cell-check&quot;]/input[1]</value>
      <webElementGuid>525b7974-6c4b-40ce-a554-f3f02fa56d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__corp</value>
      <webElementGuid>3b00ed0d-2cd7-43f7-a676-33396defa344</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ck']</value>
      <webElementGuid>2655d44e-a784-4286-9603-adeea3c18169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='entitydataGrid_datagrid-row-r1-2-0']/td/div/input</value>
      <webElementGuid>0f0d4d04-74d5-414f-99ea-413701220cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/div/input</value>
      <webElementGuid>101dfd84-d063-463a-ab19-d8d6b7dca55d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'ck']</value>
      <webElementGuid>77a34659-9649-4720-8192-7cf96dcd28bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
