<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_best_price</name>
   <tag></tag>
   <elementGuidId>da5041eb-2c09-4ac9-8ea6-a556695948d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_easyui_textbox_input103</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_easyui_textbox_input103']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>178c5566-21f0-4d30-92cf-ac73e998b135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_easyui_textbox_input103</value>
      <webElementGuid>06fca9c1-efc8-4e3b-b8b3-9385b2475578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>93dd9163-0765-443a-b5e2-293e2eedbe65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-text validatebox-text</value>
      <webElementGuid>8f448c75-a0ba-403b-a864-192d2741481a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7593beb5-8116-46bd-a18f-970044d659db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_easyui_textbox_input103&quot;)</value>
      <webElementGuid>d8fa2971-5d05-493b-9a26-8424c6859cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>f32466f4-fb6b-4874-bd41-a0308d0c82ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_easyui_textbox_input103']</value>
      <webElementGuid>40e5e628-e2b3-4408-830b-a72791087d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='daginfo']/div[13]/div/span/input</value>
      <webElementGuid>94565d5a-fdda-4902-9532-aadaba725ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[13]/div/span/input</value>
      <webElementGuid>dabc66c8-2537-4fa2-b75a-5ca064b8a16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_easyui_textbox_input103' and @type = 'text']</value>
      <webElementGuid>d7e3d0ad-8e5b-4f50-a372-70629bc210a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
