<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ck (1)</name>
   <tag></tag>
   <elementGuidId>b4cd0385-84e5-4249-bb1f-9dc419eaabe3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;ck&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='RMdataGrid_datagrid-row-r1-2-0']/td/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91cbee3a-728a-4362-90d5-ed5a1e0d59c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bc0538b1-3424-4100-83c2-85cfeb8e64e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ck</value>
      <webElementGuid>7cd8ed05-bd6d-4b72-be15-7f000abf2baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RMdataGrid_datagrid-row-r1-2-0&quot;)/td[1]/div[@class=&quot;datagrid-cell-check&quot;]/input[1]</value>
      <webElementGuid>2273d641-bf8d-422a-a0e1-9bcc4e0ebb6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__corp</value>
      <webElementGuid>b893c8df-808f-4185-90aa-bbac81f436c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='ck']</value>
      <webElementGuid>e29d87e3-0e94-4373-aca0-50ebd69af2da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='RMdataGrid_datagrid-row-r1-2-0']/td/div/input</value>
      <webElementGuid>2ca6f795-5758-49a1-9485-3f7c22cbb10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/div/input</value>
      <webElementGuid>41b1d656-f497-4b82-8657-c7a25905d37c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'ck']</value>
      <webElementGuid>3f2a561d-5360-4bb8-a65a-fc95d1657422</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
