<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_company</name>
   <tag></tag>
   <elementGuidId>567fbf3d-cf60-49b7-addd-af1781d27de1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_easyui_textbox_input171</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='ContractGrid_datagrid-row-r1-2-0']/td[21]/div/table/tbody/tr/td/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>305ffebf-544b-42f3-9e01-473df0a07fc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_easyui_textbox_input171</value>
      <webElementGuid>e78bc96a-c5b6-4cb4-b0eb-d44a1218fbb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1560c372-2224-48ee-99ba-28d23aa41b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-text validatebox-text validatebox-readonly validatebox-invalid</value>
      <webElementGuid>e71c4f01-a602-4639-9907-8b44590d1031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>11cc40d3-8f6f-446a-bd2c-25bbb95d5992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_easyui_textbox_input171&quot;)</value>
      <webElementGuid>82b78244-c628-45c2-8028-32042ff8ffe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>23db3a86-f343-428e-8300-18ee9a1e399c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_easyui_textbox_input171']</value>
      <webElementGuid>4571256e-9b98-4fed-8b7b-75ccb070b2a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContractGrid_datagrid-row-r1-2-0']/td[21]/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>ee252125-0270-43c4-8de5-6a0f6f75fda1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[21]/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>ae1b7560-e722-4052-b055-5cdfa23b9f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_easyui_textbox_input171' and @type = 'text']</value>
      <webElementGuid>87a24950-8cad-4013-973c-fb44a58dc57e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
