<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_changepaymentcondition</name>
   <tag></tag>
   <elementGuidId>a0043e4d-d841-4e94-8000-756b5474461c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_easyui_textbox_input177</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='ContractGrid_datagrid-row-r1-2-0']/td[27]/div/table/tbody/tr/td/span/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4ad2535-9594-4941-a71a-02105a505bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_easyui_textbox_input177</value>
      <webElementGuid>0bc10f82-cc5f-424b-9235-55d31c7c4003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d1d3e689-db04-4b53-90af-37f5c9a3721a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-text validatebox-text validatebox-invalid textbox-prompt tooltip-f</value>
      <webElementGuid>da11cc98-5a57-4dbb-a129-34e2dc90c6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>532e9538-ca65-4af2-b0a5-6492ded585b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_easyui_textbox_input177&quot;)</value>
      <webElementGuid>51f0c249-b1b9-407b-a81a-6b4f5d13ca83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>f2265a93-2272-4f0e-86d5-b83ef188e53c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_easyui_textbox_input135']</value>
      <webElementGuid>8fa7e63a-97fe-4e73-8ee9-a42cc31cb0c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContractGrid_datagrid-row-r1-2-0']/td[27]/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>28e6e635-4d4a-4350-a5f1-8eb7f25d1b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[27]/div/table/tbody/tr/td/span/input</value>
      <webElementGuid>2f605beb-a263-4376-a6da-50f0fc7fe538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = '_easyui_textbox_input135' and @type = 'text']</value>
      <webElementGuid>ee643d91-5046-4071-811c-6578753a2839</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
