<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Incumbent</name>
   <tag></tag>
   <elementGuidId>4d53193f-53e6-48c0-a392-c9f2bf78151e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='daginfo']/div[16]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>fd4e895c-3155-4c6d-bb3a-c14d59e8acd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-label col-md-2</value>
      <webElementGuid>dff29d9a-32de-44fe-aae7-fda1795019c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>T_SUPPLIERS_TOTAL</value>
      <webElementGuid>21b4ad55-0846-454b-995a-3adb0a0ca8bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n-text</name>
      <type>Main</type>
      <value>T_SUPPLIERS_TOTAL</value>
      <webElementGuid>90d99200-c379-4737-991e-98b5b212da9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>现有供应商总数</value>
      <webElementGuid>b33cd975-9338-46c2-96f4-cd38b6f59c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;daginfo&quot;)/div[@class=&quot;row koreaHidden&quot;]/label[@class=&quot;control-label col-md-2&quot;]</value>
      <webElementGuid>bf29da2d-9a38-4d8b-8a95-17b42e772952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>75a21e4e-d1a9-4451-853e-55d9d8a8c4a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='daginfo']/div[16]/label</value>
      <webElementGuid>5f6e5c13-415f-40bd-8a1b-ea3399d74832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='竞标类型'])[1]/following::label[1]</value>
      <webElementGuid>c11667d2-7d55-4bf5-be21-7c5971cc678d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='是否电子竞标'])[1]/following::label[2]</value>
      <webElementGuid>105ae78f-c30f-4ad7-8a6b-a4529b786fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='新供应商总数'])[1]/preceding::label[1]</value>
      <webElementGuid>3298cd88-1df6-4bf2-b3c2-f349d44d7ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='邀请供应商总数'])[1]/preceding::label[2]</value>
      <webElementGuid>df6ee430-9e86-4aa6-bf55-fe9767215e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='现有供应商总数']/parent::*</value>
      <webElementGuid>47dc89b2-3ed3-4483-b80b-3f4b3a833d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/label</value>
      <webElementGuid>f65b9b41-da54-415e-856b-d0efec2ddcc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '现有供应商总数' or . = '现有供应商总数')]</value>
      <webElementGuid>8a41d449-6377-43df-8bd0-16c152bf092e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
