<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_DAG</name>
   <tag></tag>
   <elementGuidId>6a0bb350-7a6f-4a65-b935-d60293cd3bcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='daginfo']/div[2]/label[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.control-label.col-md-2.koreaHidden</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2c104dfd-34db-4b6c-a99d-683141d220c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-label col-md-2 koreaHidden</value>
      <webElementGuid>43d45c66-b2cc-444e-8f51-42632734479c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>T_SOURCE_DAG_NUMBER</value>
      <webElementGuid>d3519ea9-2748-49cb-a2a0-6fe43c9c4ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n-text</name>
      <type>Main</type>
      <value>dag_source_dag_number</value>
      <webElementGuid>718c1351-c2c2-4d54-8755-1356216a7cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>源DAG号</value>
      <webElementGuid>66a9b512-482b-44b7-9a4a-498a5535d7a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;daginfo&quot;)/div[@class=&quot;row&quot;]/label[@class=&quot;control-label col-md-2 koreaHidden&quot;]</value>
      <webElementGuid>bd9ea444-45eb-4c2b-b604-34b38ff53a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>d533b1ab-e43f-4c91-a9dd-5ec28dbe11e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='daginfo']/div[2]/label[3]</value>
      <webElementGuid>f0058e9c-dcdf-4b5f-8b25-de9b52712b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='版本号'])[1]/following::label[1]</value>
      <webElementGuid>68cd9e4d-1af8-4e6b-a310-85871188a294</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAG_ID'])[1]/following::label[2]</value>
      <webElementGuid>af7d96cd-8d68-4002-8e4f-dd5714dd2b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAG描述'])[1]/preceding::label[1]</value>
      <webElementGuid>1d3e621a-3013-47c7-81bf-2919727ef72e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/preceding::label[2]</value>
      <webElementGuid>4d914a5b-2785-4459-a5cf-5894e04a7549</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='源DAG号']/parent::*</value>
      <webElementGuid>e1d24924-bde0-4038-ae21-a054e13d96a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]</value>
      <webElementGuid>da8bd3bb-0682-4a36-8f8b-5d04774a35f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '源DAG号' or . = '源DAG号')]</value>
      <webElementGuid>64e81661-20ba-4aaa-819f-0889a97f27f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
