<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Budget</name>
   <tag></tag>
   <elementGuidId>3101f6ed-63ee-4c19-86b4-34cefdf4d3d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='daginfo']/div[11]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c995bdff-0802-483e-b6f8-1e404ee9af4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-label col-md-2</value>
      <webElementGuid>031f6ab5-9744-418e-b46e-c93c966df815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>T_BUDGET_AMOUNT</value>
      <webElementGuid>adffd8b9-3ce5-4d5c-9e4a-e145382391d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n-text</name>
      <type>Main</type>
      <value>T_BUDGET_AMOUNT</value>
      <webElementGuid>9f1f1ed3-c08a-4368-98ef-f8a7e1683b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>预算金额</value>
      <webElementGuid>eae005aa-9d71-451d-97cf-c9d9d131aa53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;daginfo&quot;)/div[@class=&quot;row koreaHidden&quot;]/label[@class=&quot;control-label col-md-2&quot;]</value>
      <webElementGuid>863959e8-5e9f-4927-9082-2fc59b146346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>d3e09dee-0fbd-45ba-bfe4-acb84ba0226b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='daginfo']/div[11]/label</value>
      <webElementGuid>f311ab98-96c6-4cc1-b043-3a9101c71995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[13]/following::label[1]</value>
      <webElementGuid>ba4fcb65-5b1f-4f54-b97e-0e37c422dc69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='如是请选择'])[1]/following::label[1]</value>
      <webElementGuid>7b5ace8f-9180-4978-8aac-2329fc88d25a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='预算节约'])[1]/preceding::label[1]</value>
      <webElementGuid>234373ae-6df5-4ac1-975d-bff69719f3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='前批总金额'])[1]/preceding::label[2]</value>
      <webElementGuid>f9b59f1c-daa7-47d1-a346-61112333a174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='预算金额']/parent::*</value>
      <webElementGuid>6b0a3ff1-b0af-475d-acfe-f7d4c17ce334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/label</value>
      <webElementGuid>9ac75d95-bcca-4e88-ba3c-851372599956</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '预算金额' or . = '预算金额')]</value>
      <webElementGuid>67747ac4-7ca9-4e02-ad61-04a294014dc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
