<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Auction Type</name>
   <tag></tag>
   <elementGuidId>6bee6024-56f4-410b-82bd-1e019cd84715</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='daginfo']/div[15]/label[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ba213391-0e51-4e23-b59e-3ffbd3a6c992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-label col-md-2</value>
      <webElementGuid>814120a6-0839-43ed-a035-2ff65256a16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>T_BIDDING_TYPE_CODE</value>
      <webElementGuid>f637897a-eb6c-4d04-9a7d-6546f52ec3b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n-text</name>
      <type>Main</type>
      <value>T_BIDDING_TYPE_CODE</value>
      <webElementGuid>1a160705-e317-46f9-89d4-0f5adb8574e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>竞标类型</value>
      <webElementGuid>65e43630-a831-4cc6-bdc5-6988f7b302c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;daginfo&quot;)/div[@class=&quot;row koreaHidden&quot;]/label[@class=&quot;control-label col-md-2&quot;]</value>
      <webElementGuid>cfe0b594-ff53-41e2-93a8-4b35a3603979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>101ec27e-9cb6-4a1b-9b4b-ade7670039bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='daginfo']/div[15]/label[2]</value>
      <webElementGuid>3028815c-f978-4868-a96a-540d7fa58ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='是否电子竞标'])[1]/following::label[1]</value>
      <webElementGuid>60c9fbeb-86f1-4bdb-bf25-6c1fb321ad87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='项目描述'])[1]/following::label[2]</value>
      <webElementGuid>4f836ef6-aaec-42c8-a945-87f957b41d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='现有供应商总数'])[1]/preceding::label[1]</value>
      <webElementGuid>cb5ab44a-7796-42a3-ab36-a439c9304f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='新供应商总数'])[1]/preceding::label[2]</value>
      <webElementGuid>c8cbaec4-c981-4d8c-bf39-5b5ccaa1bdd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='竞标类型']/parent::*</value>
      <webElementGuid>7d55ec36-49d3-46ce-93ea-36e0498f8e40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[15]/label[2]</value>
      <webElementGuid>a7ea226c-fb22-40ff-b23f-ae8019cea29a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '竞标类型' or . = '竞标类型')]</value>
      <webElementGuid>5b782c03-fbec-46a7-bb9a-cd6910165744</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
