<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Supplier Invited</name>
   <tag></tag>
   <elementGuidId>a0a94863-77c2-4911-b550-14585cf5eb01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='daginfo']/div[17]/label</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f9d7e414-7c3d-4ebb-943b-3d516d3df8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>control-label col-md-2</value>
      <webElementGuid>0eea6dce-216b-4344-a0b9-577c7f8cbaca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>T_VENDORS_QTY</value>
      <webElementGuid>6fde505e-73d0-4fdb-ad48-33fcb122e8d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n-text</name>
      <type>Main</type>
      <value>T_VENDORS_QTY</value>
      <webElementGuid>0ccd6ee2-bb24-4b26-9897-da0f7dc430ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>邀请供应商总数</value>
      <webElementGuid>0d94a3ea-ad28-426d-94fe-83c4bf57f3ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;daginfo&quot;)/div[@class=&quot;row koreaHidden&quot;]/label[@class=&quot;control-label col-md-2&quot;]</value>
      <webElementGuid>03827abb-9763-474f-ad65-cb861215f5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>dd51b0c8-7791-4f26-a050-9ad8f3748e0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='daginfo']/div[17]/label</value>
      <webElementGuid>9692ea6d-62f9-4b09-9480-826e33eafe7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='新供应商总数'])[1]/following::label[1]</value>
      <webElementGuid>1d0dd184-3f2b-4b16-92ba-ad1cc1b7220b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='现有供应商总数'])[1]/following::label[2]</value>
      <webElementGuid>69d50c10-0159-4692-bb41-63887f5a1526</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='需要独家供应商审批'])[1]/preceding::label[1]</value>
      <webElementGuid>0c157244-f97f-4ada-85b2-4fc798d8fc19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提示'])[1]/preceding::label[2]</value>
      <webElementGuid>6490940f-9aa9-43bc-aa13-0762aecde92b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='邀请供应商总数']/parent::*</value>
      <webElementGuid>7e6149a3-5924-40b6-a7f3-6548b8b32812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/label</value>
      <webElementGuid>adef23ca-e004-4a6f-bd29-7cf5855476ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '邀请供应商总数' or . = '邀请供应商总数')]</value>
      <webElementGuid>09245ece-8f2d-49cf-b2ea-3f1fb9355f8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
