<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_zhaobiaofile_DAG</name>
   <tag></tag>
   <elementGuidId>a86b39f9-879f-42df-9340-429407b1f7f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ui-tree-text.ui-tree-text-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='AttachTree']/li/span[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5c42ab44-0f5f-4049-bb6d-ac8e1249a05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-tree-text ui-tree-text-hover</value>
      <webElementGuid>3e2872e7-b5ca-4bdd-b21d-8218e075d0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>DAG</value>
      <webElementGuid>f082d0e0-050f-4b6d-8e1e-883dc22b2cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DAG</value>
      <webElementGuid>7457e7ef-0e5c-4b4e-8d6c-ea2e59b87113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AttachTree&quot;)/li[1]/span[@class=&quot;ui-tree-text ui-tree-text-hover&quot;]</value>
      <webElementGuid>4943b854-bffb-43fa-8470-0664ab20b2d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>3da24514-bc28-4202-991e-b2785bb0db32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='AttachTree']/li/span[3]</value>
      <webElementGuid>a6b32c19-da0d-471b-823a-de243746e81e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='※无法删除之前已提交的附件'])[1]/following::span[3]</value>
      <webElementGuid>1ea71e9a-371d-4dbb-9573-b2ba2a11c371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='关键词批导上传'])[1]/following::span[4]</value>
      <webElementGuid>22a159f2-ae4d-4db5-a7d7-4989a347e1e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOW'])[1]/preceding::span[3]</value>
      <webElementGuid>4407cde0-298a-4804-a0a7-740fef3e895f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RFQ'])[1]/preceding::span[6]</value>
      <webElementGuid>48ffa5d3-285d-41b8-bb54-da94679cc916</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DAG']/parent::*</value>
      <webElementGuid>37422575-b19d-4d04-8d3a-598d0646fc92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[3]</value>
      <webElementGuid>6c470a5e-3e90-4b60-bdc1-4418df95a2b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'DAG' and (text() = 'DAG' or . = 'DAG')]</value>
      <webElementGuid>ff9617f1-63ed-4d6c-a9f8-d28b7f33d532</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
