<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_zhaobiaofile_Others</name>
   <tag></tag>
   <elementGuidId>0cb13dd8-b353-4b43-b167-84726bf1365d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='AttachTree']/li[5]/span[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ui-tree-text.ui-tree-text-hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1098a99f-115b-4cba-b016-59b23874d942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-tree-text ui-tree-text-hover</value>
      <webElementGuid>f65fdceb-cd6c-49d3-a4b6-293b57b473ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Others</value>
      <webElementGuid>76594ff3-e9a2-44ed-8ae6-5797264db27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Others</value>
      <webElementGuid>d55093fd-341c-4aef-85a6-e6547bb450ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AttachTree&quot;)/li[5]/span[@class=&quot;ui-tree-text ui-tree-text-hover&quot;]</value>
      <webElementGuid>5b64bb54-95a0-4f6e-93d3-e10584355d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>86468288-21ef-4a8a-808e-24fc42cfba76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='AttachTree']/li[5]/span[3]</value>
      <webElementGuid>d048ca9a-a3fb-4a94-aca1-2209fe7ac883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contract'])[1]/following::span[3]</value>
      <webElementGuid>d1efa7ad-85f8-433a-a7d4-e23552ad8659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RFQ'])[1]/following::span[6]</value>
      <webElementGuid>d57c559c-2f30-42df-992c-4cd1eb441df5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CID'])[2]/preceding::span[1]</value>
      <webElementGuid>0f81e361-b930-4f0d-916f-55e0e314ce0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T_SUP_CID'])[1]/preceding::span[3]</value>
      <webElementGuid>509e9b8c-83da-4bed-ad00-bde03bdb518c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Others']/parent::*</value>
      <webElementGuid>7140fbd1-ea7a-4a69-ba67-293ed7802983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/span[3]</value>
      <webElementGuid>8bb37275-2001-48d8-b17f-ddbabbfe30cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'Others' and (text() = 'Others' or . = 'Others')]</value>
      <webElementGuid>2b4644f8-b757-443a-8e94-6d309881e31b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
