<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tab_zhaobiaofile</name>
   <tag></tag>
   <elementGuidId>b717add9-a176-4cf8-a372-7495a72f47b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.tabs-last > a.tabs-inner > span.tabs-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabs']/div/div[3]/ul/li[3]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4cec4399-d15a-43c7-9709-b6bd6a451628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tabs-title</value>
      <webElementGuid>53836723-6b58-4ed4-87cf-a7c65948c043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>招标文件</value>
      <webElementGuid>ef22f7c7-2044-48ba-90e5-7caba4be9e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabs&quot;)/div[@class=&quot;tabs-header tabs-header-noborder&quot;]/div[@class=&quot;tabs-wrap&quot;]/ul[@class=&quot;tabs&quot;]/li[@class=&quot;tabs-last&quot;]/a[@class=&quot;tabs-inner&quot;]/span[@class=&quot;tabs-title&quot;]</value>
      <webElementGuid>e21437c9-a38e-4f1e-a804-99a4a8d42f07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>c0063a94-3730-4658-9867-e3540e312ee6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabs']/div/div[3]/ul/li[3]/a/span</value>
      <webElementGuid>fcb943bf-9ea5-4a76-b67a-33ceb4a3574a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='条目数信息'])[1]/following::span[2]</value>
      <webElementGuid>fdc775a1-946f-4a62-b6d0-e89519ecdc56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAG信息'])[1]/following::span[4]</value>
      <webElementGuid>2adc8ed0-eb01-45f3-adf0-f7bbf7493cdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAG_ID'])[1]/preceding::span[2]</value>
      <webElementGuid>30101898-5593-4d18-bba3-cdc434b7dcd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='版本号'])[1]/preceding::span[3]</value>
      <webElementGuid>0d53e0ce-f305-48d4-8e2b-38196bf10ff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='招标文件']/parent::*</value>
      <webElementGuid>4406ccfb-e41f-4453-8cfc-65a8712a37dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/span</value>
      <webElementGuid>081860ac-b4e7-4068-959f-96e7400cda4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '招标文件' or . = '招标文件')]</value>
      <webElementGuid>60f67b6b-6274-4fab-a8dc-36b73d551fd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
