<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_13</name>
   <tag></tag>
   <elementGuidId>d71a4a8b-fc4a-4464-8b0c-8e2bbca37e09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.calendar-day.calendar-nav-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='六'])[7]/following::td[18]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>fda1b2d0-6e86-4ed7-92d6-831a32c39121</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>calendar-day  calendar-nav-hover</value>
      <webElementGuid>67571bc3-6bd3-4522-a680-9a460bf37d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>abbr</name>
      <type>Main</type>
      <value>2024,11,13</value>
      <webElementGuid>79f51b64-569b-4a0e-9f66-c6b1d21b5629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>4e3ed763-a466-4d58-80a7-00d011d47c83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;panel-fit&quot;]/body[@class=&quot;panel-noscroll&quot;]/div[@class=&quot;panel combo-p panel-htop&quot;]/div[@class=&quot;combo-panel panel-body panel-body-noheader&quot;]/div[@class=&quot;datebox-calendar-inner panel-noscroll&quot;]/div[@class=&quot;calendar calendar-noborder easyui-fluid&quot;]/div[@class=&quot;calendar-body&quot;]/table[@class=&quot;calendar-dtable&quot;]/tbody[1]/tr[3]/td[@class=&quot;calendar-day  calendar-nav-hover&quot;]</value>
      <webElementGuid>8cb3d184-867e-4b12-8974-7d8ec6fa9df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/DAG_add_page/iframe__ifm_1</value>
      <webElementGuid>b704995b-8ae9-418c-a4bf-754879a67ba1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='六'])[7]/following::td[18]</value>
      <webElementGuid>4422f375-23ec-46eb-8e2d-990b3c689eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='五'])[7]/following::td[18]</value>
      <webElementGuid>3843fffa-2d40-4f99-ac7f-cf0eed869c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='今天'])[3]/preceding::td[25]</value>
      <webElementGuid>2cbcd2ac-a8f5-4bb9-a293-3c808c3248a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='关闭'])[3]/preceding::td[26]</value>
      <webElementGuid>a94ce168-fab5-4c05-a5f9-6c6090585803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/div/div/div/div[2]/table/tbody/tr[3]/td[4]</value>
      <webElementGuid>8ebc71ca-dfb6-4cbf-a55e-8b38ed35d567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '13' or . = '13')]</value>
      <webElementGuid>f07f1dfc-6894-4e5a-bfb4-34c3885e2987</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
