<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_approvesubmit</name>
   <tag></tag>
   <elementGuidId>02d90fe2-b797-418d-a313-01dae1a0a23c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.btn.btn-default.btn-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@onclick='SaveApprovalData()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>61b38b40-6bb3-4641-b9b3-3f87dcf25cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm</value>
      <webElementGuid>92656f2c-af6b-42de-986e-aa0fd2356450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>SaveApprovalData()</value>
      <webElementGuid>95b51007-8ec2-46ca-bcf3-ad72c194fe69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n-text</name>
      <type>Main</type>
      <value>Batch_Submit</value>
      <webElementGuid>d9e5ed98-0fe9-4380-b51d-9b029145bd1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>提交</value>
      <webElementGuid>87f30ac1-ca1d-4231-be57-441a5d7e1474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divItemBg&quot;)/div[@class=&quot;divItemBgToolbarBg&quot;]/div[@class=&quot;divItemBgToolbar&quot;]/div[@class=&quot;form-group form-group-sm&quot;]/span[@class=&quot;btn btn-default btn-sm&quot;]</value>
      <webElementGuid>b6f05878-1da9-44ae-9502-ca74a72d9d4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@onclick='SaveApprovalData()']</value>
      <webElementGuid>60b3aa00-ef61-4091-b99b-6ba12ec9988a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divItemBg']/div/div/div[2]/span</value>
      <webElementGuid>c3f1b937-d07f-4ba5-919d-0ce52a3a0873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='批量提交【签署审批人审核】'])[1]/following::span[3]</value>
      <webElementGuid>c0f67370-ef14-4028-ac58-a9c5801d8d49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='共计 2 合同条目,目前已展示 2 条！'])[1]/preceding::span[1]</value>
      <webElementGuid>3cf694a6-4a3d-4b3e-9707-5198854de76c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO.0001'])[1]/preceding::span[2]</value>
      <webElementGuid>cb29b300-80e2-4138-abee-6a38e0cb65c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='提交']/parent::*</value>
      <webElementGuid>70bcf834-b243-43ef-9092-368b1828d4cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span</value>
      <webElementGuid>716d3fce-e51c-4e8d-bf0d-5791137ec9c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '提交' or . = '提交')]</value>
      <webElementGuid>f1b51f7f-36e1-4250-aa24-b095b3ac9193</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
