<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_applyapproveallcontract</name>
   <tag></tag>
   <elementGuidId>4a4e0553-cf88-4532-9d56-4d7718cc90fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-md-2 > div.divItemBgToolbar > div.form-group.form-group-sm > span.btn.btn-default.btn-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@onclick='quickFilling(0)']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6c612c7b-6c5a-4b57-a533-36ef25060062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm</value>
      <webElementGuid>e06dd6cd-5893-45f5-9f57-b55502612878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>quickFilling(0)</value>
      <webElementGuid>8f3d22f0-1fbb-4907-92d9-85915419f68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>本模块应用到所有合同</value>
      <webElementGuid>d9319029-e5ca-4d87-bd79-f9ff2c87c11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_dcd50019-fa9e-47e8-8bd2-7bedce928bb1&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-md-2&quot;]/div[@class=&quot;divItemBgToolbar&quot;]/div[@class=&quot;form-group form-group-sm&quot;]/span[@class=&quot;btn btn-default btn-sm&quot;]</value>
      <webElementGuid>ee495623-bbbc-47fb-ad83-e611e8c375fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@onclick='quickFilling(0)']</value>
      <webElementGuid>90d855ea-a546-4c22-a4cf-bddc2f7a811b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_dcd50019-fa9e-47e8-8bd2-7bedce928bb1']/div[8]/div[3]/div/div/span</value>
      <webElementGuid>8946fd1b-aa36-48c6-b8a4-f869b81d1e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='审批意见'])[1]/following::span[1]</value>
      <webElementGuid>968f383b-a4ba-4719-9d06-bc8aa53f7e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='退回'])[1]/following::span[1]</value>
      <webElementGuid>8d1dafba-becc-4f92-9233-6dc5cfdf3cb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO.0002'])[1]/preceding::span[1]</value>
      <webElementGuid>fb869187-ec8b-41f8-941c-9091c1fc11bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='申请人'])[2]/preceding::span[4]</value>
      <webElementGuid>5719c237-274b-4d6a-9d37-92819cdfe6bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='本模块应用到所有合同']/parent::*</value>
      <webElementGuid>2c852bfe-c5c8-490a-8141-1a2ed15cb0cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span</value>
      <webElementGuid>6391a168-6241-4dc4-ad89-3eb133cb4603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '本模块应用到所有合同' or . = '本模块应用到所有合同')]</value>
      <webElementGuid>a3463b4d-a0b5-422d-9046-1262e82da5d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
