<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_signapprover_submit</name>
   <tag></tag>
   <elementGuidId>3674e55b-6ad4-4933-81ea-f20ddd578b19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.btn.btn-default.btn-sm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@onclick='SaveApprovalData()']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b6993ca7-0afb-4316-bd3e-944bca171d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm</value>
      <webElementGuid>ad1c8c80-c4cd-4b77-8077-6a4d679f14ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>SaveApprovalData()</value>
      <webElementGuid>e891e23a-9872-4721-b2e8-56ef516efeb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n-text</name>
      <type>Main</type>
      <value>Batch_Submit</value>
      <webElementGuid>e7d306f9-a6d4-47cd-a2e6-808f426edb5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>提交</value>
      <webElementGuid>c4287a37-1e08-4c96-8f92-3425de5a446c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divItemBg&quot;)/div[@class=&quot;divItemBgToolbarBg&quot;]/div[@class=&quot;divItemBgToolbar&quot;]/div[@class=&quot;form-group form-group-sm&quot;]/span[@class=&quot;btn btn-default btn-sm&quot;]</value>
      <webElementGuid>dfd0f3e8-980b-4862-8dd9-b7ca06cde37a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@onclick='SaveApprovalData()']</value>
      <webElementGuid>1d003add-695b-4c6d-aeff-4785638bebe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divItemBg']/div/div/div[2]/span</value>
      <webElementGuid>08e07e08-b513-48bf-8fa6-abddaceeba26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='批量提交【签署审批人审核】'])[1]/following::span[3]</value>
      <webElementGuid>1f3224f3-828f-46a2-bbd1-2f3981515c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='共计 2 合同条目,目前已展示 2 条！'])[1]/preceding::span[1]</value>
      <webElementGuid>138760d3-6dff-4a6c-9897-d6fa475aa89e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO.0001'])[1]/preceding::span[2]</value>
      <webElementGuid>06cfb79c-c36c-43f4-8eb4-b74b612bf226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='提交']/parent::*</value>
      <webElementGuid>50f6c215-53c0-45d3-abd9-6a40cd54cc76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/span</value>
      <webElementGuid>15c2e3ae-001f-47aa-8140-0d1f7b5ab2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '提交' or . = '提交')]</value>
      <webElementGuid>f3fc9d55-143b-402e-a6a9-c470ddc4d3dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
