<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_rejectcontent_row1</name>
   <tag></tag>
   <elementGuidId>4c4a9d63-6258-4753-9f5f-a6a8c094ccbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#spyj_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='spyj_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e64aa12b-26c9-4b6b-a139-136aa52db6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>47d914d9-4b58-49a7-bbc2-ec522ddb6ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control input-sm</value>
      <webElementGuid>8478b7c4-2204-4f9b-976d-1b445aa00506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>spyj_0</value>
      <webElementGuid>935291e9-6657-41e1-961a-52f5fad12ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spyj_0&quot;)</value>
      <webElementGuid>ce9113fe-4415-45e2-a137-30756016cb41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='spyj_0']</value>
      <webElementGuid>02575c72-89c5-49e2-81a6-ba2dbe9277b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_a2e68e26-079c-4c5b-999f-6f60f191dd3d']/div[8]/div[2]/input</value>
      <webElementGuid>1fdb8be5-4762-4e0c-b796-00a5a3f77415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/input</value>
      <webElementGuid>55f3dcdf-dcdd-492a-9562-d8a377877f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'spyj_0']</value>
      <webElementGuid>00b4c88f-313d-4520-825b-3bad37e933c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
