<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__chk</name>
   <tag></tag>
   <elementGuidId>d7aeae3e-df99-42f2-8acc-3a6f70ccb3dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='1aee201d-fb89-4411-a1b1-aa6c50889c3a']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.chk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff739fdf-59c7-4937-99e8-2b18a13c74b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>a51dcfd4-423b-4af4-b04b-7aa4cd0f54b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>6cd2e451-79cb-473f-820a-c91f23d441cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1aee201d-fb89-4411-a1b1-aa6c50889c3a</value>
      <webElementGuid>68a60ea3-1a68-48c7-9397-a0035a432eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbGrid&quot;)/tbody[@class=&quot;hidden_768&quot;]/tr[1]/td[@class=&quot;chkBox&quot;]/input[@class=&quot;chk&quot;]</value>
      <webElementGuid>05ac36f3-8612-44a3-942f-14d60e3911f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/NeedToDoTask/Batchapprove_page/iframe</value>
      <webElementGuid>b60a4d10-edd3-4cd4-9bf9-c91e76ce98ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='1aee201d-fb89-4411-a1b1-aa6c50889c3a']</value>
      <webElementGuid>950b1000-2c34-4a62-b7d8-703902c13869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tbGrid']/tbody/tr/td[2]/input</value>
      <webElementGuid>bf798b6d-a762-4f14-8092-7a4617edb588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>fef27a0a-beac-4749-a2c8-0c3455c0da38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>15c208f4-8fde-4dc3-9ce3-ecce044c8e80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
