<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_row1_reject</name>
   <tag></tag>
   <elementGuidId>9fa7fdc4-9773-4a1d-8681-9dcdf460a91a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='spjg_0'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>315fcf08-7afc-4bd4-a4a1-844cdb1aefcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0feeded9-9228-48ee-abe8-62b82e01274e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>spjg_0</value>
      <webElementGuid>b692c761-642d-48ec-a0c0-40d8f9494228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>12af435c-e422-4f3c-9f92-c4ca461794b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div_dcd50019-fa9e-47e8-8bd2-7bedce928bb1&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-md-2&quot;]/input[2]</value>
      <webElementGuid>33c1bc28-1678-442d-8593-ea6d41663cae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='spjg_0'])[2]</value>
      <webElementGuid>5c61bd69-2587-4f77-a1ef-9c476aa0ec16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_dcd50019-fa9e-47e8-8bd2-7bedce928bb1']/div[8]/div/input[2]</value>
      <webElementGuid>2f4470bd-b26a-44b1-8d51-5bc15084e4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input[2]</value>
      <webElementGuid>bf0f0b1e-cf33-416c-83ed-26940810d018</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'spjg_0']</value>
      <webElementGuid>ae9f33ab-b3b0-483c-a8af-c7497cfe8714</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
