<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_internalconsult</name>
   <tag></tag>
   <elementGuidId>13fdf874-07e4-4256-9e9f-63e068bf0fca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='addForm']/div/div[2]/div[16]/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col-md-11 > span.radiobutton.inputbox</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>55c52a1b-d141-48ee-85d7-a3345cc9876b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radiobutton inputbox</value>
      <webElementGuid>0f172038-66aa-4a64-9070-ab7bd6ab8370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addForm&quot;)/div[@class=&quot;panel panel-htop easyui-fluid&quot;]/div[@class=&quot;easyui-panel panel-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-11&quot;]/span[@class=&quot;radiobutton inputbox&quot;]</value>
      <webElementGuid>f337a4cc-49ae-49b1-a456-0e21973f1e81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='addForm']/div/div[2]/div[16]/div/span</value>
      <webElementGuid>fafc6a99-3e85-4fab-8e63-9b38a0ffec86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提交到'])[1]/following::span[1]</value>
      <webElementGuid>581303b4-31ab-4aaf-9155-386ed8c91cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='本模块应用到所有合同'])[2]/following::span[1]</value>
      <webElementGuid>9208a577-9912-49da-973e-737a2f302772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='内部磋商'])[1]/preceding::span[2]</value>
      <webElementGuid>b4f560b4-c5a8-48f0-ae6e-413005342fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='外部磋商'])[1]/preceding::span[4]</value>
      <webElementGuid>fa620fb8-fbcc-4729-9c2f-e5314d989dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div/span</value>
      <webElementGuid>bc3ad077-f37e-412e-963a-16ad7abf865b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
