<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_total</name>
   <tag></tag>
   <elementGuidId>a31b39ff-60d6-4520-9cfe-c9f28dd9b348</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#spanCount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='spanCount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>991885d6-33b2-4524-a0a5-85d73897b5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>spanCount</value>
      <webElementGuid>1c7b6f2d-46af-469a-9188-86ddc09a86fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>共计 2 合同条目,目前已展示 2 条！</value>
      <webElementGuid>a22d2066-0e09-4fd0-a4ba-4596c7a78fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spanCount&quot;)</value>
      <webElementGuid>3c226f06-7fbc-4816-998e-e3fd41313e16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='spanCount']</value>
      <webElementGuid>cfbe0a68-e692-4cbc-9119-76a04fc1f08f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divItemBg']/div/div[2]/span</value>
      <webElementGuid>e62fd34d-74cd-4206-8bde-6d9a3e4aa4f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提交'])[1]/following::span[1]</value>
      <webElementGuid>7b70e196-06ae-440b-8e8a-699a397b251d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='批量提交【签署审批人审核】'])[1]/following::span[4]</value>
      <webElementGuid>8e4e0ad0-1d87-4866-87cf-1be53673d137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO.0001'])[1]/preceding::span[1]</value>
      <webElementGuid>447e5cd8-bdc6-45a4-a437-ccb99aa5d25d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='申请人'])[1]/preceding::span[4]</value>
      <webElementGuid>b86a5cd9-2a29-4d32-820d-ad80ecb14aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='共计 2 合同条目,目前已展示 2 条！']/parent::*</value>
      <webElementGuid>2624402e-d1ad-4774-990b-21d79f9f4d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/span</value>
      <webElementGuid>23516ba9-c7d8-4623-a667-85e67eaa7fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'spanCount' and (text() = '共计 2 合同条目,目前已展示 2 条！' or . = '共计 2 合同条目,目前已展示 2 条！')]</value>
      <webElementGuid>cb716f02-c5f3-4bd1-ab24-5cd6a58cf850</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
