<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_contractno_row1</name>
   <tag></tag>
   <elementGuidId>b112f462-3abf-47ae-a806-161bb5f48433</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#htbh_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='htbh_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>99d49fdf-5046-4ef5-b305-ca4dd558f4f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>htbh_0</value>
      <webElementGuid>d590dc1b-5de4-49a8-947b-80f334ea1668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CON-COM-20231122-002M</value>
      <webElementGuid>14eab4e2-e0b4-4d12-b6cd-162c543ed3ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;htbh_0&quot;)</value>
      <webElementGuid>1f459525-5235-4c72-a835-f858f19194d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='htbh_0']</value>
      <webElementGuid>d0c25ecc-73cc-4654-910f-8343db5bae13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_a2e68e26-079c-4c5b-999f-6f60f191dd3d']/div[4]/div/p/span</value>
      <webElementGuid>4f74e3c1-a542-4592-95be-73c51edfd3fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='合同编号'])[1]/following::span[1]</value>
      <webElementGuid>a973eeee-6cf8-4947-93e4-b494675f0350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='合同金额(不含税)'])[1]/following::span[2]</value>
      <webElementGuid>de61d617-d1bd-4f0f-8669-bd24080b4653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='合同名称'])[1]/preceding::span[1]</value>
      <webElementGuid>0844e635-36cc-4140-9878-1610a3383be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='测试批量发起-草稿'])[1]/preceding::span[1]</value>
      <webElementGuid>bfa62d09-a990-4db9-be57-06a7f50ec158</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CON-COM-20231122-002M']/parent::*</value>
      <webElementGuid>49d2e5c8-adf8-4c38-a636-3ba0bec5f002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/p/span</value>
      <webElementGuid>a46b7339-1906-42df-b05c-fb5224f80dfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'htbh_0' and (text() = 'CON-COM-20231122-002M' or . = 'CON-COM-20231122-002M')]</value>
      <webElementGuid>91ac4818-1830-4e68-978c-d14f2e277f72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
