<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_viewmore</name>
   <tag></tag>
   <elementGuidId>f4150dc7-ac65-488b-80e2-daae69136dfb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnMoleSet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='btnMoleSet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd2892b6-9b42-4925-9c85-d2e52deae56b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link btnMoleSet</value>
      <webElementGuid>74c3ccd7-1505-43fc-b22d-a5ec08a1b4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnMoleSet</value>
      <webElementGuid>7d2e6092-69d4-412b-b532-f379aa7831ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>折叠</value>
      <webElementGuid>20712c81-4a15-4ca1-9880-f47314f853bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>点击查看更多</value>
      <webElementGuid>27e4e592-969b-4884-a142-b59026e1793c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnMoleSet&quot;)</value>
      <webElementGuid>db396589-1952-474a-8e34-2cefbdcf7fb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='btnMoleSet']</value>
      <webElementGuid>43102b44-527f-4461-b6ca-e5b50b15932e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divItemBg']/div[4]/span</value>
      <webElementGuid>1d5da4c7-9201-43c4-8866-cba070d4f341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='本模块应用到所有合同'])[7]/following::span[1]</value>
      <webElementGuid>c3f564e7-bf4e-4d03-ba37-d34be33f7163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='审批意见'])[7]/following::span[2]</value>
      <webElementGuid>b7d6c567-6b17-43c1-bdbd-8dec5abb8089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'btnMoleSet', '&quot;', ')')])[1]/preceding::span[1]</value>
      <webElementGuid>07c362cf-ba51-42e0-94e9-f4545b0ad6b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='点击查看更多']/parent::*</value>
      <webElementGuid>e474c774-f135-425e-9ff4-eb9af84c7a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/span</value>
      <webElementGuid>525954ac-dd36-4406-aeb6-af3dacc307f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'btnMoleSet' and (text() = '点击查看更多' or . = '点击查看更多')]</value>
      <webElementGuid>df53a006-b562-4e9f-bc5a-cb229beb69a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
