<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_contractno_row2</name>
   <tag></tag>
   <elementGuidId>da68bf7e-0742-4dbe-b27f-20617dbef80f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#htbh_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='htbh_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2c082d33-f7a4-4554-b46a-de0cd6ca2287</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>htbh_0</value>
      <webElementGuid>2f61afdc-e577-436b-ac99-1b4ba8772e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CON-COM-20231122-002M</value>
      <webElementGuid>362f3c6e-1110-4cf7-97f5-0c06ff2fbcf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;htbh_0&quot;)</value>
      <webElementGuid>bd5d5bdf-4603-4e8d-831a-a9d643497d44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='htbh_1']</value>
      <webElementGuid>45a89eeb-1f92-4ec7-8f85-0552660c099e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_64e36d59-4ad9-4f2a-979a-f742aba362be']/div[4]/div/p/span</value>
      <webElementGuid>a5adc24b-9aa6-4e54-8fef-408b7f48b3cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='合同编号'])[2]/following::span[1]</value>
      <webElementGuid>466a11b8-6629-485a-b91b-b7085a30bfad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='合同金额(不含税)'])[2]/following::span[2]</value>
      <webElementGuid>d41f19b3-91fc-4cc0-a92b-9b3c11f802ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='合同名称'])[2]/preceding::span[1]</value>
      <webElementGuid>5b81c78c-0293-42c9-b1d2-2c18411ea9a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='测试批量发起-草稿'])[2]/preceding::span[1]</value>
      <webElementGuid>0e30dd30-ea6c-4451-80d3-ac8f2192d963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CON-COM-20231122-001M']/parent::*</value>
      <webElementGuid>ce9a167c-163a-439a-af4c-194fce73fb65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>(//div[4]/div/p/span)[4]</value>
      <webElementGuid>b3f4f72b-8af7-4e8d-a066-96f2a755b469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'htbh_1' and (text() = 'CON-COM-20231122-001M' or . = 'CON-COM-20231122-001M')]</value>
      <webElementGuid>c8a31e63-4ed6-4d46-9997-3d7219158194</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
