<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_internalconsultremark</name>
   <tag></tag>
   <elementGuidId>019e2528-4926-4135-8b09-ad094f21f56a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='_easyui_textbox_input2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_easyui_textbox_input2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d874b610-28aa-4605-99e2-31d664feb549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_easyui_textbox_input2</value>
      <webElementGuid>4842b884-bce3-48bf-a068-e84945bfeb5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-text validatebox-text</value>
      <webElementGuid>6cd66042-3014-46f0-b048-a702f5431be6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>61d16429-acc4-4f09-a1af-2a7d829c030c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_easyui_textbox_input2&quot;)</value>
      <webElementGuid>dd87f931-b436-4301-ad23-82fb46e98e20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='_easyui_textbox_input2']</value>
      <webElementGuid>2f248a6b-e6b8-4db8-8c5d-925527980b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='FastAppSummary']/div[2]/div/span/textarea</value>
      <webElementGuid>6f712bb8-c50e-4781-a3ab-dce612e9566b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/span/textarea</value>
      <webElementGuid>f8a5ec76-02a0-42fe-94da-1481e7f219d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = '_easyui_textbox_input2']</value>
      <webElementGuid>03c79988-d66f-4576-95b6-0f8f7b0db496</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
