<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_export</name>
   <tag></tag>
   <elementGuidId>8e0446da-6c9c-43d8-9f8c-09a6a8ebf1e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.l-btn-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DATASearchToolBar']/div/div/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>46a5d98e-211c-46d2-b135-f2354df2fa46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>l-btn-text</value>
      <webElementGuid>691ae599-2cdd-4acf-b654-866a801a9f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>导出</value>
      <webElementGuid>5284c2d6-5ce6-4e8c-88a9-fb4404a8b7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DATASearchToolBar&quot;)/div[@class=&quot;tbBeforeBox row&quot;]/div[@class=&quot;btn-group pull-left toolBox&quot;]/span[@class=&quot;easyui-linkbutton l-btn l-btn-small&quot;]/span[@class=&quot;l-btn-left&quot;]/span[@class=&quot;l-btn-text&quot;]</value>
      <webElementGuid>ee528390-8028-4d66-992a-c795d020e83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/AuthorizeRecord/iframe__ifm</value>
      <webElementGuid>55671c34-ff78-411f-8fb7-e7149c42fbf7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DATASearchToolBar']/div/div/span/span/span</value>
      <webElementGuid>6fee458c-b763-4f27-922a-465a8efdee5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='授权记录'])[1]/following::span[3]</value>
      <webElementGuid>84beb6bf-c62e-4785-95d1-3dcbe2675f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='合同签署'])[1]/following::span[3]</value>
      <webElementGuid>625458f5-f134-45af-a3f7-06b7202b5261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CID'])[1]/preceding::span[2]</value>
      <webElementGuid>65771b9f-1969-4b57-b9ab-b1df10dd8852</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T_UPDATE_USERNAME'])[1]/preceding::span[4]</value>
      <webElementGuid>18f4a286-03fe-46f5-af3a-1cd553280502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='导出']/parent::*</value>
      <webElementGuid>4e8588bc-c4ba-4bf8-a22d-abca8a6a18fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span</value>
      <webElementGuid>0f353e07-4c12-4042-8d06-c4bbe81defaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '导出' or . = '导出')]</value>
      <webElementGuid>8c7c9921-6596-4dfb-a6e9-5e7595377cf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
