<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_record_search</name>
   <tag></tag>
   <elementGuidId>443345e6-e50b-471e-ab30-9d0400d65b73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.form-control.selech</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0c6f8071-11cf-4bf5-822f-b3d2a7d2b106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d9cd595a-c2cc-4bcb-9c12-b613da4ec2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control selech</value>
      <webElementGuid>43864fc5-c1e8-48fa-ab4b-65fe3c9dd74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DAG编号,DAG描述,合同编号,合同名称,被变更人,操作人</value>
      <webElementGuid>04fe5294-2f9c-44ac-8b90-619149a4c681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>DAG编号,DAG描述,合同编号,合同名称,被变更人,操作人</value>
      <webElementGuid>761eab41-6e81-4005-aa4b-6b42e1de5052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DATASearchToolBar&quot;)/div[@class=&quot;tbBeforeBox row&quot;]/div[@class=&quot;input-group pull-right group searchBox input-group-sm&quot;]/input[@class=&quot;form-control selech&quot;]</value>
      <webElementGuid>611ca159-220f-403a-ae2f-fc9b90e2b991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/AuthorizeRecord/iframe__ifm</value>
      <webElementGuid>76bfd9d8-221a-4932-a89c-f42028d7147d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>fc88d0a8-500c-47d6-a245-199ccdc30234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DATASearchToolBar']/div/div[2]/input</value>
      <webElementGuid>725e5797-635a-47e2-9135-9d30018c06f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9ac7c07b-0d53-4118-a0c8-b1d4a21a6f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'DAG编号,DAG描述,合同编号,合同名称,被变更人,操作人' and @title = 'DAG编号,DAG描述,合同编号,合同名称,被变更人,操作人']</value>
      <webElementGuid>db015a88-195a-4324-aa9a-ced7529b5b5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
