<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_submitorreject_legal</name>
   <tag></tag>
   <elementGuidId>178f6a48-4518-452f-949c-3012eb204c71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnFWSend']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnFWSend</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9d469362-a631-4357-8ee6-53b12c9e2415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>05aaac4f-4543-43c6-b1c6-0b2fdee77517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnFWSend</value>
      <webElementGuid>52f53aa5-46fd-4e53-a3d2-3832ceb686c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default pull-left btn-sm btnBlueColor</value>
      <webElementGuid>a96c1587-6461-48f6-a79c-70e77aab4c8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n-text</name>
      <type>Main</type>
      <value>paprobasicmsg_submit1</value>
      <webElementGuid>5f65de74-487b-4c1c-bba2-3e7945e3ca43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>提交or退回</value>
      <webElementGuid>a9e9e266-dcb0-4a8f-bfa1-d46edeb687d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnFWSend&quot;)</value>
      <webElementGuid>d99c55f9-9776-4e54-b3c1-2dbd28123309</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnFWSend']</value>
      <webElementGuid>6c30b0b7-3375-426e-b52f-1ef8107a8f32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='单据号:OA-DZHTQS-20231207-005'])[1]/following::button[1]</value>
      <webElementGuid>232e995a-2e38-4888-991d-f6289413e04e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='签署流程'])[1]/following::button[1]</value>
      <webElementGuid>45fc43b5-6d5f-4ae8-98c8-ee5d36dce620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='法务内部磋商/外部律师审核'])[1]/preceding::button[1]</value>
      <webElementGuid>882e66fa-c0ea-4771-9ab8-fca10966e2b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='关闭'])[1]/preceding::button[2]</value>
      <webElementGuid>33415a15-d7f4-4637-91c2-d040d8d011d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='提交or退回']/parent::*</value>
      <webElementGuid>bb740feb-ed8e-4001-9cec-82bd85fd3c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>055745a5-aca9-4a14-ae07-ba00503fa687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnFWSend' and (text() = '提交or退回' or . = '提交or退回')]</value>
      <webElementGuid>e1c815a4-8ef6-4d8e-b9f8-7d54b3f3db65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
