<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_legalapproveremark</name>
   <tag></tag>
   <elementGuidId>8e3c6e9c-1088-4317-86ce-f6b778b0e300</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='_easyui_textbox_input82']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_easyui_textbox_input82</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>9e27d265-61de-4b82-bceb-da0887003f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_easyui_textbox_input82</value>
      <webElementGuid>177b2b01-be68-4d72-b1ea-02366e7ab8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbox-text validatebox-text</value>
      <webElementGuid>2b4e4062-bb9a-4717-bbcf-9b8b66171fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f169a199-967c-4039-90e8-5ccb11e18852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_easyui_textbox_input82&quot;)</value>
      <webElementGuid>5299e473-d2d2-4d02-89af-bd4a0311e73a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='_easyui_textbox_input82']</value>
      <webElementGuid>cb6bff87-915a-4839-8c27-3824dc828601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSpjlDiv']/div[3]/div/span/textarea</value>
      <webElementGuid>c57ce604-b938-46be-84ef-9a4716cae9bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/span/textarea</value>
      <webElementGuid>a7dc7ba5-9554-43d4-8722-d708982eb163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = '_easyui_textbox_input82']</value>
      <webElementGuid>c6694fc2-1383-4c95-b3af-af461a7cd8e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
