<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_contract_drfatbox</name>
   <tag></tag>
   <elementGuidId>9ef7d7e0-7b83-464a-937e-f974e6592ba3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.ultrawidehide > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='t_drafts']/tbody/tr/td[5]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>06d1f924-6649-4d1d-ac0e-4a502cba4e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>45c0d78d-e6bc-476a-94db-0d0b7f21539c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>【批量起草】合同签署流程</value>
      <webElementGuid>de61db2a-590b-4484-a219-3f0ae2c26933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_drafts&quot;)/tbody[@class=&quot;hidden_768&quot;]/tr[1]/td[5]/div[@class=&quot;ultrawidehide&quot;]/a[1]</value>
      <webElementGuid>8f7ba904-29fa-4ac1-b62e-b9c2d6a8b9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DraftBox/iframe_concat(id(, , CGXFram, , ))_CGXFram</value>
      <webElementGuid>c123693b-dbe9-400a-9ebd-b75cf0d348d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='t_drafts']/tbody/tr/td[5]/div/a</value>
      <webElementGuid>fbdce60f-f6cf-4243-ba6f-ebf986f56118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'【批量起草】合同签署流程')]</value>
      <webElementGuid>b75d6674-26be-47f5-a790-ceaec2a1b5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='编辑'])[2]/following::a[1]</value>
      <webElementGuid>115ff7f0-e0b3-44e5-ade6-0bb9abc83665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='autotest_add_批量测试'])[1]/preceding::a[1]</value>
      <webElementGuid>f34a5ed8-cad0-4584-89ff-19466aceb1eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='编辑'])[3]/preceding::a[1]</value>
      <webElementGuid>a7504b28-7c22-404f-afb3-a9d2b448b6a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='【批量起草】合同签署流程']/parent::*</value>
      <webElementGuid>0fe27fbc-0f59-4aff-977c-283d4eb37c1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:;')]</value>
      <webElementGuid>c835798b-6ced-4b63-a422-e4e23e911a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/div/a</value>
      <webElementGuid>b42a00ef-e2a0-4c98-9d2c-cae9ae5cafaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = '【批量起草】合同签署流程' or . = '【批量起草】合同签署流程')]</value>
      <webElementGuid>4c740aeb-d910-445d-b26f-250641da951c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
