<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_delete</name>
   <tag></tag>
   <elementGuidId>aff1eea2-a5c7-4e45-a68e-a0058416eb46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form1']/div[3]/div[2]/div/div/div/div/div/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>06b1d987-d7b0-4055-833c-da0ab111b323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-sm</value>
      <webElementGuid>808b51fe-3bfa-4a89-b0e1-f2b7dd4df218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>删除</value>
      <webElementGuid>93a4e3c2-8759-43f3-8109-6bc85413c2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form1&quot;)/div[@class=&quot;form-group&quot;]/div[@class=&quot;divContent&quot;]/div[@class=&quot;col-md-12&quot;]/div[@class=&quot;formBg&quot;]/div[@class=&quot;tbContainer container&quot;]/div[@class=&quot;tbBeforeBox row&quot;]/div[@class=&quot;btn-group pull-left toolBox&quot;]/span[@class=&quot;btn btn-default btn-sm&quot;]</value>
      <webElementGuid>0519ae0e-5ebc-4963-a445-61c6d2bef999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DraftBox/iframe_concat(id(, , CGXFram, , ))_CGXFram</value>
      <webElementGuid>832e6f77-d85b-45c1-9a04-c05037ca70ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form1']/div[3]/div[2]/div/div/div/div/div/span[2]</value>
      <webElementGuid>88fd6256-3420-4aba-9ff5-47742d069e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='编辑'])[1]/following::span[1]</value>
      <webElementGuid>f44c13a6-6d34-48c0-b2f5-5e28be709445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='草稿箱'])[2]/following::span[2]</value>
      <webElementGuid>d9a18b43-8ab9-4602-86e1-8bd03f417a35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='刷新'])[1]/preceding::span[1]</value>
      <webElementGuid>5eb23fc2-3596-4933-9c26-5fbb9bd6e37d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='删除']/parent::*</value>
      <webElementGuid>3d935c92-b4b9-4e08-b1af-8f76fea48c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]</value>
      <webElementGuid>51364970-9f6f-443f-87b9-4a057bb28e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '删除' or . = '删除')]</value>
      <webElementGuid>d6a76b57-0f72-4702-a370-db853b9d5199</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
