<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_autotest_add_</name>
   <tag></tag>
   <elementGuidId>2e51ee39-ea4d-4137-b8b8-dfcf3538e096</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='t_drafts']/tbody/tr/td[6]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(6) > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>74312360-ff68-46ad-8d76-07187a308c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>autotest_add_批量测试</value>
      <webElementGuid>99747101-7e7e-4fa0-ba62-ee0b29146a8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_drafts&quot;)/tbody[@class=&quot;hidden_768&quot;]/tr[1]/td[6]/div[1]</value>
      <webElementGuid>3021a96a-968f-4746-9835-ebdd40b93d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DraftBox/iframe_concat(id(, , CGXFram, , ))_CGXFram</value>
      <webElementGuid>44641a2f-e10a-452f-80e5-1e7aadeca2f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='t_drafts']/tbody/tr/td[6]/div</value>
      <webElementGuid>cb46cfb4-2ce5-43e9-bda2-f1d6ea0913b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='【批量起草】合同签署流程'])[1]/following::div[1]</value>
      <webElementGuid>0679f88e-5deb-4361-93e2-acf166fe4695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='编辑'])[2]/following::div[2]</value>
      <webElementGuid>3c25cf3c-8e3b-40d7-80d0-84744cd52ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='编辑'])[3]/preceding::div[2]</value>
      <webElementGuid>52a998c4-40e7-4d26-98b9-1c5ca31cbb55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='流程名称'])[3]/preceding::div[3]</value>
      <webElementGuid>f784fb21-a0b4-4e8f-92fb-cc03731fca2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='autotest_add_批量测试']/parent::*</value>
      <webElementGuid>117658e7-f34c-443b-a441-0d682e0be899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/div</value>
      <webElementGuid>46823f97-f313-4074-9208-9a386d8b6be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'autotest_add_批量测试' or . = 'autotest_add_批量测试')]</value>
      <webElementGuid>a0747ae0-b11b-4f76-9741-246f96ae7cac</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
