<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_concat(id(, , CGXFram, , ))_CGXFram</name>
   <tag></tag>
   <elementGuidId>ab6a058a-2c69-4995-aaa5-700c5e820a8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='CGXFram']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CGXFram</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5d5f9d4e-3244-4756-83bd-b5c3363ae68c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CGXFram</value>
      <webElementGuid>4820f6d4-657d-4084-acc6-bcadade7d360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CGXFram</value>
      <webElementGuid>9400c2ae-f3cf-4fd1-b000-f182bc1d86fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>b135515a-d051-45bf-bad7-471e6ac2d3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/CTP/ProcessCenter/DraftsBox.aspx</value>
      <webElementGuid>f198551d-edf3-43d1-affc-a146aa9ebbf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CGXFram&quot;)</value>
      <webElementGuid>f77e867b-ab1b-448d-ba81-75abba01d733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DraftBox/iframe__ifm</value>
      <webElementGuid>16a1969e-26cd-43e6-a864-acd08d3689d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='CGXFram']</value>
      <webElementGuid>f1f8b048-7d83-4683-b290-a139f514e215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7267afdd-7cc6-40c7-808d-f2f4682aa28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'CGXFram' and @name = 'CGXFram' and @src = '/CTP/ProcessCenter/DraftsBox.aspx']</value>
      <webElementGuid>6e1ffcc5-016d-470f-a582-cab45af52a83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
