<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__ifm</name>
   <tag></tag>
   <elementGuidId>b4435a5f-511d-454a-930a-704365556a9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ifm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>86767395-66eb-4da7-ab6b-2340931ce94d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifm</value>
      <webElementGuid>dd2af0fe-741e-4ecf-991d-ae850fba46c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>2f4a2f27-8b30-4396-ad36-de1a589b375c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>1bb8ffb4-d5c9-48d4-8072-2a4db1b11903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ifm</value>
      <webElementGuid>b70ef935-9db7-4a9f-bfb5-d275b09fbd5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DASContract/Process/Page/ContractCaogaoxiang.cshtml?mainTone=Index&amp;strUserUltCode=BPM/28070907&amp;CurrentLanguage=zh-CN&amp;rnd=0.995864577205102</value>
      <webElementGuid>cd9d6fc8-bf30-4296-97e4-519ff1784ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-header-fixed&quot;]/div[@class=&quot;page-container row-fluid&quot;]/div[@class=&quot;divContent&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;ifmBg&quot;]/div[@class=&quot;col-md-12&quot;]/iframe[@id=&quot;ifm&quot;]</value>
      <webElementGuid>a4253bcf-82f2-486f-8df8-8b1bb48ea67d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifm']</value>
      <webElementGuid>5fec44c3-5da9-457b-83bc-cd70fa727c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>a19df86f-4651-4c70-8d9d-fda1828b75af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ifm' and @name = 'ifm' and @src = '/DASContract/Process/Page/ContractCaogaoxiang.cshtml?mainTone=Index&amp;strUserUltCode=BPM/28070907&amp;CurrentLanguage=zh-CN&amp;rnd=0.995864577205102']</value>
      <webElementGuid>24a8f342-01c8-4589-b392-972310f6a93f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
