<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__chk</name>
   <tag></tag>
   <elementGuidId>046c73be-a8bf-4b7d-9aba-0114462a99f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.chk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='t_drafts']/tbody/tr/td[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c9c4db5-f805-4ded-bbe9-5a666b7b46a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7a2c330d-1e94-4a38-ab61-9a1d81d3f21a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>chk</value>
      <webElementGuid>3aa5a1ed-e625-491c-a84d-5f713199749b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>P-e48bfd-df2b-4d35-abab-253bf2099868</value>
      <webElementGuid>e60960ac-9497-4be4-98b0-d166c638560e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;t_drafts&quot;)/tbody[@class=&quot;hidden_768&quot;]/tr[1]/td[@class=&quot;chkBox&quot;]/input[@class=&quot;chk&quot;]</value>
      <webElementGuid>2cdaa3f1-e9a9-4382-9e62-0aea05e2908f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DraftBox/iframe_concat(id(, , CGXFram, , ))_CGXFram</value>
      <webElementGuid>96ba3a4c-ba31-4f97-bb2b-4bb81d392eae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='P-e48bfd-df2b-4d35-abab-253bf2099868']</value>
      <webElementGuid>22b3e771-eeec-40e6-a56b-52960a00d52b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='t_drafts']/tbody/tr/td[2]/input</value>
      <webElementGuid>3a9c7ace-3754-4154-8caa-ebc95446b94a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>a1ea1cfa-e866-4d22-924c-91aadb6b9fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox']</value>
      <webElementGuid>a61213ba-f55d-4366-9ebb-a01d4e5ce7f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
