<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_draft</name>
   <tag></tag>
   <elementGuidId>a1af7b2b-c9dd-468c-a31c-8560624e4823</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ulPageSidebarMenu']/li[3]/ul/li[4]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(4) > a > span.title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>be18b424-9ece-46c2-bdb0-b12033e0b7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>8b5c321f-06e6-464b-8bae-b00c0c10ca9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>草稿箱</value>
      <webElementGuid>a358dc75-298c-4eb0-832f-528e29d62d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ulPageSidebarMenu&quot;)/li[@class=&quot;open&quot;]/ul[@class=&quot;sub-menu&quot;]/li[4]/a[1]/span[@class=&quot;title&quot;]</value>
      <webElementGuid>560618e6-e50b-4f69-91a1-91ba908e3a16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ulPageSidebarMenu']/li[3]/ul/li[4]/a/span</value>
      <webElementGuid>bd553ede-6a4e-405e-bdd7-8f6cbf55bd60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='已处理任务'])[1]/following::span[1]</value>
      <webElementGuid>e4fd3779-35d7-4201-b151-ca5d07f6da05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='已申请任务'])[1]/following::span[2]</value>
      <webElementGuid>2a199d6b-fd96-4e38-9dc5-ed971938c783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E签宝推送日志'])[1]/preceding::span[1]</value>
      <webElementGuid>8cc8592e-e9f5-4a0d-bb3c-a757e070e424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='模板管理'])[1]/preceding::span[2]</value>
      <webElementGuid>e68b7944-1124-4bad-8473-7278c051c995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='草稿箱']/parent::*</value>
      <webElementGuid>03848ae8-d4a4-4c89-b1d4-320613db1b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/ul/li[4]/a/span</value>
      <webElementGuid>6a3e8ff0-13fb-482a-92a8-e5771215f96f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '草稿箱' or . = '草稿箱')]</value>
      <webElementGuid>843f50af-725c-4a0e-8e8d-bab0a8627752</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
