<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_import</name>
   <tag></tag>
   <elementGuidId>bc6edfa0-c7cb-4164-912a-453ea0674e9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='DATASearchToolBar']/div/div/span/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.l-btn-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>127f9c24-a758-4936-a519-4c4a80bfd4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>l-btn-text</value>
      <webElementGuid>9f4996e2-574f-4fee-9e42-c272293f9c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>导出</value>
      <webElementGuid>5cf66195-0729-46a0-bc22-99a39fc59be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DATASearchToolBar&quot;)/div[@class=&quot;tbBeforeBox row&quot;]/div[@class=&quot;btn-group pull-left toolBox&quot;]/span[@class=&quot;easyui-linkbutton l-btn l-btn-small&quot;]/span[@class=&quot;l-btn-left&quot;]/span[@class=&quot;l-btn-text&quot;]</value>
      <webElementGuid>cb115b78-917e-46d3-b2d6-25cb3ace880c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/SignatureBoard/authorizerecord_page/iframe_-_MultAuthorListFrame</value>
      <webElementGuid>5ed33eb4-cdfc-46d3-a4ef-69c853d4d758</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DATASearchToolBar']/div/div/span/span/span</value>
      <webElementGuid>67dd0ccd-1ec2-4c9e-b164-420429e4d29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CID'])[1]/preceding::span[2]</value>
      <webElementGuid>9f85a4cf-131e-4b8d-be60-75730495de55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T_UPDATE_USERNAME'])[1]/preceding::span[4]</value>
      <webElementGuid>e54da0a1-be8c-44e9-b978-9fa50b186d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='导出']/parent::*</value>
      <webElementGuid>415f2ae3-57d6-4e3d-bc7a-8b008ade4484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span/span</value>
      <webElementGuid>e28c1b94-15f6-4204-85e7-1c9050ec5347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '导出' or . = '导出')]</value>
      <webElementGuid>9dbac7c3-cc0c-4219-ad1b-0d525dd006b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
