<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_-_MultAuthorListFrame</name>
   <tag></tag>
   <elementGuidId>f95aa674-1fb3-4bcb-bdaf-c6a93ff34fb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='MultAuthorListFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MultAuthorListFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>73042db9-3ba5-49e3-be94-7d8295cf2210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MultAuthorListFrame</value>
      <webElementGuid>5def2a34-bdc3-4567-a234-c245c121a8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MultAuthorListFrame</value>
      <webElementGuid>1202b545-0265-481a-b1e8-b531ebb7304e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>1c02a9d8-3900-4a88-b99f-87f0193c3201</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4d2817e0-2f53-4f2f-a28a-e4bd100220fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DASContractSignUp/BWProcess/ConTractRelatMy/Page/AuthPage/UserAuthorList_Log.cshtml</value>
      <webElementGuid>7e94b132-06ac-41a8-9791-8401db980a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MultAuthorListFrame&quot;)</value>
      <webElementGuid>b41bdb62-dcf6-4b0c-97ba-493751585016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/SignatureBoard/authorizerecord_page/iframe__ifm</value>
      <webElementGuid>33205a8e-80ea-47f6-8e00-e26d0d069d85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='MultAuthorListFrame']</value>
      <webElementGuid>3f3f07de-18f6-4051-bce3-fa8b5f949b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='RemoveContract']/iframe</value>
      <webElementGuid>4eafca62-62cf-4b5f-b406-8ec44b81ef1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/iframe</value>
      <webElementGuid>2e411a96-8630-4cf6-96f1-ffa84ad765c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'MultAuthorListFrame' and @name = 'MultAuthorListFrame' and @src = '/DASContractSignUp/BWProcess/ConTractRelatMy/Page/AuthPage/UserAuthorList_Log.cshtml']</value>
      <webElementGuid>206fa9a2-7072-41e7-8cb6-2839772d189d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
