<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_record_search</name>
   <tag></tag>
   <elementGuidId>3dd29ce2-e6a7-4d10-8a30-93d33a85f3fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@type='text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.form-control.selech</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>65947f5f-ec11-4ead-af48-93d535118d23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a2a138f3-33e6-4e2e-a72a-dd6d1b276392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control selech</value>
      <webElementGuid>b053feed-8c2d-4647-9de8-0a2f9ba020db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>DAG编号,DAG描述,合同编号,合同名称,被变更人,操作人</value>
      <webElementGuid>e4b81fa8-43db-40f9-9de7-d4200d8d56ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>DAG编号,DAG描述,合同编号,合同名称,被变更人,操作人</value>
      <webElementGuid>ea76eb9f-6c98-4f55-8224-b8ca3a988e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DATASearchToolBar&quot;)/div[@class=&quot;tbBeforeBox row&quot;]/div[@class=&quot;input-group pull-right group searchBox input-group-sm&quot;]/input[@class=&quot;form-control selech&quot;]</value>
      <webElementGuid>dbc4f6ae-b7fe-4265-a7c6-d3c79d96c540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/SignatureBoard/authorizerecord_page/iframe_-_MultAuthorListFrame</value>
      <webElementGuid>b2451599-8639-442c-ad08-ed05d7cec231</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@type='text']</value>
      <webElementGuid>0f889f76-3b3d-4ade-9f56-a2e56f6d74c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='DATASearchToolBar']/div/div[2]/input</value>
      <webElementGuid>d87f40f0-d3b9-4ad2-a37c-965c55a73bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>0a0a177b-ab80-4678-9998-2dfd7cc2e6b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'DAG编号,DAG描述,合同编号,合同名称,被变更人,操作人' and @title = 'DAG编号,DAG描述,合同编号,合同名称,被变更人,操作人']</value>
      <webElementGuid>c5b6792a-4b54-4543-844a-ec6f6b6697bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
