<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__ifm</name>
   <tag></tag>
   <elementGuidId>15327339-108f-4abf-8c64-a24f55371767</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='ifm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ifm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>89c3a2d1-a4e0-48ac-802c-05443048865f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ifm</value>
      <webElementGuid>6a613351-df15-4588-b25b-e6a558e7255e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>90345a6e-6a7b-4c62-aa02-e318b0c4ecc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>8eb00eae-da3e-4f1d-84b5-5e17d9971aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ifm</value>
      <webElementGuid>47389d03-1858-4823-bb65-14b49589d1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/DASContractFast/BWProcess/BWContractDAG/Page/DatapoolN.cshtml?mainTone=Index&amp;strUserUltCode=BPM/28070907&amp;CurrentLanguage=zh-CN&amp;rnd=0.5376210026322443</value>
      <webElementGuid>dcc67ae4-2ccd-443f-b874-5cc89021d31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;page-header-fixed&quot;]/div[@class=&quot;page-container row-fluid&quot;]/div[@class=&quot;divContent&quot;]/div[@class=&quot;page-content&quot;]/div[@class=&quot;ifmBg&quot;]/div[@class=&quot;col-md-12&quot;]/iframe[@id=&quot;ifm&quot;]</value>
      <webElementGuid>2603d086-4864-41e4-bda4-8f0cd0459ec2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='ifm']</value>
      <webElementGuid>f38d3c10-bc8f-4ae6-9214-e20385e98179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4224139a-af0e-4241-8d04-1e87f9b490fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'ifm' and @name = 'ifm' and @src = '/DASContractFast/BWProcess/BWContractDAG/Page/DatapoolN.cshtml?mainTone=Index&amp;strUserUltCode=BPM/28070907&amp;CurrentLanguage=zh-CN&amp;rnd=0.5376210026322443']</value>
      <webElementGuid>bfc60714-1476-4cb1-8c4d-5986b68020b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
