<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__signatureboard</name>
   <tag></tag>
   <elementGuidId>bb5352c6-c627-462a-9085-e1b6444ef6a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ulPageSidebarMenu']/li[6]/ul/li[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.open > ul.sub-menu > li:nth-of-type(2) > a > span.title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>186f91f5-3858-48fe-ba43-a89290d197ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>78e246c1-750b-4069-bd71-bc199ec4e8cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>签约看板</value>
      <webElementGuid>dcf679dd-5080-4c87-86a0-63a33795e4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ulPageSidebarMenu&quot;)/li[@class=&quot;open&quot;]/ul[@class=&quot;sub-menu&quot;]/li[2]/a[1]/span[@class=&quot;title&quot;]</value>
      <webElementGuid>36b31852-fb46-4798-a4e9-33763c382cae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ulPageSidebarMenu']/li[6]/ul/li[2]/a/span</value>
      <webElementGuid>08970ee7-4848-4e33-a01a-7554098ffe3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='发起签署'])[1]/following::span[1]</value>
      <webElementGuid>5dc03240-a955-435c-9ab8-fff56b74e4ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='合同签署'])[1]/following::span[3]</value>
      <webElementGuid>fac19779-dddc-46a2-8b75-4e0c3a7dca73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Office插件安装教程'])[1]/preceding::span[1]</value>
      <webElementGuid>60feef14-c748-4faf-9efc-760bc6f5e8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='黑色系'])[1]/preceding::span[3]</value>
      <webElementGuid>8d13c9cb-434f-4aa0-94e6-15608bc47d5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='签约看板']/parent::*</value>
      <webElementGuid>6d8badc5-473d-4dc9-b79b-a9111db41a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/ul/li[2]/a/span</value>
      <webElementGuid>c1d009dc-38bd-4251-beb6-6fc5723d2ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '签约看板' or . = '签约看板')]</value>
      <webElementGuid>ec574057-807b-46ab-8518-9594902e2a29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
