<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_contractmanagement</name>
   <tag></tag>
   <elementGuidId>3e97cc20-946a-442d-bb13-8af7af0d6f2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ulTopNav']/li[3]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ulTopNav > li.active > a > span.title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>37f09797-4c8e-4618-a1bb-6328c253b4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>3b5b769d-0697-41c5-b1eb-0fdc8e5a1a68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>合同管理</value>
      <webElementGuid>5127a26e-431f-4193-96b7-cef1ae142690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ulTopNav&quot;)/li[@class=&quot;active&quot;]/a[1]/span[@class=&quot;title&quot;]</value>
      <webElementGuid>ba77b4aa-600d-4ac1-8f1c-1e9aaeb9c2a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ulTopNav']/li[3]/a/span</value>
      <webElementGuid>d583f86b-d413-4ab5-a831-cd648e0107b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='百威图书馆'])[1]/following::span[1]</value>
      <webElementGuid>8b09196b-0aa3-405c-ab6b-436324564020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='流程中心'])[1]/following::span[2]</value>
      <webElementGuid>16c95c57-171b-4b28-8a53-9d4f2a737bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='报表中心'])[1]/preceding::span[2]</value>
      <webElementGuid>0ba498e8-3b91-4073-8a89-2c5ff6d06c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='合同管理']/parent::*</value>
      <webElementGuid>2a6fbbc0-3f08-49e1-bbde-cee777af8d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[3]/a/span</value>
      <webElementGuid>e4453337-ba98-4a6a-ba2a-98a20adcc803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '合同管理' or . = '合同管理')]</value>
      <webElementGuid>293a6214-eb10-40a9-ba48-5a35258601a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
