<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_DAGdatapool</name>
   <tag></tag>
   <elementGuidId>4b9a1d75-8d74-413b-8af6-d1c9ab6f1309</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ulPageSidebarMenu']/li[5]/ul/li/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.open > ul.sub-menu > li > a > span.title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd191602-c821-4341-bd41-1e4386eeb851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>655a79a6-7c21-4696-a527-1258e7d264ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DAG数据池</value>
      <webElementGuid>d2170aaf-ac02-44ce-9034-a7814ec5a87f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ulPageSidebarMenu&quot;)/li[@class=&quot;open&quot;]/ul[@class=&quot;sub-menu&quot;]/li[1]/a[1]/span[@class=&quot;title&quot;]</value>
      <webElementGuid>c61ae156-e8dc-46b3-9838-943c19907eb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ulPageSidebarMenu']/li[5]/ul/li/a/span</value>
      <webElementGuid>19cf175e-0295-44fa-84bb-aaa3b757d4ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAG管理'])[1]/following::span[2]</value>
      <webElementGuid>8fd0c040-eca6-4abf-9534-dbb38e194869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='合同附件库'])[1]/following::span[3]</value>
      <webElementGuid>a3423ff6-b1d7-4e68-9b5f-c25d3165e11a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAG看板'])[1]/preceding::span[1]</value>
      <webElementGuid>0fb1b342-bf27-4f37-9ec9-2a72d25498f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAG附件报表'])[1]/preceding::span[2]</value>
      <webElementGuid>d16c6e6d-0d52-40e0-9164-20d2c9c47c25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DAG数据池']/parent::*</value>
      <webElementGuid>d5f6cc65-b1dd-4329-92d6-267715587ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/ul/li/a/span</value>
      <webElementGuid>5cac4c23-9def-420a-94d2-ab85f45dcd65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'DAG数据池' or . = 'DAG数据池')]</value>
      <webElementGuid>0f8c638f-9d46-44fb-a0da-abf2d9bffd99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
