<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_contractsignature</name>
   <tag></tag>
   <elementGuidId>77a05877-2a7f-455b-a94d-45a85fd3030c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ulPageSidebarMenu']/li[6]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(6) > a > span.title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4251a39c-ee1a-435b-973d-fb14d682509a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>bfe7ef4e-67cc-4e25-874f-e5fb90e85241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>合同签署</value>
      <webElementGuid>8bad76ce-b0dc-4472-9466-ac47549d8689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ulPageSidebarMenu&quot;)/li[6]/a[1]/span[@class=&quot;title&quot;]</value>
      <webElementGuid>9b138792-60c0-459d-950f-508d7d225485</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ulPageSidebarMenu']/li[6]/a/span</value>
      <webElementGuid>7d1c2c3c-6f95-4f30-8b14-b363750ba128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAG数据池（批量）'])[1]/following::span[1]</value>
      <webElementGuid>b4eaf928-a56b-41ae-9b3d-7c2ec6e2de69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAG附件报表'])[1]/following::span[2]</value>
      <webElementGuid>3f661cfe-cdb7-446a-9dec-f7d6d15f70e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='发起签署'])[1]/preceding::span[2]</value>
      <webElementGuid>781e345b-3eeb-4041-ae39-10a6a4f102ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='签约看板'])[1]/preceding::span[3]</value>
      <webElementGuid>8b7b3262-e679-4eda-b233-9390bcb14274</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='合同签署']/parent::*</value>
      <webElementGuid>b2c33d71-551c-47df-95ec-17469902dbfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a/span</value>
      <webElementGuid>9d154fc0-7c41-4742-8046-4ed530e0a3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '合同签署' or . = '合同签署')]</value>
      <webElementGuid>0596187c-ca04-4192-ab8d-8e1b2a574931</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
