<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_editvendor_row1</name>
   <tag></tag>
   <elementGuidId>4940e820-8ac3-4411-a485-0ba8f8f03e12</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnQCOperation0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnQCOperation0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cd504612-1b77-429d-a785-c269df99b1bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>39b33c50-02c2-439a-908d-3cd5b2a6c312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnQCOperation0</value>
      <webElementGuid>a56ff393-345b-4e61-bd48-88e22cf82222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datagridhref</value>
      <webElementGuid>3c81c825-3d7e-4bd8-acc9-fd24865a4e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>EditSupplierMsg('0','e3423cef-d083-4f6b-a47c-2cc30ae307fb','赵少平','0592-3309876','')</value>
      <webElementGuid>585a922c-8da6-4e1c-b299-15d10b2c21da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>编辑</value>
      <webElementGuid>a65b5f4e-86bd-486f-8e4d-574343a0de53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnQCOperation0&quot;)</value>
      <webElementGuid>3ac82484-3bf7-4693-a440-181553be9b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/ContractBatchSignProcess_Page/VendorSetting_Page/iframe__SupplierFastView</value>
      <webElementGuid>0a750e5f-7ae5-4129-9aea-12bd63c873ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnQCOperation0']</value>
      <webElementGuid>297a2438-6467-4373-acd9-c805ded6d10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContractFastContractGrid_datagrid-row-r1-2-0']/td[11]/div/a</value>
      <webElementGuid>f84437e0-ce3d-4d68-8cdd-4c05ea34352b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'编辑')]</value>
      <webElementGuid>74531067-be04-47c8-ac36-218e7418d6c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='厦门市软件园二期望海路31号4楼'])[1]/following::a[1]</value>
      <webElementGuid>78a4bbb2-9fdf-442c-9dea-ad12e2f7effe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='赵少平'])[1]/following::a[1]</value>
      <webElementGuid>2a16f0fe-3e98-4c5f-b11b-524125fe9812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a2e68e26-079c-4c5b-999f-6f60f191dd3d'])[1]/preceding::a[1]</value>
      <webElementGuid>8e2cddac-9959-4537-a247-1c372127e27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAG-COM-20231122-001M'])[2]/preceding::a[1]</value>
      <webElementGuid>fc4a0af9-02ac-4760-b812-e8ecd5386e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='编辑']/parent::*</value>
      <webElementGuid>6950bfaf-783a-4ba3-841a-1431a3e02921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:;')]</value>
      <webElementGuid>c19762db-ab07-4157-a93d-95a43fd2ae5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>7e81c70d-ee81-4089-a517-bcefa60257ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and @id = 'btnQCOperation0' and (text() = '编辑' or . = '编辑')]</value>
      <webElementGuid>a8c197c6-5b63-4e0d-9534-4e12328e5df7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
