<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_editvendor_row2</name>
   <tag></tag>
   <elementGuidId>56096ce1-453f-4518-9ef6-0cb2e6dee1b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnQCOperation1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnQCOperation1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9962c653-bcba-427f-806c-eec86a6e03c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>934545bb-364a-4cba-bb48-688242e64411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnQCOperation1</value>
      <webElementGuid>b368ef27-021f-49e5-a764-9daf1ae000c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datagridhref</value>
      <webElementGuid>3cd2bb8d-9798-43e6-9b9b-a47bd64b4434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>EditSupplierMsg('1','1908c907-ae78-4a69-bd7f-6c60e03d93a4','赵少平','0592-3309876','')</value>
      <webElementGuid>e3e3ce10-9e20-49a6-89c0-bbea62ece6cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>编辑</value>
      <webElementGuid>e587ec48-648a-442f-8aff-f33a895064c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnQCOperation1&quot;)</value>
      <webElementGuid>ad2d0cfb-5061-4bab-a941-bd0b24ac1d1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/ContractBatchSignProcess_Page/VendorSetting_Page/iframe__SupplierFastView</value>
      <webElementGuid>1c4d0c69-3b55-4549-8e3f-c1fab436b4da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnQCOperation1']</value>
      <webElementGuid>448b0860-fb25-44da-b073-ee1d45ba4e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContractFastContractGrid_datagrid-row-r1-2-1']/td[11]/div/a</value>
      <webElementGuid>aaf942c8-b70c-4d24-a7c2-34b1dff97c2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'编辑')])[2]</value>
      <webElementGuid>e4ed03d4-76cd-4a95-a354-c787509b08d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='厦门市软件园二期望海路31号4楼'])[2]/following::a[1]</value>
      <webElementGuid>9da2417b-c7c1-485e-859a-7142edaea877</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='赵少平'])[1]/following::a[1]</value>
      <webElementGuid>11d253a5-b235-42d8-81d0-2be4970eb45d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='第'])[1]/preceding::a[3]</value>
      <webElementGuid>a2262b49-c7fb-4e3e-8263-dfd4c967c758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='共1页'])[1]/preceding::a[3]</value>
      <webElementGuid>d8644090-a789-4cd2-a213-ee79513e4a7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[2]</value>
      <webElementGuid>45b41a0c-cf6e-4f1b-9904-8ee8aecf2e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[11]/div/a</value>
      <webElementGuid>c6b3216f-5195-4697-bc5b-f7929f236206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and @id = 'btnQCOperation1' and (text() = '编辑' or . = '编辑')]</value>
      <webElementGuid>c3f654c5-6e73-4135-841b-4b6e7c279ba2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
