<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_row1_save</name>
   <tag></tag>
   <elementGuidId>7e543e2a-a259-4c29-9fcf-8c8f20ea182f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnQCOperation0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnQCOperation0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bdd375c8-cf23-4148-a0ae-9e7a2272a7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>cfc32278-62f3-414a-bb02-034234355cdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnQCOperation0</value>
      <webElementGuid>705d832b-3c94-47c9-999a-16267eefcc6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datagridhref</value>
      <webElementGuid>12b195fe-ac86-4646-b09e-ec196430e141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>EditSupplierMsg('0','1fb296f1-381c-402a-ae59-6a998400af30','赵少平','0592-3309876','')</value>
      <webElementGuid>2082c957-e1e6-4cad-9b1b-e12a31152e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>保存</value>
      <webElementGuid>473a5e14-1d9b-493d-a120-1fa9b66c2914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>保存</value>
      <webElementGuid>0125f47c-0d26-4c0b-aca5-468eeb09a90f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnQCOperation0&quot;)</value>
      <webElementGuid>0ac9bfd6-6d64-405e-9c90-4d19a6856c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/ContractBatchSignProcess_Page/VendorSetting_Page/iframe__SupplierFastView</value>
      <webElementGuid>67c145aa-626b-4450-b47f-82619cd580ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnQCOperation0']</value>
      <webElementGuid>98c78d84-477c-4660-ac8f-147c540f8b19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContractFastContractGrid_datagrid-row-r1-2-0']/td[11]/div/a</value>
      <webElementGuid>b7daa56a-6c23-4293-99fa-f314a6a6fa73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'保存')]</value>
      <webElementGuid>78b6ae47-7cc4-4bd8-a674-3a64e1998572</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='百威（厦门）管理运营有限公司测试V1'])[1]/following::a[1]</value>
      <webElementGuid>cd24f8ff-ef2f-4722-ab4b-9a8052f3c6d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CON-COM-20231122-001M'])[1]/following::a[1]</value>
      <webElementGuid>d9341f51-3e51-4056-8b86-c738082d001f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='a2e68e26-079c-4c5b-999f-6f60f191dd3d'])[1]/preceding::a[1]</value>
      <webElementGuid>3696859f-d2e6-4fa3-8c3a-390c8e053ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DAG-COM-20231122-001M'])[2]/preceding::a[1]</value>
      <webElementGuid>26a4c5f8-b75b-4e0f-bc0d-7df11def693e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='保存']/parent::*</value>
      <webElementGuid>27515d92-4108-41dd-92a0-f19c273d5062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:;')]</value>
      <webElementGuid>2f4fc296-2257-443f-9bdc-f6fc66215de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>9872ef45-3801-45ed-9751-47fd06e10796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and @id = 'btnQCOperation0' and (text() = '保存' or . = '保存')]</value>
      <webElementGuid>f957b6ec-1072-4f6c-b3a3-a79814c32cde</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
