<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_vendorsetting</name>
   <tag></tag>
   <elementGuidId>d8bb6376-fc00-40b5-9b94-7e5bfbbff4ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#JBRSET</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='JBRSET']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>59e11410-4e40-4e11-a55a-e9d41eefd809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5efd5fc2-c19c-4164-b2d3-fb8689dfdc7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>JBRSET</value>
      <webElementGuid>ba0287e5-a19b-4972-b1b9-46cfd2793204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default pull-left btn-sm btnBlueColor</value>
      <webElementGuid>2c162596-d97a-40f2-985b-0acf5950201c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n-text</name>
      <type>Main</type>
      <value>ce_plsz</value>
      <webElementGuid>06403e13-5273-4c11-8fa2-5996ea0199e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>对方经办人批量设置</value>
      <webElementGuid>d911b158-4f27-45a9-95a6-e625bff8418d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JBRSET&quot;)</value>
      <webElementGuid>d5f0eed0-821d-49d5-857f-b1cc59a56f7e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='JBRSET']</value>
      <webElementGuid>d6f5b8c9-8fdb-4bba-b04c-adaaebebfb10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myTimeLine']/button</value>
      <webElementGuid>9e88ef0c-b22a-4cf4-a02c-8cd47360b501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='合同签署流程'])[2]/following::button[1]</value>
      <webElementGuid>60735d11-2497-414a-8016-29c2bd965aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='保存'])[1]/preceding::button[1]</value>
      <webElementGuid>08986bb9-104b-41c6-a516-8402a6d04789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提交'])[1]/preceding::button[2]</value>
      <webElementGuid>be259c8c-70b5-401f-b5c0-bf1f05c123e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='对方经办人批量设置']/parent::*</value>
      <webElementGuid>f889fbe3-bfe2-46bf-a1a0-bde8118df9ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>da57b0bd-7899-43f2-9eaf-bca5106a14da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'JBRSET' and (text() = '对方经办人批量设置' or . = '对方经办人批量设置')]</value>
      <webElementGuid>54732809-084d-4d66-b83a-a9e2a1fbc1bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
