<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_row2_save</name>
   <tag></tag>
   <elementGuidId>35000c76-15b4-4448-adb8-2397ca7d5ff5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnQCOperation1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnQCOperation1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>04ca5cb4-ad02-4972-a415-3519ed19b6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>8d4cd391-0f57-42b8-be38-790e14d383db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnQCOperation1</value>
      <webElementGuid>ca1b1a93-7121-47d2-a2ef-6ca1a40edc4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>datagridhref</value>
      <webElementGuid>967eac97-5105-43a7-ba5a-623b408bb383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>EditSupplierMsg('1','1908c907-ae78-4a69-bd7f-6c60e03d93a4','赵少平','0592-3309876','')</value>
      <webElementGuid>01468cb3-fef6-4171-8dd7-6726dd02c18c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>保存</value>
      <webElementGuid>a78e8b50-1554-4b76-a890-9b495c37af90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>保存</value>
      <webElementGuid>7ad48e0c-0091-4ba1-aa61-fc56498d2851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnQCOperation1&quot;)</value>
      <webElementGuid>ffabfdee-94ee-44dc-b7c8-941da014c961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_ABI One Process Center/DAGDataPool/ContractBatchSignProcess_Page/VendorSetting_Page/iframe__SupplierFastView</value>
      <webElementGuid>27e7a058-d56a-44b7-a713-58324ab8aebe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnQCOperation1']</value>
      <webElementGuid>41609695-e641-4c08-a2e3-0674be5b010d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='ContractFastContractGrid_datagrid-row-r1-2-1']/td[11]/div/a</value>
      <webElementGuid>ca371ada-4f2b-4867-a40a-175589c6b515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'保存')]</value>
      <webElementGuid>cb6eacc3-953c-4489-9599-9019f1a5df39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='百威（厦门）管理运营有限公司测试V1'])[2]/following::a[1]</value>
      <webElementGuid>933463d4-bade-4b1e-9ece-0fdacea602f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CON-COM-20231122-002M'])[1]/following::a[1]</value>
      <webElementGuid>646c04be-db44-49b6-bb42-63b685516093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='第'])[1]/preceding::a[3]</value>
      <webElementGuid>e24ce0c2-b372-4b1d-a02f-71b509db6939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='共1页'])[1]/preceding::a[3]</value>
      <webElementGuid>baec2cdd-ffff-4f44-b392-b420a0403357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='保存']/parent::*</value>
      <webElementGuid>6fd52d5e-cc17-4137-ab71-b35b5765329f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:;')])[2]</value>
      <webElementGuid>c4ac50c7-9939-471e-b21e-e13422842d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[11]/div/a</value>
      <webElementGuid>cf08c0ef-59e2-4d13-995b-6ed3b8cb2751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and @id = 'btnQCOperation1' and (text() = '保存' or . = '保存')]</value>
      <webElementGuid>a58b6e97-1992-4ee8-be4c-6a92462f0098</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
