<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__SupplierFastView</name>
   <tag></tag>
   <elementGuidId>ac24f6f7-6fad-4261-a99a-01abe177347f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SupplierFastView</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='SupplierFastView']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>546d53ac-f955-4104-97d8-7878a7c97584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SupplierFastView</value>
      <webElementGuid>edd6e3a9-38df-4bbc-bc8a-d4a674ad0b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SupplierFastView</value>
      <webElementGuid>0b82d543-b3d8-4acc-9257-2daad3648ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>60a9d201-e957-4e6c-91a2-bac33ecf3367</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d38a0116-72ca-46ce-99cb-a85eb2dcb27a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>ChoosePage/ChooseSupplierFastGrid.cshtml?PCCID=P-daf676-1516-4571-9500-d3c9f9544532</value>
      <webElementGuid>1ea83194-de87-4cd8-bb78-b053ad0a9807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SupplierFastView&quot;)</value>
      <webElementGuid>67dd2b56-9660-4423-a05c-14ff2cf3d05c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='SupplierFastView']</value>
      <webElementGuid>d05d5061-3347-4744-bde1-cfb7aa29f182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ChooseSupplierFastGrid']/iframe</value>
      <webElementGuid>bd50d3e0-716a-4869-bd11-0cdaf72381ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='对方经办人批量设置'])[2]/following::iframe[1]</value>
      <webElementGuid>d351527e-ee4d-4a32-b37d-97a2b46db887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='自由上传合同文本'])[1]/following::iframe[1]</value>
      <webElementGuid>1a0c5a59-cf48-408f-b7db-ddbd6cdee5d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='关闭'])[2]/preceding::iframe[1]</value>
      <webElementGuid>80e8a499-67f6-444e-8f2e-ec4a521516c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='提交'])[2]/preceding::iframe[1]</value>
      <webElementGuid>7eda4c9c-ce6f-4535-ab26-32de748274a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>de494de9-af8d-4019-92ea-19f3b3a201bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'SupplierFastView' and @name = 'SupplierFastView' and @src = 'ChoosePage/ChooseSupplierFastGrid.cshtml?PCCID=P-daf676-1516-4571-9500-d3c9f9544532']</value>
      <webElementGuid>57e08914-dfcb-499d-9e51-db710d1e7a17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
